// Single source of truth for the Recruitment Information trends report (part of
// Workplace).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Workplace', cat_l2='Recruitment Information', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const workplaceRecruitmentInformationSubReport: TikTokSubcategoryReport = {
  subcategory: "Recruitment Information",
  parentCategory: "Workplace",
  parentSlug: "workplace",
  region: "global",
  computedAt: "2026-10-09T04:35:33Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-10",
  topics: [
    {
      topic: "partnership paid",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 3834,
      topCountries: ["ID", "BR", "MX", "CO"],
    },
    {
      topic: "side hustle para personal de salud",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 445,
      topCountries: ["US", "TR", "DE", "MX", "PH"],
    },
    {
      topic: "a daily part time job",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 1088,
      topCountries: ["ID", "TH", "MY", "PH", "SA"],
    },
    {
      topic: "cruise ship salary per month",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 136,
      topCountries: ["ZA", "PH", "KE", "JM"],
    },
    {
      topic: "TikTok artist collaboration monetization",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 301,
      topCountries: [],
    },
    {
      topic: "FreshGraduate",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 600,
      topCountries: ["ID", "PH", "EG", "MY", "NG"],
    },
    {
      topic: "best walt disney world jobs ranked",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "ID", "MX", "ES", "US"],
    },
    {
      topic: "concentrix typing test passing score",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "EG", "ZA", "SA"],
    },
    {
      topic: "reschedule interview",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 405,
      topCountries: ["ID", "PH", "MY", "ZA"],
    },
    {
      topic: "JobSearching",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 3781,
      topCountries: ["IT", "MM", "ZA", "CD", "GB"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "partnership paid",
    audience: "unknown 35+, Indonesia (dominant segment, snapshot at collection date)",
  },
};
