// Single source of truth for the Education - Others trends report (part of
// Education).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Education', cat_l2='Education - Others', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const educationEducationOthersSubReport: TikTokSubcategoryReport = {
  subcategory: "Education - Others",
  parentCategory: "Education",
  parentSlug: "education",
  region: "global",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "sincere metaphors compilation",
      growthMultiplier: 8,
      trust: "high",
      videoNum: 390,
      topCountries: ["US", "CA", "AU", "ZA", "NZ"],
    },
    {
      topic: "presentation stab pen",
      growthMultiplier: 5,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "PH", "MY", "AE", "CA"],
    },
    {
      topic: "teaching money how to multiply",
      growthMultiplier: 5,
      trust: "high",
      videoNum: null,
      topCountries: ["ID", "PH", "ZA", "AU", "UG"],
    },
    {
      topic: "learning educational videos only",
      growthMultiplier: 5,
      trust: "high",
      videoNum: 409,
      topCountries: ["PH", "KE", "GH", "MM", "UG"],
    },
    {
      topic: "study for exam",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 2951,
      topCountries: ["MY", "PH", "ID", "PK"],
    },
    {
      topic: "Speed reading",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 622,
      topCountries: ["PH", "AU", "CA", "SA", "ID"],
    },
    {
      topic: "Grades",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 826,
      topCountries: ["PH", "CA", "AU", "SG", "AE"],
    },
    {
      topic: "educational learning content for women",
      growthMultiplier: 3,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "PK", "ZA", "EG", "MM"],
    },
    {
      topic: "school fees 2500000",
      growthMultiplier: 2,
      trust: "high",
      videoNum: null,
      topCountries: ["UG", "KE", "RW", "ZW"],
    },
    {
      topic: "educly",
      growthMultiplier: 2,
      trust: "high",
      videoNum: null,
      topCountries: ["MX", "PE", "VE", "CO", "EC"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "sincere metaphors compilation",
    audience: "female 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
