// Single source of truth for the TikTok trends in Myanmar report.
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region='MM', growth_reason='ok', trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokCountryReport } from "./tiktok-country-report-types";

export const mmCountryReport: TikTokCountryReport = {
  country: "Myanmar",
  countryCode: "MM",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "waterphone sound",
      category: "Science and Technology",
      subcategory: "Web Recources Download",
      growthMultiplier: 86,
      trust: "high",
      videoNum: 1966,
      topCountries: ["US", "ID", "DE", "MM", "MY"],
    },
    {
      topic: "spa date",
      category: "Local Life",
      subcategory: "Leisure and Entertainment",
      growthMultiplier: 83,
      trust: "high",
      videoNum: 1110,
      topCountries: ["MM", "ZA", "ID", "NG", "PH"],
    },
    {
      topic: "pull tabs big win",
      category: "Personal Interests and Hobbies",
      subcategory: "Other Hobbies",
      growthMultiplier: 80,
      trust: "high",
      videoNum: null,
      topCountries: ["MM", "PH", "ID", "MY", "TH"],
    },
    {
      topic: "ip 18 pro max",
      category: "Science and Technology",
      subcategory: "Digital",
      growthMultiplier: 18,
      trust: "high",
      videoNum: 7873,
      topCountries: ["ID", "MM", "IQ", "PH"],
    },
    {
      topic: "realistic fitness routine for beginners",
      category: "Sports",
      subcategory: "Fitness",
      growthMultiplier: 17,
      trust: "high",
      videoNum: 575,
      topCountries: ["EG", "PK", "IQ", "MM", "DZ"],
    },
    {
      topic: "KitchenCooking",
      category: "Gourmet",
      subcategory: "Food Tutorials",
      growthMultiplier: 6,
      trust: "high",
      videoNum: 870,
      topCountries: ["MM", "MY", "TH", "JP"],
    },
    {
      topic: "createfasterwithtako",
      category: "Gourmet",
      subcategory: "Food Tutorials",
      growthMultiplier: 4,
      trust: "high",
      videoNum: 414,
      topCountries: ["BD", "IQ", "MM", "NG"],
    },
    {
      topic: "adorable dogs",
      category: "Personal Interests and Hobbies",
      subcategory: "Gardening and Pet",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 56967,
      topCountries: ["MM", "ID", "TH", "JP"],
    },
    {
      topic: "creatorinsighthashtags",
      category: "Science and Technology",
      subcategory: "Internet",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 738,
      topCountries: ["MM", "ID", "ET", "BD"],
    },
    {
      topic: "puzzle 1000000000000000000000000000",
      category: "Personal Interests and Hobbies",
      subcategory: "Toys",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 1157,
      topCountries: ["BD", "MM", "IQ", "ID"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this country's own search-demand series (not global demand). Mixes every category — for a single-category view across all countries, see the niche reports instead. Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "waterphone sound",
    audience: "unknown 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
