// Single source of truth for the Working Policies trends report (part of
// Workplace).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Workplace', cat_l2='Working Policies', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const workplaceWorkingPoliciesSubReport: TikTokSubcategoryReport = {
  subcategory: "Working Policies",
  parentCategory: "Workplace",
  parentSlug: "workplace",
  region: "global",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "live incentive program 2 part",
      growthMultiplier: 12,
      trust: "high",
      videoNum: null,
      topCountries: ["PK", "ID", "PH", "NP"],
    },
    {
      topic: "butler salary",
      growthMultiplier: 2,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "CA", "PH", "MY", "EG"],
    },
    {
      topic: "live incentive program content ideas",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 786,
      topCountries: ["PK", "SN", "PE", "VE"],
    },
    {
      topic: "job vacancies hours ago",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 572,
      topCountries: ["KE", "UG", "GH", "ZM"],
    },
    {
      topic: "albania salary per month",
      growthMultiplier: 2,
      trust: "high",
      videoNum: null,
      topCountries: ["UG", "PH", "NG", "AE", "SA"],
    },
    {
      topic: "ISR training",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 498,
      topCountries: ["CA", "AU", "ZA", "SA", "NZ"],
    },
    {
      topic: "understanding live incentive programs",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 1044,
      topCountries: ["MX", "GT", "PE", "VE", "BR"],
    },
    {
      topic: "8171 bisp 8 171 online apply link",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 276,
      topCountries: ["PK", "SA", "NP", "AE"],
    },
    {
      topic: "how to join live incentive program 2026",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 540,
      topCountries: ["BD", "PK", "PH", "ZA"],
    },
    {
      topic: "policies",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 866,
      topCountries: ["BR", "GB", "PH", "MX", "AR"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "live incentive program 2 part",
    audience: "unknown 25-34, Pakistan (dominant segment, snapshot at collection date)",
  },
};
