// Single source of truth for the TikTok trends in Bangladesh report.
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region='BD', growth_reason='ok', trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokCountryReport } from "./tiktok-country-report-types";

export const bdCountryReport: TikTokCountryReport = {
  country: "Bangladesh",
  countryCode: "BD",
  computedAt: "2026-10-09T04:35:33Z",
  windowStart: "2026-08-09",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-10",
  topics: [
    {
      topic: "messi vs england reaccion pt 2 fut crunch",
      category: "Sports",
      subcategory: "Physical Sports",
      growthMultiplier: 32,
      trust: "high",
      videoNum: null,
      topCountries: ["ID", "NG", "AR", "ZA", "BD"],
    },
    {
      topic: "a chill day inside rock am ring",
      category: "Sports",
      subcategory: "Physical Sports",
      growthMultiplier: 9,
      trust: "high",
      videoNum: 196,
      topCountries: ["PK", "SA", "ET", "BD"],
    },
    {
      topic: "car lighting features that stand out",
      category: "Vehicles & Transportation",
      subcategory: "Transport Equipment",
      growthMultiplier: 9,
      trust: "high",
      videoNum: null,
      topCountries: ["PK", "SA", "ET", "BD"],
    },
    {
      topic: "viral funny shorts",
      category: "TikTok's Featured Content",
      subcategory: "Trends/Challenges",
      growthMultiplier: 8,
      trust: "high",
      videoNum: null,
      topCountries: ["BD", "PK", "ID", "EG"],
    },
    {
      topic: "healed purple eye",
      category: "Healthcare",
      subcategory: "Modern Medicine",
      growthMultiplier: 6,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "PK", "BD", "RU", "UA"],
    },
    {
      topic: "4k 120 fps upload method",
      category: "Science and Technology",
      subcategory: "Software",
      growthMultiplier: 5,
      trust: "high",
      videoNum: 550,
      topCountries: ["BD", "NP", "PH", "MM", "JP"],
    },
    {
      topic: "createfasterwithtako",
      category: "Gourmet",
      subcategory: "Food Tutorials",
      growthMultiplier: 5,
      trust: "high",
      videoNum: 414,
      topCountries: ["BD", "IQ", "MM", "NG"],
    },
    {
      topic: "مقارنة كاميرا هاتفين في التصوير",
      category: "Science and Technology",
      subcategory: "Digital",
      growthMultiplier: 5,
      trust: "high",
      videoNum: 140,
      topCountries: ["ID", "MX", "BD", "VN", "TH"],
    },
    {
      topic: "speaker cleaner 30000000000hz redmi",
      category: "Science and Technology",
      subcategory: "Digital",
      growthMultiplier: 5,
      trust: "high",
      videoNum: 1190,
      topCountries: ["ID", "PH", "BD", "MM"],
    },
    {
      topic: "pink blush song dance",
      category: "Dance",
      subcategory: "Dance Trend",
      growthMultiplier: 5,
      trust: "high",
      videoNum: null,
      topCountries: ["BD", "KE", "PH", "AU"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this country's own search-demand series (not global demand). Mixes every category — for a single-category view across all countries, see the niche reports instead. Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "messi vs england reaccion pt 2 fut crunch",
    audience: "unknown 18-24, Indonesia (dominant segment, snapshot at collection date)",
  },
};
