// Single source of truth for the Other Hobbies trends report (part of
// Personal Interests and Hobbies).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Personal Interests and Hobbies', cat_l2='Other Hobbies', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const hobbiesOtherHobbiesSubReport: TikTokSubcategoryReport = {
  subcategory: "Other Hobbies",
  parentCategory: "Personal Interests and Hobbies",
  parentSlug: "hobbies",
  region: "global",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "breaker review xxl 2 3 4 5 6 7 8 9 10",
      growthMultiplier: 926,
      trust: "high",
      videoNum: 742,
      topCountries: ["ID", "BR", "MY", "PK", "PH"],
    },
    {
      topic: "star pose hand tutorial",
      growthMultiplier: 96,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "ZA", "NG", "CA", "BR"],
    },
    {
      topic: "family time game",
      growthMultiplier: 43,
      trust: "high",
      videoNum: 662,
      topCountries: ["US", "ID", "PH", "TH", "VN"],
    },
    {
      topic: "day 276 poker face",
      growthMultiplier: 22,
      trust: "high",
      videoNum: null,
      topCountries: ["GB", "PH", "RU", "BR", "DE"],
    },
    {
      topic: "how to make pennies large",
      growthMultiplier: 18,
      trust: "high",
      videoNum: null,
      topCountries: ["ZA", "GH", "KE", "NG", "PH"],
    },
    {
      topic: "easy survival tools to carry in forest",
      growthMultiplier: 17,
      trust: "high",
      videoNum: null,
      topCountries: ["MM", "IQ", "EG", "BD", "SN"],
    },
    {
      topic: "how to play people the game",
      growthMultiplier: 9,
      trust: "high",
      videoNum: 514,
      topCountries: ["PH", "ID", "BR", "MY"],
    },
    {
      topic: "Simple survival tools to pack",
      growthMultiplier: 7,
      trust: "high",
      videoNum: null,
      topCountries: ["TH", "TR", "ID", "PH"],
    },
    {
      topic: "pull tabs big win",
      growthMultiplier: 5,
      trust: "high",
      videoNum: null,
      topCountries: ["MM", "PH", "ID", "MY", "TH"],
    },
    {
      topic: "monster can",
      growthMultiplier: 4,
      trust: "high",
      videoNum: 869,
      topCountries: ["DE", "IT", "FR", "ES", "PH"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "breaker review xxl 2 3 4 5 6 7 8 9 10",
    audience: "unknown 25-34, Indonesia (dominant segment, snapshot at collection date)",
  },
};
