// Single source of truth for the Games trends report (part of
// ACGN (Anime, Comics, Games & Novels)).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='ACGN', cat_l2='Games', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const acgnGamesSubReport: TikTokSubcategoryReport = {
  subcategory: "Games",
  parentCategory: "ACGN (Anime, Comics, Games & Novels)",
  parentSlug: "acgn",
  region: "global",
  computedAt: "2026-10-09T04:35:33Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-10",
  topics: [
    {
      topic: "melissa doi ending call",
      growthMultiplier: 1019,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "GB", "DE", "IT", "NL"],
    },
    {
      topic: "part two of the story fruit 2 mask",
      growthMultiplier: 337,
      trust: "high",
      videoNum: 931,
      topCountries: ["US", "PH", "CA", "PK", "LB"],
    },
    {
      topic: "scp 953 explained",
      growthMultiplier: 80,
      trust: "high",
      videoNum: 995,
      topCountries: ["US", "DE", "PL", "MX", "PH"],
    },
    {
      topic: "gg funkin eazy ai",
      growthMultiplier: 60,
      trust: "high",
      videoNum: 920,
      topCountries: ["PH", "ID", "CA", "MY", "VN"],
    },
    {
      topic: "severian zzz gameplay",
      growthMultiplier: 57,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "PH", "ID", "VN", "BR"],
    },
    {
      topic: "sensi geral 198 red dot 200 2x 200 4x 198 2026 com dpi1vs4",
      growthMultiplier: 53,
      trust: "high",
      videoNum: null,
      topCountries: ["BD", "NP", "BR", "PK"],
    },
    {
      topic: "what happened to thing 2",
      growthMultiplier: 18,
      trust: "high",
      videoNum: 519,
      topCountries: ["US", "GB", "PH", "CA", "MX"],
    },
    {
      topic: "nascar game trolling",
      growthMultiplier: 10,
      trust: "high",
      videoNum: 269,
      topCountries: ["US", "GB", "CA", "AU", "PH"],
    },
    {
      topic: "uzi diamond light reflect",
      growthMultiplier: 9,
      trust: "high",
      videoNum: 850,
      topCountries: ["US", "GB", "PH", "CA", "IT"],
    },
    {
      topic: "to be continued clip",
      growthMultiplier: 4,
      trust: "high",
      videoNum: 308,
      topCountries: ["PH", "PK", "NG", "ZA", "MY"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "melissa doi ending call",
    audience: "female 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
