// Single source of truth for the Traffic Services trends report (part of
// Vehicles & Transportation).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Vehicles & Transportation', cat_l2='Traffic Services', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const vehiclesTrafficServicesSubReport: TikTokSubcategoryReport = {
  subcategory: "Traffic Services",
  parentCategory: "Vehicles & Transportation",
  parentSlug: "vehicles",
  region: "global",
  computedAt: "2026-10-09T04:35:33Z",
  windowStart: "2026-08-09",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-09",
  topics: [
    {
      topic: "الاقلاع الفوري القوات الجوية الملكية السعودية",
      growthMultiplier: 7,
      trust: "high",
      videoNum: 330,
      topCountries: ["SA", "IQ", "KW", "AE"],
    },
    {
      topic: "Taxi life",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 1015,
      topCountries: ["IQ", "MX", "DE", "BR"],
    },
    {
      topic: "delta key 2026 tutorial",
      growthMultiplier: 3,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "ID", "TR", "MX", "MY"],
    },
    {
      topic: "england park the bus",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 1681,
      topCountries: ["ID", "MY", "PH", "ZA", "VN"],
    },
    {
      topic: "florida walmart parking lot",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 776,
      topCountries: ["US", "GB", "CA", "FR", "ES"],
    },
    {
      topic: "royal gorge train",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 3808,
      topCountries: ["US", "PH", "CA", "AU", "MX"],
    },
    {
      topic: "ping driver",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 459,
      topCountries: ["PH", "SA", "CA", "GB", "ID"],
    },
    {
      topic: "idr meaning license",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "CA", "AE", "SA"],
    },
    {
      topic: "trucking in europe",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 529,
      topCountries: ["PK", "AE", "SA", "KE"],
    },
    {
      topic: "car maintenance tools",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1127,
      topCountries: ["IQ", "MM", "MY", "ID"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "الاقلاع الفوري القوات الجوية الملكية السعودية",
    audience: "male 25-34, Saudi Arabia (dominant segment, snapshot at collection date)",
  },
};
