// Single source of truth for the Geology Knowledge trends report (part of
// Science Knowledge).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Science Knowledge', cat_l2='Geology Knowledge', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const scienceFactsGeologyKnowledgeSubReport: TikTokSubcategoryReport = {
  subcategory: "Geology Knowledge",
  parentCategory: "Science Knowledge",
  parentSlug: "science-facts",
  region: "global",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "there is a new rock by the water",
      growthMultiplier: 8,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "BR", "PH", "VN", "MX"],
    },
    {
      topic: "autum ",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 3008,
      topCountries: ["ID", "UA", "PH", "MX", "CA"],
    },
    {
      topic: "شكل البحر الاسود",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 176,
      topCountries: ["EG", "IL", "IQ", "LY"],
    },
    {
      topic: "biggest pearl ever found",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 249,
      topCountries: ["GB", "PH", "NG", "ZA"],
    },
    {
      topic: "what shipwreck finds reveal",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["ID", "VN", "GB", "MX", "PH"],
    },
    {
      topic: "british shipwreck treasures explored",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["ID", "VN", "GB", "MX", "PH"],
    },
    {
      topic: "how much is 1 light day",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["CA", "PH", "AU", "RS"],
    },
    {
      topic: "what old diamonds say about earth",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "ID", "MY", "CA"],
    },
    {
      topic: "forest nature",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 2062,
      topCountries: ["PH", "NP", "LK", "PK", "MM"],
    },
    {
      topic: "Which hull feels safer in waves",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "DO", "MX", "GB", "DE"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "there is a new rock by the water",
    audience: "male 18-24, Brazil (dominant segment, snapshot at collection date)",
  },
};
