// Single source of truth for the TikTok trends in United States report.
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region='US', growth_reason='ok', trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokCountryReport } from "./tiktok-country-report-types";

export const usCountryReport: TikTokCountryReport = {
  country: "United States",
  countryCode: "US",
  computedAt: "2026-10-08T04:24:18Z",
  windowStart: "2026-08-08",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-08",
  topics: [
    {
      topic: "police officer the final part 3 review car",
      category: "Vehicles & Transportation",
      subcategory: "Transport Equipment",
      growthMultiplier: 6,
      trust: "high",
      videoNum: 1016,
      topCountries: ["US", "AU", "PH", "CA", "KE"],
    },
    {
      topic: "putting ai in middle of movie",
      category: "Science and Technology",
      subcategory: "Internet",
      growthMultiplier: 6,
      trust: "high",
      videoNum: 441,
      topCountries: ["US", "NG", "SG", "PH", "DE"],
    },
    {
      topic: "portrait reveal made for a viral review",
      category: "Personal Interests and Hobbies",
      subcategory: "Art related Interests",
      growthMultiplier: 4,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "CA", "GB", "ZA", "AU"],
    },
    {
      topic: "waterphone sound",
      category: "Science and Technology",
      subcategory: "Web Recources Download",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 1966,
      topCountries: ["US", "ID", "DE", "MM", "MY"],
    },
    {
      topic: "uzi diamond light reflect",
      category: "ACGN",
      subcategory: "Games",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 850,
      topCountries: ["US", "GB", "PH", "CA", "IT"],
    },
    {
      topic: "pump three diesel orginal",
      category: "Vehicles & Transportation",
      subcategory: "Transport Equipment",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 669,
      topCountries: ["US", "PH", "GH", "UG", "MY"],
    },
    {
      topic: "royal gorge train",
      category: "Vehicles & Transportation",
      subcategory: "Traffic Services",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 3808,
      topCountries: ["US", "PH", "CA", "AU", "MX"],
    },
    {
      topic: "bronco sport",
      category: "Vehicles & Transportation",
      subcategory: "Transport Equipment",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 8604,
      topCountries: ["US", "ZA", "DE", "GB", "CA"],
    },
    {
      topic: "the caravelle myrtle beach",
      category: "Tourism",
      subcategory: "Tourism Service",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 16182,
      topCountries: ["US", "PK", "EG", "BD", "PH"],
    },
    {
      topic: "smart door solutions for pet owners",
      category: "Household",
      subcategory: "Home Life",
      growthMultiplier: 3,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "GB", "CA", "PH", "DE"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this country's own search-demand series (not global demand). Mixes every category — for a single-category view across all countries, see the niche reports instead. Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "police officer the final part 3 review car",
    audience: "female 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
