// Single source of truth for the Education Supplies trends report (part of
// Education).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Education', cat_l2='Education Supplies', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const educationEducationSuppliesSubReport: TikTokSubcategoryReport = {
  subcategory: "Education Supplies",
  parentCategory: "Education",
  parentSlug: "education",
  region: "global",
  computedAt: "2026-10-08T04:24:18Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-08",
  topics: [
    {
      topic: "الزي المدرسي العراقي الجديد 2027",
      growthMultiplier: 7,
      trust: "high",
      videoNum: 785,
      topCountries: ["IQ", "EG", "TR", "AE"],
    },
    {
      topic: "back to school supply hauls",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 940,
      topCountries: ["MX", "CA", "JM", "LB", "PH"],
    },
    {
      topic: "back school haul",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 891,
      topCountries: ["TR", "MX", "EG", "VE"],
    },
    {
      topic: "student must-haves for everyday class",
      growthMultiplier: 2,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "CA", "MX", "ID", "GB"],
    },
    {
      topic: "notebook notes",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 1107,
      topCountries: ["PH", "BR", "ID", "CA", "EG"],
    },
    {
      topic: "Cute and useful stationery finds",
      growthMultiplier: 2,
      trust: "high",
      videoNum: null,
      topCountries: ["ID", "CA", "BR", "SA", "MX"],
    },
    {
      topic: "must-have school supplies for students",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["VN", "BR", "ID", "JP", "PL"],
    },
    {
      topic: "crossword puzzle book",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 539,
      topCountries: ["PH", "MY", "ID", "TH", "CA"],
    },
    {
      topic: "College binder",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 526,
      topCountries: ["PH", "ID", "CA", "MV", "OM"],
    },
    {
      topic: "sticky notes for studying",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 789,
      topCountries: ["PH", "ID", "MY", "BD", "MX"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "الزي المدرسي العراقي الجديد 2027",
    audience: "unknown 25-34, Iraq (dominant segment, snapshot at collection date)",
  },
};
