// Single source of truth for the Other-Workplace trends report (part of
// Workplace).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Workplace', cat_l2='Other-Workplace', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const workplaceOtherWorkplaceSubReport: TikTokSubcategoryReport = {
  subcategory: "Other-Workplace",
  parentCategory: "Workplace",
  parentSlug: "workplace",
  region: "global",
  computedAt: "2026-10-08T04:24:18Z",
  windowStart: "2026-08-09",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-08",
  topics: [
    {
      topic: "you're hired",
      growthMultiplier: 14,
      trust: "high",
      videoNum: 526,
      topCountries: ["PH", "MX", "BR", "TH", "ID"],
    },
    {
      topic: "best client ddnet",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 112,
      topCountries: ["RU", "BY", "UA", "KZ", "TR"],
    },
    {
      topic: "salary cap",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 418,
      topCountries: ["ID", "CA", "AU", "PH", "MX"],
    },
    {
      topic: "NightShifts",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 929,
      topCountries: ["LY", "PH", "ZA", "SA", "AU"],
    },
    {
      topic: "visiting friends at work",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 368,
      topCountries: ["GB", "PH", "CA", "AU", "ID"],
    },
    {
      topic: "work office",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1333,
      topCountries: ["BD", "PH", "ID", "PK", "MY"],
    },
    {
      topic: "CareerTips",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1244,
      topCountries: ["NG", "ZA", "ID", "BD"],
    },
    {
      topic: "Employee",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1006,
      topCountries: ["MM", "PH", "AU", "CA", "SA"],
    },
    {
      topic: "work-life balance by disney world",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "MX", "BR", "ID", "PE"],
    },
    {
      topic: "work essentials",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 801,
      topCountries: ["GB", "DE", "PH", "ID", "MY"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "you're hired",
    audience: "unknown 25-34, Philippines (dominant segment, snapshot at collection date)",
  },
};
