// Single source of truth for the TikTok trends in Vietnam report.
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region='VN', growth_reason='ok', trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokCountryReport } from "./tiktok-country-report-types";

export const vnCountryReport: TikTokCountryReport = {
  country: "Vietnam",
  countryCode: "VN",
  computedAt: "2026-10-09T04:35:33Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-09",
  topics: [
    {
      topic: "new lionel messi",
      category: "Sports",
      subcategory: "Physical Sports",
      growthMultiplier: 854,
      trust: "high",
      videoNum: 1069,
      topCountries: ["VN", "BD", "NG", "JP"],
    },
    {
      topic: "TheMissingPiece",
      category: "Culture",
      subcategory: "Serious Literature",
      growthMultiplier: 99,
      trust: "high",
      videoNum: 1122,
      topCountries: ["ID", "VN", "TH", "MM", "KH"],
    },
    {
      topic: "fourhandstwosonatas",
      category: "Vehicles & Transportation",
      subcategory: "Transport Equipment",
      growthMultiplier: 79,
      trust: "high",
      videoNum: 5339,
      topCountries: ["ID", "VN", "MY", "TH", "PH"],
    },
    {
      topic: "Best goals and assists breakdown",
      category: "Sports",
      subcategory: "Physical Sports",
      growthMultiplier: 66,
      trust: "high",
      videoNum: null,
      topCountries: ["VN", "ID", "MX", "TH", "PE"],
    },
    {
      topic: "training season capcut",
      category: "Sports",
      subcategory: "Fitness",
      growthMultiplier: 36,
      trust: "high",
      videoNum: 554,
      topCountries: ["ID", "VN", "MY", "PH", "TH"],
    },
    {
      topic: "smartbot review parte 2",
      category: "Science and Technology",
      subcategory: "Digital",
      growthMultiplier: 31,
      trust: "high",
      videoNum: 980,
      topCountries: ["ID", "VN", "TH", "PH"],
    },
    {
      topic: "steel and egg",
      category: "Gourmet",
      subcategory: "Food Ingredients/Fresh Food",
      growthMultiplier: 16,
      trust: "high",
      videoNum: 261,
      topCountries: ["ID", "PH", "TH", "VN"],
    },
    {
      topic: "tuide speak english",
      category: "Education",
      subcategory: "Language Learning",
      growthMultiplier: 14,
      trust: "high",
      videoNum: null,
      topCountries: ["ID", "PH", "VN", "MY", "TH"],
    },
    {
      topic: "playstyle in real life",
      category: "Sports",
      subcategory: "Physical Sports",
      growthMultiplier: 9,
      trust: "high",
      videoNum: 402,
      topCountries: ["ID", "VN", "MY", "TH", "MX"],
    },
    {
      topic: "color combo ideas for shoe accessories",
      category: "Fashion",
      subcategory: "Fashion Tutorials",
      growthMultiplier: 8,
      trust: "high",
      videoNum: 338,
      topCountries: ["ID", "VN", "MM", "TH", "MY"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this country's own search-demand series (not global demand). Mixes every category — for a single-category view across all countries, see the niche reports instead. Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "new lionel messi",
    audience: "unknown 18-24, Vietnam (dominant segment, snapshot at collection date)",
  },
};
