// Single source of truth for the Life Snapshots trends report (part of
// Featured Content).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='TikTok's Featured Content', cat_l2='Life Snapshots', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const featuredContentLifeSnapshotsSubReport: TikTokSubcategoryReport = {
  subcategory: "Life Snapshots",
  parentCategory: "Featured Content",
  parentSlug: "featured-content",
  region: "global",
  computedAt: "2026-10-08T04:24:18Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-08",
  topics: [
    {
      topic: "hawaii is underwater",
      growthMultiplier: 23,
      trust: "high",
      videoNum: 4057,
      topCountries: ["GB", "US", "PH", "CA"],
    },
    {
      topic: "TravelVlogs",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 13176,
      topCountries: ["MM", "ID", "NP", "BR", "BD"],
    },
    {
      topic: "RecapVideos",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 2815,
      topCountries: ["MM", "TH", "JP", "ET"],
    },
    {
      topic: "DailyRoutineVlog",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 2976,
      topCountries: ["PK", "ID", "ET", "BD"],
    },
    {
      topic: "day in my life vlog template",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 21974,
      topCountries: ["ZA", "PK", "ID", "PH", "NG"],
    },
    {
      topic: "family vlog ideas",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1222,
      topCountries: ["BD", "PK", "PH", "MM"],
    },
    {
      topic: "RecapVideo",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 7085,
      topCountries: ["MM", "TH", "JP", "MY"],
    },
    {
      topic: "disney cruise vlog",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 659,
      topCountries: ["ID", "MX", "CA", "PH", "AU"],
    },
    {
      topic: "aesthetic routine vlog",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1176,
      topCountries: ["BR", "ID", "TR", "PH", "MY"],
    },
    {
      topic: "realistic vacation prep vlog ideas",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 740,
      topCountries: ["PH", "ID", "MY", "US", "CH"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "hawaii is underwater",
    audience: "unknown 18-24, United Kingdom (dominant segment, snapshot at collection date)",
  },
};
