// Single source of truth for the ACGN (Anime, Comics, Games & Novels) trends report.
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, growth_reason='ok', trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokReport } from "./tiktok-report-types";

export const acgnReport: TikTokReport = {
  category: "ACGN (Anime, Comics, Games & Novels)",
  region: "global",
  computedAt: "2026-10-09T04:35:33Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-09",
  topics: [
    {
      topic: "melissa doi ending call",
      subcategory: "Games",
      growthMultiplier: 1019,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "GB", "DE", "IT", "NL"],
    },
    {
      topic: "dump trucks liv and maddie",
      subcategory: "Animation and Comics",
      growthMultiplier: 427,
      trust: "high",
      videoNum: 9870,
      topCountries: ["US", "ZA", "CA", "AU", "NG"],
    },
    {
      topic: "part two of the story fruit 2 mask",
      subcategory: "Games",
      growthMultiplier: 337,
      trust: "high",
      videoNum: 931,
      topCountries: ["US", "PH", "CA", "PK", "LB"],
    },
    {
      topic: "disney confirms new tiana casting",
      subcategory: "Animation and Comics",
      growthMultiplier: 278,
      trust: "high",
      videoNum: 2316,
      topCountries: ["US", "PH", "CA", "AU", "ZA"],
    },
    {
      topic: "my jojo stand",
      subcategory: "Animation and Comics",
      growthMultiplier: 250,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "BR", "RU", "FR", "UA"],
    },
    {
      topic: "scp 953 explained",
      subcategory: "Games",
      growthMultiplier: 80,
      trust: "high",
      videoNum: 995,
      topCountries: ["US", "DE", "PL", "MX", "PH"],
    },
    {
      topic: "doris girl",
      subcategory: "Animation and Comics",
      growthMultiplier: 80,
      trust: "high",
      videoNum: 28916,
      topCountries: ["US", "CA", "GB", "AU", "PH"],
    },
    {
      topic: "gg funkin eazy ai",
      subcategory: "Games",
      growthMultiplier: 60,
      trust: "high",
      videoNum: 920,
      topCountries: ["PH", "ID", "CA", "MY", "VN"],
    },
    {
      topic: "kise vs kuroko first match",
      subcategory: "Animation and Comics",
      growthMultiplier: 59,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "PH", "GB", "DE", "CA"],
    },
    {
      topic: "severian zzz gameplay",
      subcategory: "Games",
      growthMultiplier: 57,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "PH", "ID", "VN", "BR"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights. Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "melissa doi ending call",
    audience: "female 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
