// Single source of truth for the Featured Content trends report.
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, growth_reason='ok', trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokReport } from "./tiktok-report-types";

export const featuredContentReport: TikTokReport = {
  category: "Featured Content",
  region: "global",
  computedAt: "2026-10-08T04:24:18Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-08",
  topics: [
    {
      topic: "gracie pizza shop original video",
      subcategory: "Others TikTok and Video Contents",
      growthMultiplier: 752,
      trust: "high",
      videoNum: 844,
      topCountries: [],
    },
    {
      topic: "leah ashe copying megan",
      subcategory: "Others TikTok and Video Contents",
      growthMultiplier: 158,
      trust: "high",
      videoNum: 963,
      topCountries: ["US", "PH", "GB", "CA", "AU"],
    },
    {
      topic: "mr jackie purple egg truth revealed",
      subcategory: "Others TikTok and Video Contents",
      growthMultiplier: 147,
      trust: "high",
      videoNum: 642,
      topCountries: ["US", "PH", "CA", "AU", "ZA"],
    },
    {
      topic: "ContentCreatorInsightsIn2026",
      subcategory: "Others TikTok and Video Contents",
      growthMultiplier: 50,
      trust: "high",
      videoNum: 2127,
      topCountries: ["ET", "NG", "ZA", "BD"],
    },
    {
      topic: "morgz guess the price",
      subcategory: "Others TikTok and Video Contents",
      growthMultiplier: 41,
      trust: "high",
      videoNum: null,
      topCountries: ["GB", "IE", "AU", "NL", "SE"],
    },
    {
      topic: "duet videos on tiktok",
      subcategory: "Others TikTok and Video Contents",
      growthMultiplier: 28,
      trust: "high",
      videoNum: 2573,
      topCountries: ["ID", "NG", "KH", "MY", "MM"],
    },
    {
      topic: "hawaii is underwater",
      subcategory: "Life Snapshots",
      growthMultiplier: 23,
      trust: "high",
      videoNum: 4057,
      topCountries: ["GB", "US", "PH", "CA"],
    },
    {
      topic: "boy cracking a girl up",
      subcategory: "Trends/Challenges",
      growthMultiplier: 21,
      trust: "high",
      videoNum: 602,
      topCountries: ["US", "PH", "GB", "ZA"],
    },
    {
      topic: "31millionviewsviralvideo",
      subcategory: "Others TikTok and Video Contents",
      growthMultiplier: 20,
      trust: "high",
      videoNum: 9817,
      topCountries: ["MM", "ID", "UG", "BD"],
    },
    {
      topic: "creator insights part 3 4 next 3",
      subcategory: "Others TikTok and Video Contents",
      growthMultiplier: 15,
      trust: "high",
      videoNum: 108,
      topCountries: ["ZA", "NG", "PK", "GH"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights. Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "gracie pizza shop original video",
    audience: "not enough audience data for this topic",
  },
};
