// Single source of truth for the Digital trends report (part of
// Science and Technology).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Science and Technology', cat_l2='Digital', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const scienceTechnologyDigitalSubReport: TikTokSubcategoryReport = {
  subcategory: "Digital",
  parentCategory: "Science and Technology",
  parentSlug: "science-technology",
  region: "global",
  computedAt: "2026-10-09T04:35:33Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-10",
  topics: [
    {
      topic: "xiaomi 18 fold",
      growthMultiplier: 500,
      trust: "high",
      videoNum: 156,
      topCountries: ["VN", "ID", "MY", "PH", "TH"],
    },
    {
      topic: "speaker cleaner 90000000000hz",
      growthMultiplier: 64,
      trust: "high",
      videoNum: 1045,
      topCountries: ["ID", "PH", "BD", "MM"],
    },
    {
      topic: "16k 240fps camera",
      growthMultiplier: 53,
      trust: "high",
      videoNum: null,
      topCountries: ["ID", "VN", "TH", "MX", "BR"],
    },
    {
      topic: "ip 18 pro max",
      growthMultiplier: 24,
      trust: "high",
      videoNum: 7873,
      topCountries: ["ID", "MM", "IQ", "PH"],
    },
    {
      topic: "Biggest changes from page to screen",
      growthMultiplier: 17,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "MX", "BR", "ID", "PH"],
    },
    {
      topic: "smartbot review parte 2",
      growthMultiplier: 16,
      trust: "high",
      videoNum: 980,
      topCountries: ["ID", "VN", "TH", "PH"],
    },
    {
      topic: "تنظيف السماعات الهاتف 1000000000000",
      growthMultiplier: 14,
      trust: "high",
      videoNum: 704,
      topCountries: ["SD", "EG", "IQ", "TD"],
    },
    {
      topic: "speaker cleaner 30000000000hz redmi",
      growthMultiplier: 11,
      trust: "high",
      videoNum: 1190,
      topCountries: ["ID", "PH", "BD", "MM"],
    },
    {
      topic: "food clicker",
      growthMultiplier: 6,
      trust: "high",
      videoNum: 334,
      topCountries: ["MY", "BN", "PH", "SG"],
    },
    {
      topic: "new speaker cleaner sound 2026",
      growthMultiplier: 6,
      trust: "high",
      videoNum: null,
      topCountries: ["PK", "ET", "KE", "SN"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "xiaomi 18 fold",
    audience: "male 25-34, Vietnam (dominant segment, snapshot at collection date)",
  },
};
