// Single source of truth for the House Decoration trends report (part of
// Household).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Household', cat_l2='House Decoration', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const householdHouseDecorationSubReport: TikTokSubcategoryReport = {
  subcategory: "House Decoration",
  parentCategory: "Household",
  parentSlug: "household",
  region: "global",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "dolly parton house",
      growthMultiplier: 284,
      trust: "high",
      videoNum: 5444,
      topCountries: ["US", "GB", "ZA", "CA", "KE"],
    },
    {
      topic: "Nippon soft tissue",
      growthMultiplier: 54,
      trust: "high",
      videoNum: 543,
      topCountries: ["ID", "MY", "SG", "JP"],
    },
    {
      topic: "christmas curtains 2026 design",
      growthMultiplier: 13,
      trust: "high",
      videoNum: 442,
      topCountries: ["PH", "SA", "KW", "AE"],
    },
    {
      topic: "stock tank pool",
      growthMultiplier: 12,
      trust: "high",
      videoNum: null,
      topCountries: ["GB", "PH", "CA", "AU", "NL"],
    },
    {
      topic: "bunker tour",
      growthMultiplier: 7,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "CA", "AU", "ID", "GB"],
    },
    {
      topic: "pet beds that match your room",
      growthMultiplier: 7,
      trust: "high",
      videoNum: null,
      topCountries: ["NG", "ZA", "ID", "KE"],
    },
    {
      topic: "diy pool project from start to finish",
      growthMultiplier: 6,
      trust: "high",
      videoNum: null,
      topCountries: ["MX", "CO", "AR", "VE", "BR"],
    },
    {
      topic: "window",
      growthMultiplier: 6,
      trust: "high",
      videoNum: 1170,
      topCountries: ["TH", "ID", "PH", "BR", "MX"],
    },
    {
      topic: "Home trend",
      growthMultiplier: 4,
      trust: "high",
      videoNum: 1237,
      topCountries: ["PH", "ID", "CA", "AU", "MM"],
    },
    {
      topic: "Modern Design Ideas",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 1219,
      topCountries: ["KE", "UG", "GH", "NG", "TZ"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "dolly parton house",
    audience: "female 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
