// Single source of truth for the Internet trends report (part of
// Featured Content).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='TikTok's Featured Content', cat_l2='Internet', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const featuredContentInternetSubReport: TikTokSubcategoryReport = {
  subcategory: "Internet",
  parentCategory: "Featured Content",
  parentSlug: "featured-content",
  region: "global",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-07",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "learn faster with tako",
      growthMultiplier: 3,
      trust: "high",
      videoNum: null,
      topCountries: ["PK", "MM", "ID", "BD", "VN"],
    },
    {
      topic: "How to do I love I love with a passion",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 2109,
      topCountries: ["PK", "MM", "NP", "BD", "ID"],
    },
    {
      topic: "Rate with Tako",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["PK", "MM", "BD", "IR", "ID"],
    },
    {
      topic: "Stream with Tako",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["PK", "MM", "NP", "BD", "PH"],
    },
    {
      topic: "Edit with Tako",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["BR", "JP", "VN", "ID", "TH"],
    },
    {
      topic: "win the algorithm with tako",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["PK", "BD", "IR", "ID", "MM"],
    },
    {
      topic: "Scroll with Tako",
      growthMultiplier: 0,
      trust: "high",
      videoNum: null,
      topCountries: ["PK", "MM", "BD", "NP", "ID"],
    },
    {
      topic: "Compare with Tako",
      growthMultiplier: 0,
      trust: "high",
      videoNum: null,
      topCountries: ["PK", "MM", "BD", "IR", "LA"],
    },
    {
      topic: "i wanna see the sunshine after the rain tutorial",
      growthMultiplier: 0,
      trust: "high",
      videoNum: 9844,
      topCountries: ["PK", "BY", "MM", "VN", "RU"],
    },
    {
      topic: "home vs show hoodie",
      growthMultiplier: 0,
      trust: "high",
      videoNum: 7329,
      topCountries: ["US", "ID", "PK", "BD", "MM"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "learn faster with tako",
    audience: "not enough audience data for this topic",
  },
};
