// Single source of truth for the TikTok trends in Australia report.
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region='AU', growth_reason='ok', trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokCountryReport } from "./tiktok-country-report-types";

export const auCountryReport: TikTokCountryReport = {
  country: "Australia",
  countryCode: "AU",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "disney cruise child ring",
      category: "Fashion",
      subcategory: "Fashion Products",
      growthMultiplier: 45,
      trust: "high",
      videoNum: null,
      topCountries: ["GB", "CA", "PH", "AU", "ID"],
    },
    {
      topic: "burning man 2026",
      category: "Local Life",
      subcategory: "Offline Performance",
      growthMultiplier: 26,
      trust: "high",
      videoNum: 821,
      topCountries: ["US", "BR", "CA", "GB", "AU"],
    },
    {
      topic: "making mofongo luigi original",
      category: "Gourmet",
      subcategory: "Food Tutorials",
      growthMultiplier: 21,
      trust: "high",
      videoNum: 1175,
      topCountries: ["US", "CA", "PH", "AU", "ZA"],
    },
    {
      topic: "driving no steering wheel",
      category: "Vehicles & Transportation",
      subcategory: "Transport Equipment",
      growthMultiplier: 21,
      trust: "high",
      videoNum: 1009,
      topCountries: ["US", "CA", "AU", "GB", "NZ"],
    },
    {
      topic: "river otter",
      category: "Science Knowledge",
      subcategory: "Biology Knowledge",
      growthMultiplier: 9,
      trust: "high",
      videoNum: 1207,
      topCountries: ["US", "PH", "GB", "AU", "CA"],
    },
    {
      topic: "StudyHacks",
      category: "Education",
      subcategory: "Education - Others",
      growthMultiplier: 9,
      trust: "high",
      videoNum: 875,
      topCountries: ["AU", "CA", "ZA", "GB", "NZ"],
    },
    {
      topic: "mark ballas and maura higgins",
      category: "Entertainment",
      subcategory: "Celebrity Entertainment",
      growthMultiplier: 8,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "GB", "CA", "AU", "IE"],
    },
    {
      topic: "shuji finding out what derrick did to maya",
      category: "ACGN",
      subcategory: "Animation and Comics",
      growthMultiplier: 8,
      trust: "high",
      videoNum: 128,
      topCountries: ["PH", "US", "CA", "GB", "AU"],
    },
    {
      topic: "best fabric types for small brands",
      category: "Fashion",
      subcategory: "Fashion Products",
      growthMultiplier: 7,
      trust: "high",
      videoNum: null,
      topCountries: ["AU", "CA", "MX", "PH", "SA"],
    },
    {
      topic: "stevie star explained magic trick",
      category: "Personal Interests and Hobbies",
      subcategory: "Performance Interests Opera Art",
      growthMultiplier: 6,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "CA", "GB", "AU", "MY"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this country's own search-demand series (not global demand). Mixes every category — for a single-category view across all countries, see the niche reports instead. Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "disney cruise child ring",
    audience: "female 18-24, United Kingdom (dominant segment, snapshot at collection date)",
  },
};
