// Single source of truth for the Offline Performance trends report (part of
// Local Life).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Local Life', cat_l2='Offline Performance', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const localLifeOfflinePerformanceSubReport: TikTokSubcategoryReport = {
  subcategory: "Offline Performance",
  parentCategory: "Local Life",
  parentSlug: "local-life",
  region: "global",
  computedAt: "2026-10-09T04:35:33Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-10",
  topics: [
    {
      topic: "burnout car event schedules",
      growthMultiplier: 138,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "BR", "CA", "GB"],
    },
    {
      topic: "burning man 2026",
      growthMultiplier: 54,
      trust: "high",
      videoNum: 821,
      topCountries: ["US", "BR", "CA", "GB", "AU"],
    },
    {
      topic: "worlds collide tour 2026",
      growthMultiplier: 6,
      trust: "high",
      videoNum: 661,
      topCountries: ["US", "GB", "BR", "MX", "CA"],
    },
    {
      topic: "ثري دوتس جده",
      growthMultiplier: 6,
      trust: "high",
      videoNum: null,
      topCountries: ["SA", "AE", "KW", "EG"],
    },
    {
      topic: "laufey mexico",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 575,
      topCountries: ["MX", "PE", "PH", "BR"],
    },
    {
      topic: "albis rock in rio",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 348,
      topCountries: ["BR", "AO", "CA", "PY", "IL"],
    },
    {
      topic: "family drama filming locations",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 350,
      topCountries: ["KH", "IQ", "BD", "PK", "SA"],
    },
    {
      topic: "wemby contract",
      growthMultiplier: 2,
      trust: "high",
      videoNum: null,
      topCountries: ["ZA", "PH", "KE", "CA", "NG"],
    },
    {
      topic: "tihar festival in nepal",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 851,
      topCountries: ["NP", "MY", "JP", "AE"],
    },
    {
      topic: "bunny concert mandalay",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 614,
      topCountries: ["MM", "JP", "TH", "SG"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "burnout car event schedules",
    audience: "unknown 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
