// Single source of truth for the Society trends report.
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, growth_reason='ok', trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokReport } from "./tiktok-report-types";

export const societyReport: TikTokReport = {
  category: "Society",
  region: "global",
  computedAt: "2026-10-08T04:24:18Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-08",
  topics: [
    {
      topic: "policestop",
      subcategory: "Society News",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 681,
      topCountries: ["MX", "BR", "ID", "PE"],
    },
    {
      topic: "911Dispatcher",
      subcategory: "Society News",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 634,
      topCountries: ["CA", "GB", "AU", "PH", "ZA"],
    },
    {
      topic: "StreetVendor",
      subcategory: "Society News",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["ZA", "PH", "MX", "ID"],
    },
    {
      topic: "CrimeInvestigation",
      subcategory: "Society News",
      growthMultiplier: 0,
      trust: "high",
      videoNum: 1101,
      topCountries: ["PH", "BD", "PK", "NG"],
    },
    {
      topic: "build a community with tako",
      subcategory: "Society News",
      growthMultiplier: 0,
      trust: "high",
      videoNum: null,
      topCountries: ["KH", "LA", "MM", "PK", "BD"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights. Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "policestop",
    audience: "unknown 35+, Mexico (dominant segment, snapshot at collection date)",
  },
};
