// Single source of truth for the Local Life trends report.
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, growth_reason='ok', trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokReport } from "./tiktok-report-types";

export const localLifeReport: TikTokReport = {
  category: "Local Life",
  region: "global",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "toronto inconvenience store",
      subcategory: "Shopping",
      growthMultiplier: 407,
      trust: "high",
      videoNum: 886,
      topCountries: ["US", "GB", "FR", "DE", "CA"],
    },
    {
      topic: "lip and eddie shop",
      subcategory: "Shopping",
      growthMultiplier: 140,
      trust: "high",
      videoNum: 525,
      topCountries: ["US", "GB", "BD", "MM", "PK"],
    },
    {
      topic: "burning man 2026",
      subcategory: "Offline Performance",
      growthMultiplier: 54,
      trust: "high",
      videoNum: 821,
      topCountries: ["US", "BR", "CA", "GB", "AU"],
    },
    {
      topic: "obamas center opening",
      subcategory: "Leisure and Entertainment",
      growthMultiplier: 38,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "KE", "MX", "NG", "CA"],
    },
    {
      topic: "northwood space",
      subcategory: "Leisure and Entertainment",
      growthMultiplier: 27,
      trust: "high",
      videoNum: 609,
      topCountries: ["US", "GB", "CA", "AU", "DE"],
    },
    {
      topic: "1965 store",
      subcategory: "Shopping",
      growthMultiplier: 11,
      trust: "high",
      videoNum: 713,
      topCountries: ["PK", "NP", "AE", "SA"],
    },
    {
      topic: "target now",
      subcategory: "Shopping",
      growthMultiplier: 9,
      trust: "high",
      videoNum: 1007,
      topCountries: ["PH", "PK", "AE", "CA", "JP"],
    },
    {
      topic: "skinner park",
      subcategory: "Leisure and Entertainment",
      growthMultiplier: 8,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "GB", "TT", "NL"],
    },
    {
      topic: "هيفاء مول",
      subcategory: "Shopping",
      growthMultiplier: 8,
      trust: "high",
      videoNum: 289,
      topCountries: ["SA", "IQ", "LY", "TN", "TR"],
    },
    {
      topic: "james falls mall",
      subcategory: "Shopping",
      growthMultiplier: 6,
      trust: "high",
      videoNum: 1085,
      topCountries: ["US", "GB", "DE", "NL", "IT"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights. Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "toronto inconvenience store",
    audience: "female 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
