// Single source of truth for the Unresolved Mysteries trends report (part of
// Science Knowledge).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Science Knowledge', cat_l2='Unresolved Mysteries', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const scienceFactsUnresolvedMysteriesSubReport: TikTokSubcategoryReport = {
  subcategory: "Unresolved Mysteries",
  parentCategory: "Science Knowledge",
  parentSlug: "science-facts",
  region: "global",
  computedAt: "2026-10-08T04:24:18Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-08",
  topics: [
    {
      topic: "mimics caught on camera",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 385,
      topCountries: ["CA", "AU", "PH", "ZA", "LT"],
    },
    {
      topic: "Virus 2026",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1125,
      topCountries: ["PK", "MX", "ID", "CO", "NP"],
    },
    {
      topic: "strange creatures caught on camera",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 669,
      topCountries: ["PH", "ZA", "CA", "ID", "AU"],
    },
    {
      topic: "alien stage stats test",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "ID", "VN", "MY", "BR"],
    },
    {
      topic: "mystery jewelry found underwater",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["UG", "ZA", "KE", "MY"],
    },
    {
      topic: "alien stages",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1174,
      topCountries: ["ID", "BR", "PH", "VN", "TH"],
    },
    {
      topic: "chicken wire ghosts at night",
      growthMultiplier: 0,
      trust: "high",
      videoNum: 978,
      topCountries: ["US", "PH", "GB", "CA", "AU"],
    },
    {
      topic: "allatra rabbithole",
      growthMultiplier: 0,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "GB", "DE", "PL", "IE"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "mimics caught on camera",
    audience: "female 18-24, Canada (dominant segment, snapshot at collection date)",
  },
};
