// Single source of truth for the Physics Knowledge trends report (part of
// Science Knowledge).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Science Knowledge', cat_l2='Physics Knowledge', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const scienceFactsPhysicsKnowledgeSubReport: TikTokSubcategoryReport = {
  subcategory: "Physics Knowledge",
  parentCategory: "Science Knowledge",
  parentSlug: "science-facts",
  region: "global",
  computedAt: "2026-10-08T04:24:18Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-08",
  topics: [
    {
      topic: "there is something faster than light",
      growthMultiplier: 41,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "GB", "DE", "US", "ID"],
    },
    {
      topic: "atoms perfectly lining up footage",
      growthMultiplier: 6,
      trust: "high",
      videoNum: 1069,
      topCountries: ["PH", "ID", "MY", "CA", "AU"],
    },
    {
      topic: "still water vs normal water",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 877,
      topCountries: ["US", "ID", "PH", "MY", "CA"],
    },
    {
      topic: "faster than light",
      growthMultiplier: 2,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "ID", "BR", "DE", "GB"],
    },
    {
      topic: "nikola tesla aura farming",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "ID", "CA", "MY", "ZA"],
    },
    {
      topic: "how energy harvesting really works",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "GB", "ES", "BR"],
    },
    {
      topic: "explaining step-powered energy",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "GB", "ES", "BR"],
    },
    {
      topic: "how dredging ships move sand fast",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["DZ", "MX", "BR", "CO", "AR"],
    },
    {
      topic: "sand dredging",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 658,
      topCountries: ["ZA", "PH", "AU", "CA", "MY"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "there is something faster than light",
    audience: "unknown 18-24, Philippines (dominant segment, snapshot at collection date)",
  },
};
