// Single source of truth for the Films and TVs trends report (part of
// Entertainment).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Entertainment', cat_l2='Films and TVs', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const entertainmentFilmsAndTvsSubReport: TikTokSubcategoryReport = {
  subcategory: "Films and TVs",
  parentCategory: "Entertainment",
  parentSlug: "entertainment",
  region: "global",
  computedAt: "2026-10-08T04:24:18Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-08",
  topics: [
    {
      topic: "eddie vs toby's dad review",
      growthMultiplier: 46,
      trust: "high",
      videoNum: 771,
      topCountries: ["US", "PH", "GB", "ID", "CA"],
    },
    {
      topic: "domhnall gleeson harry potter",
      growthMultiplier: 23,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "GB", "IE", "AU", "CA"],
    },
    {
      topic: "موتٍ شاهين المدينه البعيده",
      growthMultiplier: 14,
      trust: "high",
      videoNum: 364,
      topCountries: ["SA", "IQ", "EG", "DZ"],
    },
    {
      topic: "georgie makes a lot of money",
      growthMultiplier: 9,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "PH", "CA", "ID", "MY"],
    },
    {
      topic: "there will be food",
      growthMultiplier: 5,
      trust: "high",
      videoNum: 678,
      topCountries: ["ZA", "PH", "NG", "KE", "CA"],
    },
    {
      topic: "loveindisguise",
      growthMultiplier: 4,
      trust: "high",
      videoNum: 622,
      topCountries: ["ID", "PH", "MY", "TH", "VN"],
    },
    {
      topic: "shortdramareview 2 3 4 5 6 7 8 9 10",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 128,
      topCountries: ["CA", "GH", "JM", "NG"],
    },
    {
      topic: "like and share film",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 168,
      topCountries: ["ID", "MY", "BN", "TL"],
    },
    {
      topic: "the dons greatest regret",
      growthMultiplier: 2,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "MY", "ID", "SG"],
    },
    {
      topic: "bts iheartradio festival 2026",
      growthMultiplier: 2,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "MX", "ID", "PH", "PE"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "eddie vs toby's dad review",
    audience: "male 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
