// Single source of truth for the Food Ingredients/Fresh Food trends report (part of
// Gourmet).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Gourmet', cat_l2='Food Ingredients/Fresh Food', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const gourmetFoodIngredientsFreshFoodSubReport: TikTokSubcategoryReport = {
  subcategory: "Food Ingredients/Fresh Food",
  parentCategory: "Gourmet",
  parentSlug: "gourmet",
  region: "global",
  computedAt: "2026-10-09T04:35:33Z",
  windowStart: "2026-08-09",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-10",
  topics: [
    {
      topic: "lacewing eggs",
      growthMultiplier: 157,
      trust: "high",
      videoNum: 763,
      topCountries: ["US", "CA", "AU", "PH", "MY"],
    },
    {
      topic: "indeks steel an egg",
      growthMultiplier: 27,
      trust: "high",
      videoNum: null,
      topCountries: ["ID", "PL", "MY", "PH"],
    },
    {
      topic: "susu dairy champ",
      growthMultiplier: 14,
      trust: "high",
      videoNum: null,
      topCountries: ["ID", "MY", "TL", "EG"],
    },
    {
      topic: "video of the egg original",
      growthMultiplier: 8,
      trust: "high",
      videoNum: 811,
      topCountries: ["US", "BR", "MX", "PH", "ID"],
    },
    {
      topic: "is eating bone good",
      growthMultiplier: 7,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "GB", "DE", "AU", "ID"],
    },
    {
      topic: "steel an egg",
      growthMultiplier: 6,
      trust: "high",
      videoNum: 1167,
      topCountries: ["PH", "ID", "VN", "TH", "US"],
    },
    {
      topic: "dunbar village grape",
      growthMultiplier: 4,
      trust: "high",
      videoNum: 350,
      topCountries: ["CA", "AU", "GB", "PH", "ZA"],
    },
    {
      topic: "Ateal an egg",
      growthMultiplier: 4,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "AU", "TH", "CA", "KH"],
    },
    {
      topic: "steel and egg",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 261,
      topCountries: ["ID", "PH", "TH", "VN"],
    },
    {
      topic: "miurin grape original video",
      growthMultiplier: 3,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "MY", "ID", "CA", "TR"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "lacewing eggs",
    audience: "female 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
