// Single source of truth for the Traditions and Culture trends report (part of
// Culture).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Culture', cat_l2='Traditions and Culture', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const cultureTraditionsAndCultureSubReport: TikTokSubcategoryReport = {
  subcategory: "Traditions and Culture",
  parentCategory: "Culture",
  parentSlug: "culture",
  region: "global",
  computedAt: "2026-10-08T04:24:18Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-08",
  topics: [
    {
      topic: "a banshee",
      growthMultiplier: 4,
      trust: "high",
      videoNum: 797,
      topCountries: ["US", "PH", "ID", "MY"],
    },
    {
      topic: "how to plan your festival day",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 128,
      topCountries: ["ID", "MY", "PH", "VN"],
    },
    {
      topic: "viking videos",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 922,
      topCountries: ["MX", "PE", "AR", "GT"],
    },
    {
      topic: "TamilWedding",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 645,
      topCountries: ["MY", "CA", "LK", "ZA"],
    },
    {
      topic: "happy birthday xori",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1102,
      topCountries: ["NP", "IN", "AE", "KW", "QA"],
    },
    {
      topic: "february 14",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1408,
      topCountries: ["NG", "PH", "MM", "NP"],
    },
    {
      topic: "happy birthday kinza",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 717,
      topCountries: ["PK", "AE", "SA", "QA"],
    },
    {
      topic: "a punk",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1191,
      topCountries: ["ID", "MX", "GB", "PH", "CA"],
    },
    {
      topic: "sunday status 2026",
      growthMultiplier: 0,
      trust: "high",
      videoNum: 31545,
      topCountries: ["NG", "ZA", "PK", "KE"],
    },
    {
      topic: "beautiful weddings",
      growthMultiplier: 0,
      trust: "high",
      videoNum: 2284,
      topCountries: ["MM", "ZA", "PK", "IQ"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "a banshee",
    audience: "female 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
