// Single source of truth for the Tourist Supplies trends report (part of
// Tourism).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Tourism', cat_l2='Tourist Supplies', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const tourismTouristSuppliesSubReport: TikTokSubcategoryReport = {
  subcategory: "Tourist Supplies",
  parentCategory: "Tourism",
  parentSlug: "tourism",
  region: "global",
  computedAt: "2026-10-08T04:24:18Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-08",
  topics: [
    {
      topic: "what to pack for a valley tour",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["PK", "PH", "AE", "SA"],
    },
    {
      topic: "backpacking packing list",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 618,
      topCountries: ["CA", "AU", "GB", "DE", "NZ"],
    },
    {
      topic: "how to pack luggage",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 741,
      topCountries: ["PH", "MY", "NP", "CA", "SG"],
    },
    {
      topic: "umroh packing and travel essentials",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 249,
      topCountries: ["ID", "MY", "TL", "BN"],
    },
    {
      topic: "travel needs",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1210,
      topCountries: ["PH", "MY", "SA", "AU", "ID"],
    },
    {
      topic: "what i pack for a beauty road trip",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 344,
      topCountries: ["US", "PH", "PA", "GB", "FR"],
    },
    {
      topic: "beach packing essentials i actually use",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["MM", "ID", "BD", "ET"],
    },
    {
      topic: "Packing for camp",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 651,
      topCountries: ["CA", "AU", "ZA", "NZ"],
    },
    {
      topic: "what i pack for hot weather travel",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["ID", "PH", "MY", "GB"],
    },
    {
      topic: "travel essentials for women",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 962,
      topCountries: ["CA", "MY", "PH", "AU", "ZA"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "what to pack for a valley tour",
    audience: "male 25-34, Pakistan (dominant segment, snapshot at collection date)",
  },
};
