// Single source of truth for the Offline Catering trends report (part of
// Gourmet).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Gourmet', cat_l2='Offline Catering', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const gourmetOfflineCateringSubReport: TikTokSubcategoryReport = {
  subcategory: "Offline Catering",
  parentCategory: "Gourmet",
  parentSlug: "gourmet",
  region: "global",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-09",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "lunch im my city",
      growthMultiplier: 237,
      trust: "high",
      videoNum: 475,
      topCountries: ["US", "SE", "CA", "AU", "ZA"],
    },
    {
      topic: "مطعم تيدي في الغزاليه",
      growthMultiplier: 16,
      trust: "high",
      videoNum: 503,
      topCountries: ["IQ", "TR", "EG", "AE"],
    },
    {
      topic: "brawadis starbucks",
      growthMultiplier: 14,
      trust: "high",
      videoNum: 2663,
      topCountries: ["US", "CA", "GB", "AU", "AE"],
    },
    {
      topic: "ksos cafe",
      growthMultiplier: 12,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "ID", "BR", "VN"],
    },
    {
      topic: "sugarfish nyc",
      growthMultiplier: 12,
      trust: "high",
      videoNum: 405,
      topCountries: ["US", "CA", "AU", "GB", "SG"],
    },
    {
      topic: "my taco bell order",
      growthMultiplier: 11,
      trust: "high",
      videoNum: 768,
      topCountries: ["US", "CA", "GB", "AU"],
    },
    {
      topic: "you pizza nica",
      growthMultiplier: 9,
      trust: "high",
      videoNum: 486,
      topCountries: ["US", "BR", "MX", "DO", "AU"],
    },
    {
      topic: "hernan meat house",
      growthMultiplier: 7,
      trust: "high",
      videoNum: 172,
      topCountries: ["HN", "US", "SV", "NI", "GT"],
    },
    {
      topic: "coffee festival 2026",
      growthMultiplier: 6,
      trust: "high",
      videoNum: null,
      topCountries: ["TH", "GR", "TR", "MY", "SG"],
    },
    {
      topic: "taco bell trend",
      growthMultiplier: 6,
      trust: "high",
      videoNum: 701,
      topCountries: ["ID", "BR", "PH", "MX", "MY"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "lunch im my city",
    audience: "female 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
