// Single source of truth for the Workplace trends report.
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, growth_reason='ok', trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokReport } from "./tiktok-report-types";

export const workplaceReport: TikTokReport = {
  category: "Workplace",
  region: "global",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "i am police officer",
      subcategory: "Special Work Types",
      growthMultiplier: 280,
      trust: "high",
      videoNum: 176,
      topCountries: ["PK", "GB", "AE", "SA"],
    },
    {
      topic: "you\\'re hired",
      subcategory: "Other-Workplace",
      growthMultiplier: 14,
      trust: "high",
      videoNum: 526,
      topCountries: ["PH", "MX", "BR", "TH", "ID"],
    },
    {
      topic: "UnderwaterWelding",
      subcategory: "Special Work Types",
      growthMultiplier: 12,
      trust: "high",
      videoNum: 370,
      topCountries: ["US", "ID", "GB", "CA", "DE"],
    },
    {
      topic: "live incentive program 2 part",
      subcategory: "Working Policies",
      growthMultiplier: 12,
      trust: "high",
      videoNum: null,
      topCountries: ["PK", "ID", "PH", "NP"],
    },
    {
      topic: "turning point 4",
      subcategory: "Workplace Skills",
      growthMultiplier: 7,
      trust: "high",
      videoNum: 869,
      topCountries: ["ID", "PH", "US", "GB", "BR"],
    },
    {
      topic: "Explaining earnings in agent models",
      subcategory: "Special Work Types",
      growthMultiplier: 6,
      trust: "high",
      videoNum: null,
      topCountries: ["MX", "NG", "PK", "ID", "BR"],
    },
    {
      topic: "Delivery guy",
      subcategory: "Special Work Types",
      growthMultiplier: 5,
      trust: "high",
      videoNum: 1068,
      topCountries: ["ZA", "NG", "IQ", "MX", "ID"],
    },
    {
      topic: "networking tutorial",
      subcategory: "Workplace Skills",
      growthMultiplier: 5,
      trust: "high",
      videoNum: 557,
      topCountries: ["PH", "ZA", "MY", "ID", "KE"],
    },
    {
      topic: "funny ways to sell useful tools",
      subcategory: "Workplace Skills",
      growthMultiplier: 4,
      trust: "high",
      videoNum: 301,
      topCountries: ["GT", "PE", "MX", "VE", "CO"],
    },
    {
      topic: "apartment property management",
      subcategory: "Special Work Types",
      growthMultiplier: 4,
      trust: "high",
      videoNum: 1090,
      topCountries: ["PH", "CA", "GB", "AU", "MY"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights. Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "i am police officer",
    audience: "unknown 25-34, Pakistan (dominant segment, snapshot at collection date)",
  },
};
