// Single source of truth for the Web Recources Download trends report (part of
// Science and Technology).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Science and Technology', cat_l2='Web Recources Download', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const scienceTechnologyWebRecourcesDownloadSubReport: TikTokSubcategoryReport = {
  subcategory: "Web Recources Download",
  parentCategory: "Science and Technology",
  parentSlug: "science-technology",
  region: "global",
  computedAt: "2026-10-09T04:35:33Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-10",
  topics: [
    {
      topic: "james live photo",
      growthMultiplier: 4,
      trust: "high",
      videoNum: null,
      topCountries: ["VN", "ID", "MY", "PH", "MM"],
    },
    {
      topic: "waterphone sound",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 1966,
      topCountries: ["US", "ID", "DE", "MM", "MY"],
    },
    {
      topic: "ronaldo best wallpapers 4k",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 136,
      topCountries: ["ET", "NG", "PK", "ZA"],
    },
    {
      topic: "waterfall screen phone",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 11859,
      topCountries: ["PH", "US", "ID", "MM"],
    },
    {
      topic: "dembele live photo tutorial",
      growthMultiplier: 2,
      trust: "high",
      videoNum: 599,
      topCountries: ["BD", "ID", "MM", "GB", "NP"],
    },
    {
      topic: "hearts2hearts logo",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 776,
      topCountries: ["ID", "PH", "MY", "VN"],
    },
    {
      topic: "drake album cover wallpaper",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1098,
      topCountries: ["ZA", "PH", "NG", "ZW"],
    },
    {
      topic: "video 4k",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 960,
      topCountries: ["VN", "ID", "DZ", "MX"],
    },
    {
      topic: "sad wallpaper for girls",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["PK", "PH", "NG", "ID", "ZA"],
    },
    {
      topic: "ultra hd 8k",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 998,
      topCountries: ["PK", "ID", "MY", "MX", "SA"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "james live photo",
    audience: "unknown 18-24, Philippines (dominant segment, snapshot at collection date)",
  },
};
