// Single source of truth for the TikTok trends in Nigeria report.
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region='NG', growth_reason='ok', trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokCountryReport } from "./tiktok-country-report-types";

export const ngCountryReport: TikTokCountryReport = {
  country: "Nigeria",
  countryCode: "NG",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "messi first goal for argentina",
      category: "Sports",
      subcategory: "Physical Sports",
      growthMultiplier: 37,
      trust: "high",
      videoNum: 879,
      topCountries: ["NG", "ZA", "GH", "ID"],
    },
    {
      topic: "messi vs england reaccion pt 2 fut crunch",
      category: "Sports",
      subcategory: "Physical Sports",
      growthMultiplier: 24,
      trust: "high",
      videoNum: null,
      topCountries: ["ID", "NG", "AR", "ZA", "BD"],
    },
    {
      topic: "hotel maid",
      category: "Tourism",
      subcategory: "Tourism Service",
      growthMultiplier: 23,
      trust: "high",
      videoNum: 608,
      topCountries: ["NG", "GH", "KE", "ZA", "TZ"],
    },
    {
      topic: "capcut new trending videos 2026",
      category: "Science and Technology",
      subcategory: "Software",
      growthMultiplier: 22,
      trust: "high",
      videoNum: 809,
      topCountries: ["NG", "GH", "UG", "KE", "SL"],
    },
    {
      topic: "WeddingVideography",
      category: "Personal Interests and Hobbies",
      subcategory: "Visual related Interests",
      growthMultiplier: 21,
      trust: "high",
      videoNum: 1074,
      topCountries: ["NG", "MW", "ZA", "GH"],
    },
    {
      topic: "matta lee new car gle 53",
      category: "Vehicles & Transportation",
      subcategory: "Transport Equipment",
      growthMultiplier: 20,
      trust: "high",
      videoNum: null,
      topCountries: ["NG", "GB", "DE", "BJ"],
    },
    {
      topic: "pet beds that match your room",
      category: "Household",
      subcategory: "House Decoration",
      growthMultiplier: 15,
      trust: "high",
      videoNum: null,
      topCountries: ["NG", "ZA", "ID", "KE"],
    },
    {
      topic: "7 billion view mountain",
      category: "Tourism",
      subcategory: "Tourism Sites",
      growthMultiplier: 9,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "NG", "MM", "NP", "ZA"],
    },
    {
      topic: "#MyAccountGrowth",
      category: "Science and Technology",
      subcategory: "Internet",
      growthMultiplier: 9,
      trust: "high",
      videoNum: null,
      topCountries: ["PK", "NG", "NP", "PH", "ET"],
    },
    {
      topic: "Ronaldo 1000 goals",
      category: "Sports",
      subcategory: "Physical Sports",
      growthMultiplier: 9,
      trust: "high",
      videoNum: 1183,
      topCountries: ["NG", "GB", "KE", "GH"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this country's own search-demand series (not global demand). Mixes every category — for a single-category view across all countries, see the niche reports instead. Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "messi first goal for argentina",
    audience: "unknown 18-24, Nigeria (dominant segment, snapshot at collection date)",
  },
};
