// Single source of truth for the Dance Trend trends report (part of
// Dance).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Dance', cat_l2='Dance Trend', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const danceDanceTrendSubReport: TikTokSubcategoryReport = {
  subcategory: "Dance Trend",
  parentCategory: "Dance",
  parentSlug: "dance",
  region: "global",
  computedAt: "2026-10-08T04:24:18Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-08",
  topics: [
    {
      topic: "Boom Boom Boom Dance Trend",
      growthMultiplier: 8036,
      trust: "high",
      videoNum: 1024,
      topCountries: ["PH", "ID", "ZA", "BR"],
    },
    {
      topic: "addison rae renegade",
      growthMultiplier: 140,
      trust: "high",
      videoNum: 1235,
      topCountries: ["US", "FR", "ES", "IT", "GB"],
    },
    {
      topic: "tiktok dance ideas 2026",
      growthMultiplier: 126,
      trust: "high",
      videoNum: 1105,
      topCountries: ["US", "PK", "NG", "KE"],
    },
    {
      topic: "Obsession Dance Goes Viral",
      growthMultiplier: 114,
      trust: "high",
      videoNum: 1127,
      topCountries: ["BD", "US", "PK", "PH"],
    },
    {
      topic: "new trending dance august 2026",
      growthMultiplier: 57,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "ID", "NP", "MM"],
    },
    {
      topic: "new dance trend august 2026",
      growthMultiplier: 35,
      trust: "high",
      videoNum: 1056,
      topCountries: ["PH", "ZA", "NP", "ID"],
    },
    {
      topic: "TikTok Brazilian Dance",
      growthMultiplier: 23,
      trust: "high",
      videoNum: 6814,
      topCountries: ["PH", "ID", "MM", "MX"],
    },
    {
      topic: "do a money spread jynxzi",
      growthMultiplier: 21,
      trust: "high",
      videoNum: null,
      topCountries: ["GB", "CA", "AU", "ZA", "NZ"],
    },
    {
      topic: "viral dance and audio trends",
      growthMultiplier: 11,
      trust: "high",
      videoNum: 638,
      topCountries: ["KW", "SA", "EG", "IQ"],
    },
    {
      topic: "tiktok dances compilation",
      growthMultiplier: 9,
      trust: "high",
      videoNum: 1179,
      topCountries: ["PH", "MX", "AE", "MM"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "Boom Boom Boom Dance Trend",
    audience: "unknown 25-34, Others (dominant segment, snapshot at collection date)",
  },
};
