// Single source of truth for the TikTok trends in Mexico report.
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region='MX', growth_reason='ok', trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokCountryReport } from "./tiktok-country-report-types";

export const mxCountryReport: TikTokCountryReport = {
  country: "Mexico",
  countryCode: "MX",
  computedAt: "2026-10-08T04:24:18Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-08",
  topics: [
    {
      topic: "wileecoyote x roadrunner",
      category: "Vehicles & Transportation",
      subcategory: "Transport Equipment",
      growthMultiplier: 1190,
      trust: "high",
      videoNum: 870,
      topCountries: ["US", "MX", "PH", "BR", "PE"],
    },
    {
      topic: "Quick marinara pizza at home",
      category: "Gourmet",
      subcategory: "Food Tutorials",
      growthMultiplier: 52,
      trust: "high",
      videoNum: null,
      topCountries: ["ID", "PK", "MX", "EG", "BD"],
    },
    {
      topic: "a BMW",
      category: "Vehicles & Transportation",
      subcategory: "Transport Equipment",
      growthMultiplier: 48,
      trust: "high",
      videoNum: 22352,
      topCountries: ["PH", "CA", "MX", "AU", "ID"],
    },
    {
      topic: "eddie vs toby's dad review",
      category: "Entertainment",
      subcategory: "Films and TVs",
      growthMultiplier: 45,
      trust: "high",
      videoNum: 771,
      topCountries: ["US", "PH", "GB", "ID", "CA"],
    },
    {
      topic: "tate mcrae neutrogena makeup",
      category: "Fashion",
      subcategory: "Fashion Products",
      growthMultiplier: 34,
      trust: "high",
      videoNum: 944,
      topCountries: ["US", "MX", "AR", "CA", "FR"],
    },
    {
      topic: "Tractomula",
      category: "Vehicles & Transportation",
      subcategory: "Transport Equipment",
      growthMultiplier: 25,
      trust: "high",
      videoNum: 647,
      topCountries: ["MX", "AR", "EC", "CO", "CL"],
    },
    {
      topic: "nestle agua",
      category: "Gourmet",
      subcategory: "Food FMCG",
      growthMultiplier: 21,
      trust: "high",
      videoNum: 515,
      topCountries: ["US", "MX", "PE", "EC", "ES"],
    },
    {
      topic: "buddy edit",
      category: "Science and Technology",
      subcategory: "Internet",
      growthMultiplier: 20,
      trust: "high",
      videoNum: 938,
      topCountries: ["BR", "MX", "PH", "AR"],
    },
    {
      topic: "is it a verity verity verity",
      category: "Culture",
      subcategory: "Serious Literature",
      growthMultiplier: 19,
      trust: "high",
      videoNum: 579,
      topCountries: ["PH", "MX", "CA", "BR", "ID"],
    },
    {
      topic: "Stag Reel",
      category: "Personal Interests and Hobbies",
      subcategory: "Gardening and Pet",
      growthMultiplier: 14,
      trust: "high",
      videoNum: null,
      topCountries: ["MX", "PE", "BO", "AR", "CO"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this country's own search-demand series (not global demand). Mixes every category — for a single-category view across all countries, see the niche reports instead. Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "wileecoyote x roadrunner",
    audience: "female 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
