// Single source of truth for the Food Science trends report (part of
// Gourmet).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Gourmet', cat_l2='Food Science', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const gourmetFoodScienceSubReport: TikTokSubcategoryReport = {
  subcategory: "Food Science",
  parentCategory: "Gourmet",
  parentSlug: "gourmet",
  region: "global",
  computedAt: "2026-10-09T04:35:33Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-10",
  topics: [
    {
      topic: "pumpkin seeds ready to eat",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 877,
      topCountries: ["PH", "MY", "SA", "PK"],
    },
    {
      topic: "how much is 250g flour",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["ZA", "PH", "AU", "NZ"],
    },
    {
      topic: "turmeric drink benefits",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 736,
      topCountries: ["ZA", "KE", "PH", "NG"],
    },
    {
      topic: "beef tallow benefits",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 767,
      topCountries: ["GB", "PH", "AU", "ZA", "KE"],
    },
    {
      topic: "mistakes to avoid in sauce reduction",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["FR", "US", "ID", "GB"],
    },
    {
      topic: "refined carbs vs smarter meal choices",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 764,
      topCountries: ["MM", "ID", "BD", "ET"],
    },
    {
      topic: "foods that support skin and eye health",
      growthMultiplier: 1,
      trust: "high",
      videoNum: null,
      topCountries: ["MM", "ID", "BD", "ET"],
    },
    {
      topic: "foods that form harmful compounds",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1191,
      topCountries: ["MM", "ID", "BD", "ET"],
    },
    {
      topic: "what does nestle not own",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 120,
      topCountries: ["PH", "CA", "ID", "AU", "AE"],
    },
    {
      topic: "Organic food",
      growthMultiplier: 1,
      trust: "high",
      videoNum: 1267,
      topCountries: ["PH", "GB", "AU", "ZA"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "pumpkin seeds ready to eat",
    audience: "unknown 35+, Philippines (dominant segment, snapshot at collection date)",
  },
};
