// Single source of truth for the Education trends report.
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, growth_reason='ok', trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokReport } from "./tiktok-report-types";

export const educationReport: TikTokReport = {
  category: "Education",
  region: "global",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "3 in german",
      subcategory: "Language Learning",
      growthMultiplier: 5207,
      trust: "high",
      videoNum: 581,
      topCountries: ["US", "GB", "PH", "CA", "AU"],
    },
    {
      topic: "happy birthday in thai language",
      subcategory: "Language Learning",
      growthMultiplier: 22,
      trust: "high",
      videoNum: 100,
      topCountries: ["PH", "CA", "AE", "JP"],
    },
    {
      topic: "michelle calculator math",
      subcategory: "School Education",
      growthMultiplier: 18,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "MX", "BR", "US", "GB"],
    },
    {
      topic: "π edit math",
      subcategory: "School Education",
      growthMultiplier: 16,
      trust: "high",
      videoNum: 421,
      topCountries: ["PH", "ID", "CO", "BR"],
    },
    {
      topic: "semester at sea explained",
      subcategory: "School Education",
      growthMultiplier: 13,
      trust: "high",
      videoNum: null,
      topCountries: ["GB", "PH", "PT", "AU", "CA"],
    },
    {
      topic: "sincere metaphors compilation",
      subcategory: "Education - Others",
      growthMultiplier: 8,
      trust: "high",
      videoNum: 390,
      topCountries: ["US", "CA", "AU", "ZA", "NZ"],
    },
    {
      topic: "vlog schools",
      subcategory: "Campus Life",
      growthMultiplier: 8,
      trust: "high",
      videoNum: 684,
      topCountries: ["FR", "ID", "RE", "ET", "PH"],
    },
    {
      topic: "الزي المدرسي العراقي الجديد 2027",
      subcategory: "Education Supplies",
      growthMultiplier: 7,
      trust: "high",
      videoNum: 785,
      topCountries: ["IQ", "EG", "TR", "AE"],
    },
    {
      topic: "BackToSchoolCheck",
      subcategory: "Campus Life",
      growthMultiplier: 7,
      trust: "high",
      videoNum: 749,
      topCountries: ["RU", "BY", "NG", "KZ"],
    },
    {
      topic: "kristina poudel ko handwriting",
      subcategory: "Language Learning",
      growthMultiplier: 7,
      trust: "high",
      videoNum: null,
      topCountries: ["NP", "PK", "BD", "IN"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights. Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "3 in german",
    audience: "female 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
