// Single source of truth for the Trends/Challenges trends report (part of
// Featured Content).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='TikTok's Featured Content', cat_l2='Trends/Challenges', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const featuredContentTrendsChallengesSubReport: TikTokSubcategoryReport = {
  subcategory: "Trends/Challenges",
  parentCategory: "Featured Content",
  parentSlug: "featured-content",
  region: "global",
  computedAt: "2026-10-07T04:23:34Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-07",
  topics: [
    {
      topic: "boy cracking a girl up",
      growthMultiplier: 21,
      trust: "high",
      videoNum: 602,
      topCountries: ["US", "PH", "GB", "ZA"],
    },
    {
      topic: "popular tiktok memes",
      growthMultiplier: 9,
      trust: "high",
      videoNum: null,
      topCountries: ["VN", "BR", "MM", "NG", "ID"],
    },
    {
      topic: "viral tiktok love videos",
      growthMultiplier: 7,
      trust: "high",
      videoNum: 17029,
      topCountries: ["PK", "BD", "ID", "PH", "MM"],
    },
    {
      topic: "venom trend couple",
      growthMultiplier: 5,
      trust: "high",
      videoNum: 1137,
      topCountries: ["US", "GB", "FR", "IT", "DE"],
    },
    {
      topic: "guess who slapped challenge",
      growthMultiplier: 5,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "ZA", "GB", "CA", "PH"],
    },
    {
      topic: "take my hand come with me trend",
      growthMultiplier: 5,
      trust: "high",
      videoNum: null,
      topCountries: ["ID", "MY", "PH", "ZA", "KH"],
    },
    {
      topic: "drake album cover girl",
      growthMultiplier: 4,
      trust: "high",
      videoNum: 194934,
      topCountries: ["CA", "GB", "FR", "DE", "AU"],
    },
    {
      topic: "what's 9 plus 10 21 original",
      growthMultiplier: 4,
      trust: "high",
      videoNum: 377,
      topCountries: ["BR", "PH", "ID", "MX", "CA"],
    },
    {
      topic: "hey lisbon found it",
      growthMultiplier: 3,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "MY", "ID", "AU", "CA"],
    },
    {
      topic: "viral video ideas 2026",
      growthMultiplier: 3,
      trust: "high",
      videoNum: 8911,
      topCountries: ["PK", "ID", "ET", "BD"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "boy cracking a girl up",
    audience: "unknown 18-24, United States of America (dominant segment, snapshot at collection date)",
  },
};
