// Single source of truth for the Tourism Sites trends report (part of
// Tourism).
// Generated by scripts/generate-reports.py from ClickHouse `csi.v_topic_metrics`
// (region=global, cat_l1='Tourism', cat_l2='Tourism Sites', growth_reason='ok',
// trust='high', quantized=0, coarse=0, shared_n=0).
// Do not hand-edit the numbers here — rerun the generator instead. The same object feeds
// the human-readable page, its llms-full.txt and the JSON-LD blocks, so a change here changes
// all three at once (no drift between "visible" and "AI-facing" content).

import type { TikTokSubcategoryReport } from "./tiktok-subcategory-report-types";

export const tourismTourismSitesSubReport: TikTokSubcategoryReport = {
  subcategory: "Tourism Sites",
  parentCategory: "Tourism",
  parentSlug: "tourism",
  region: "global",
  computedAt: "2026-10-09T04:35:33Z",
  windowStart: "2026-08-10",
  windowEnd: "2026-09-20",
  updatedAt: "2026-10-09",
  topics: [
    {
      topic: "gollum cave real photo",
      growthMultiplier: 263,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "US", "DE", "GB", "FR"],
    },
    {
      topic: "tooro kingdom palace",
      growthMultiplier: 182,
      trust: "high",
      videoNum: 656,
      topCountries: ["UG", "NG", "KE", "SA"],
    },
    {
      topic: "the disney cruise ship",
      growthMultiplier: 35,
      trust: "high",
      videoNum: 741,
      topCountries: ["US", "GB", "DE", "ES", "CA"],
    },
    {
      topic: "khadlaj island sun",
      growthMultiplier: 13,
      trust: "high",
      videoNum: null,
      topCountries: ["MY", "GB", "ID", "PH", "CA"],
    },
    {
      topic: "epstrin island",
      growthMultiplier: 8,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "ID", "MY", "CA"],
    },
    {
      topic: "widow bay",
      growthMultiplier: 7,
      trust: "high",
      videoNum: 632,
      topCountries: ["US", "SA", "GB", "FR", "ID"],
    },
    {
      topic: "tallest statues in the usa",
      growthMultiplier: 6,
      trust: "high",
      videoNum: 184,
      topCountries: ["US", "PH", "ZA", "AU"],
    },
    {
      topic: "split rock horeb",
      growthMultiplier: 5,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "ID", "BR", "MX", "TH"],
    },
    {
      topic: "aquarium arm mc matteo",
      growthMultiplier: 5,
      trust: "high",
      videoNum: null,
      topCountries: ["PH", "AU", "TR", "MY"],
    },
    {
      topic: "dean potter falls",
      growthMultiplier: 4,
      trust: "high",
      videoNum: null,
      topCountries: ["US", "PH", "MY", "ID", "CA"],
    },
  ],
  methodologyNote:
    "TikTok Creative Center data, collected by Vira's own account via Creative Search Insights, filtered to this one subcategory within its parent niche (TikTok's own two-level category taxonomy). Growth = 7/14/21-day median vs. prior period, shown only when trust is medium or high. Video count as reported by TikTok; \"not reported\" (video_num=0) means TikTok did not report a count for that topic, not zero competition. Updated daily.",
  highlightTopic: {
    topic: "gollum cave real photo",
    audience: "female 18-24, Philippines (dominant segment, snapshot at collection date)",
  },
};
