// Single source of truth for the YouTube Action game channel growth report
// (part of Video game culture).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Action game" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeActionGameSubReport: YoutubeSubgenreReport = {
  subgenre: "Action game",
  parentCategory: "Video game culture",
  parentSlug: "gaming",
  region: "global",
  dataAsOf: "2026-10-09",
  updatedAt: "2026-10-09",
  channels: [
    {
      channelName: "Mʀ Pᴜʀᴘʟᴇ Oɴᴇ",
      channelUrl: "https://www.youtube.com/channel/UCM7RF0sKSApJ_V6YbdeWGlw",
      topic: "Action game, Video game culture",
      subscribers: 374000,
      subsGained30d: 277300,
      growthPct: 286.8,
      viewsGained30d: 6497281,
      channelCreatedAt: "2022-09-16",
    },
    {
      channelName: "Eurofihl",
      channelUrl: "https://www.youtube.com/channel/UCC30G2aahpAdA_0Mtj3gf8w",
      topic: "Action game, Video game culture",
      subscribers: 92200,
      subsGained30d: 65900,
      growthPct: 250.6,
      viewsGained30d: 2069518,
      channelCreatedAt: "2023-02-08",
    },
    {
      channelName: "JYMZ",
      channelUrl: "https://www.youtube.com/channel/UCzUEytJj-zpQFEWnlWqVGGg",
      topic: "Video game culture, Action game",
      subscribers: 246000,
      subsGained30d: 146800,
      growthPct: 148.0,
      viewsGained30d: 1943779,
      channelCreatedAt: "2025-04-14",
    },
    {
      channelName: "Ex Winx ff",
      channelUrl: "https://www.youtube.com/channel/UCQv27MELiF4A7Xlzgb-5cew",
      topic: "Video game culture, Action game",
      subscribers: 56700,
      subsGained30d: 32400,
      growthPct: 133.3,
      viewsGained30d: 12263464,
      channelCreatedAt: "2025-07-24",
    },
    {
      channelName: "SCARY GAMER",
      channelUrl: "https://www.youtube.com/channel/UCMKx29aJgj82IRdCIisC1gw",
      topic: "Action game, Video game culture",
      subscribers: 92700,
      subsGained30d: 52400,
      growthPct: 130.0,
      viewsGained30d: 4397066,
      channelCreatedAt: "2025-02-28",
    },
    {
      channelName: "His Bloxy",
      channelUrl: "https://www.youtube.com/channel/UCPVt8nbUmxQvbb1k_AiWLLQ",
      topic: "Video game culture, Action game",
      subscribers: 109000,
      subsGained30d: 60400,
      growthPct: 124.3,
      viewsGained30d: 4198446,
      channelCreatedAt: "2025-09-01",
    },
    {
      channelName: "ardytemanfora",
      channelUrl: "https://www.youtube.com/channel/UCAsBY7YRmlUNDO0Hac6hbJw",
      topic: "Video game culture, Action game",
      subscribers: 66800,
      subsGained30d: 35300,
      growthPct: 112.1,
      viewsGained30d: 7695368,
      channelCreatedAt: "2025-06-30",
    },
    {
      channelName: "Black Bunny",
      channelUrl: "https://www.youtube.com/channel/UCzraguiKnOSb9oH5n_JYq0g",
      topic: "Action game, Video game culture",
      subscribers: 67200,
      subsGained30d: 34800,
      growthPct: 107.4,
      viewsGained30d: 18633317,
      channelCreatedAt: "2022-02-04",
    },
    {
      channelName: "Yt-Aayanshgaming",
      channelUrl: "https://www.youtube.com/channel/UCA0hO9nB1B1_T3nHBb6RwOA",
      topic: "Video game culture, Action game",
      subscribers: 208000,
      subsGained30d: 107000,
      growthPct: 105.9,
      viewsGained30d: 2931507,
      channelCreatedAt: "2024-04-04",
    },
    {
      channelName: "Medal",
      channelUrl: "https://www.youtube.com/channel/UCs1xWFLN__Txt6QqFkxRpRA",
      topic: "Action game, Video game culture",
      subscribers: 153000,
      subsGained30d: 73400,
      growthPct: 92.2,
      viewsGained30d: 43945827,
      channelCreatedAt: "2017-06-21",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Video game culture niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Mʀ Pᴜʀᴘʟᴇ Oɴᴇ",
    note: "an established channel (created 2022) that gained 277,300 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
