// Single source of truth for the YouTube Hip hop music channel growth report
// (part of Music).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Hip hop music" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeHipHopMusicSubReport: YoutubeSubgenreReport = {
  subgenre: "Hip hop music",
  parentCategory: "Music",
  parentSlug: "music",
  region: "global",
  dataAsOf: "2026-10-10",
  updatedAt: "2026-10-10",
  channels: [
    {
      channelName: "Kvng Tayo",
      channelUrl: "https://www.youtube.com/channel/UC0Xb6D4OdwG5stjwkKGSC2g",
      topic: "Entertainment, Hip hop music",
      subscribers: 280000,
      subsGained30d: 71000,
      growthPct: 34.0,
      viewsGained30d: 36436596,
      channelCreatedAt: "2015-06-26",
    },
    {
      channelName: "Apex Entertainment",
      channelUrl: "https://www.youtube.com/channel/UC80ZKD0VQ0JG-8wvS4PaDDg",
      topic: "Music, Hip hop music",
      subscribers: 53500,
      subsGained30d: 13400,
      growthPct: 33.4,
      viewsGained30d: 2276118,
      channelCreatedAt: "2024-11-08",
    },
    {
      channelName: "comehelpglo",
      channelUrl: "https://www.youtube.com/channel/UCHGhHAyC4z9kU5v_P7s9w0Q",
      topic: "Music, Hip hop music",
      subscribers: 55000,
      subsGained30d: 10500,
      growthPct: 23.6,
      viewsGained30d: 1525172,
      channelCreatedAt: "2025-08-05",
    },
    {
      channelName: "Rell Vert",
      channelUrl: "https://www.youtube.com/channel/UC1X3D3zQCH_YL8vVf3JRjPw",
      topic: "Music, Hip hop music",
      subscribers: 76700,
      subsGained30d: 13400,
      growthPct: 21.2,
      viewsGained30d: 4790669,
      channelCreatedAt: "2024-06-30",
    },
    {
      channelName: "Durkiologist",
      channelUrl: "https://www.youtube.com/channel/UCIIaT3_76WcamyIiEnoPCjg",
      topic: "Music, Hip hop music",
      subscribers: 111000,
      subsGained30d: 18900,
      growthPct: 20.5,
      viewsGained30d: 8280911,
      channelCreatedAt: "2023-02-24",
    },
    {
      channelName: "MIRV48",
      channelUrl: "https://www.youtube.com/channel/UCNLrkJhiaNR24ikmOmntxCw",
      topic: "Music, Hip hop music",
      subscribers: 99600,
      subsGained30d: 16800,
      growthPct: 20.3,
      viewsGained30d: 15692053,
      channelCreatedAt: "2018-03-10",
    },
    {
      channelName: "Yo Mariyos",
      channelUrl: "https://www.youtube.com/channel/UC2thIVXbRJS0r50wVRLQZ4A",
      topic: "Music, Hip hop music",
      subscribers: 129000,
      subsGained30d: 21000,
      growthPct: 19.4,
      viewsGained30d: 438171,
      channelCreatedAt: "2025-09-17",
    },
    {
      channelName: "Bloodhound Q50",
      channelUrl: "https://www.youtube.com/channel/UCQYSAAPWo_0Au63xCJ5PJVQ",
      topic: "Music, Hip hop music",
      subscribers: 365000,
      subsGained30d: 59000,
      growthPct: 19.3,
      viewsGained30d: 29558143,
      channelCreatedAt: "2024-06-19",
    },
    {
      channelName: "wantché",
      channelUrl: "https://www.youtube.com/channel/UCmJEWYQIy3zRwhoLQjhppXg",
      topic: "Music, Hip hop music",
      subscribers: 77400,
      subsGained30d: 11700,
      growthPct: 17.8,
      viewsGained30d: 1957706,
      channelCreatedAt: "2023-10-05",
    },
    {
      channelName: "Transco Leopard",
      channelUrl: "https://www.youtube.com/channel/UCJPoiYkSFTv67F6SL7rdLMQ",
      topic: "Hip hop music, Music",
      subscribers: 127000,
      subsGained30d: 18000,
      growthPct: 16.5,
      viewsGained30d: 3995380,
      channelCreatedAt: "2026-03-06",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Music niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Kvng Tayo",
    note: "an established channel (created 2015) that gained 71,000 subscribers in 30 days, a 34.0% increase over its subscriber base a month earlier",
  },
};
