// Single source of truth for the YouTube Sports game channel growth report
// (part of Video game culture).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Sports game" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeSportsGameSubReport: YoutubeSubgenreReport = {
  subgenre: "Sports game",
  parentCategory: "Video game culture",
  parentSlug: "gaming",
  region: "global",
  dataAsOf: "2026-10-10",
  updatedAt: "2026-10-10",
  channels: [
    {
      channelName: "KING PLAYER",
      channelUrl: "https://www.youtube.com/channel/UCrhzIFmFwvb9Xegt_q561aw",
      topic: "Video game culture, Sports game",
      subscribers: 119000,
      subsGained30d: 54100,
      growthPct: 83.4,
      viewsGained30d: 43295568,
      channelCreatedAt: "2020-02-01",
    },
    {
      channelName: "R PES GAMING",
      channelUrl: "https://www.youtube.com/channel/UC0sKozOrglalgTLlsne6BlQ",
      topic: "Video game culture, Sports game",
      subscribers: 102000,
      subsGained30d: 44400,
      growthPct: 77.1,
      viewsGained30d: 2649876,
      channelCreatedAt: "2020-05-16",
    },
    {
      channelName: "4zFAIZI GAMING",
      channelUrl: "https://www.youtube.com/channel/UC1KM9w7D3y0yynU_hmxpmKA",
      topic: "Video game culture, Sports game",
      subscribers: 132000,
      subsGained30d: 38300,
      growthPct: 40.9,
      viewsGained30d: 2716484,
      channelCreatedAt: "2020-06-11",
    },
    {
      channelName: "RixGo",
      channelUrl: "https://www.youtube.com/channel/UCN4dZDSn5pfuDWCV7Q89rjA",
      topic: "Sports game, Video game culture",
      subscribers: 115000,
      subsGained30d: 27700,
      growthPct: 31.7,
      viewsGained30d: 53125506,
      channelCreatedAt: "2025-02-11",
    },
    {
      channelName: "SOJEEB FCC",
      channelUrl: "https://www.youtube.com/channel/UCMFBTBaBDA_AB0XwCMDR99w",
      topic: "Video game culture, Sports game",
      subscribers: 115000,
      subsGained30d: 23800,
      growthPct: 26.1,
      viewsGained30d: 18628578,
      channelCreatedAt: "2024-10-28",
    },
    {
      channelName: "Vanzi Game",
      channelUrl: "https://www.youtube.com/channel/UCETEO8MToxzWisEcVqA8nJg",
      topic: "Video game culture, Sports game",
      subscribers: 66200,
      subsGained30d: 13200,
      growthPct: 24.9,
      viewsGained30d: 22126358,
      channelCreatedAt: "2020-07-09",
    },
    {
      channelName: "THE SIKE_FC",
      channelUrl: "https://www.youtube.com/channel/UCUF4YiIhhX3Cu9uBN7N1xEA",
      topic: "Video game culture, Sports game",
      subscribers: 128000,
      subsGained30d: 25000,
      growthPct: 24.3,
      viewsGained30d: 8162763,
      channelCreatedAt: "2022-12-03",
    },
    {
      channelName: "Kaueafc",
      channelUrl: "https://www.youtube.com/channel/UCCqZ9ubf9IcSEdFH8fwyxBw",
      topic: "Video game culture, Sports game",
      subscribers: 439000,
      subsGained30d: 84000,
      growthPct: 23.7,
      viewsGained30d: 36720949,
      channelCreatedAt: "2022-11-26",
    },
    {
      channelName: "AZ FC MOBILE 2.0",
      channelUrl: "https://www.youtube.com/channel/UCDnV4fog0C2qEIKSJ4k7f8A",
      topic: "Video game culture, Sports game",
      subscribers: 50100,
      subsGained30d: 9500,
      growthPct: 23.4,
      viewsGained30d: 7887828,
      channelCreatedAt: "2021-10-11",
    },
    {
      channelName: "Sepuh FC",
      channelUrl: "https://www.youtube.com/channel/UCoCPQJhls4xLOCL_BWQoX6A",
      topic: "Video game culture, Sports game",
      subscribers: 207000,
      subsGained30d: 37000,
      growthPct: 21.8,
      viewsGained30d: 79452140,
      channelCreatedAt: "2020-12-01",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Video game culture niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "KING PLAYER",
    note: "an established channel (created 2020) that gained 54,100 subscribers in 30 days, a 83.4% increase over its subscriber base a month earlier",
  },
};
