// Single source of truth for the YouTube Reggae channel growth report
// (part of Music).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Reggae" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeReggaeSubReport: YoutubeSubgenreReport = {
  subgenre: "Reggae",
  parentCategory: "Music",
  parentSlug: "music",
  region: "global",
  dataAsOf: "2026-10-10",
  updatedAt: "2026-10-10",
  channels: [
    {
      channelName: "Anslom",
      channelUrl: "https://www.youtube.com/channel/UCZfrSANBhLtWT04Be661npA",
      topic: "Reggae, Music",
      subscribers: 94700,
      subsGained30d: 22400,
      growthPct: 31.0,
      viewsGained30d: 254185,
      channelCreatedAt: "2013-11-14",
    },
    {
      channelName: "Natty Bix Reggae Channel",
      channelUrl: "https://www.youtube.com/channel/UCPfXf-m6JYy5ciDb8dhqsBQ",
      topic: "Reggae, Music",
      subscribers: 59500,
      subsGained30d: 6300,
      growthPct: 11.8,
      viewsGained30d: 32678,
      channelCreatedAt: "2021-10-04",
    },
    {
      channelName: "Pinoy Reggae Republic",
      channelUrl: "https://www.youtube.com/channel/UC69jduqvaN0x70SdxKerUuQ",
      topic: "Reggae, Music",
      subscribers: 105000,
      subsGained30d: 8000,
      growthPct: 8.2,
      viewsGained30d: 4648243,
      channelCreatedAt: "2024-12-13",
    },
    {
      channelName: "London Yardie Tv",
      channelUrl: "https://www.youtube.com/channel/UCAktv8S-sFihYtMXNA8tF9A",
      topic: "Reggae, Music",
      subscribers: 86900,
      subsGained30d: 6100,
      growthPct: 7.5,
      viewsGained30d: 130360,
      channelCreatedAt: "2016-01-27",
    },
    {
      channelName: "elbarouke",
      channelUrl: "https://www.youtube.com/channel/UCFv10htERDWh7lg1vKw-WqA",
      topic: "Music, Reggae",
      subscribers: 51400,
      subsGained30d: 2600,
      growthPct: 5.3,
      viewsGained30d: 1672254,
      channelCreatedAt: "2020-06-25",
    },
    {
      channelName: "CoyCoy Reggae",
      channelUrl: "https://www.youtube.com/channel/UCFeC0B-pGwNVGmL_Kwt9_LA",
      topic: "Music, Reggae",
      subscribers: 55800,
      subsGained30d: 2000,
      growthPct: 3.7,
      viewsGained30d: 2606745,
      channelCreatedAt: "2025-05-30",
    },
    {
      channelName: "Studio Room",
      channelUrl: "https://www.youtube.com/channel/UC8kFz9iwf7kzlQcloM1f7vw",
      topic: "Music, Reggae",
      subscribers: 114000,
      subsGained30d: 4000,
      growthPct: 3.6,
      viewsGained30d: 1305337,
      channelCreatedAt: "2024-06-25",
    },
    {
      channelName: "Jeffstar Chizi",
      channelUrl: "https://www.youtube.com/channel/UCkUbcUoPoL950z93RjBMvMg",
      topic: "Music, Reggae",
      subscribers: 68700,
      subsGained30d: 2000,
      growthPct: 3.0,
      viewsGained30d: 319020,
      channelCreatedAt: "2022-02-25",
    },
    {
      channelName: "B N Bluenight Vlog",
      channelUrl: "https://www.youtube.com/channel/UCDpijJh_W4w8wqsCgAgjGeQ",
      topic: "Music, Reggae",
      subscribers: 89200,
      subsGained30d: 2100,
      growthPct: 2.4,
      viewsGained30d: 997621,
      channelCreatedAt: "2024-10-08",
    },
    {
      channelName: "Ni Yar Ma",
      channelUrl: "https://www.youtube.com/channel/UCxo1pu9YNG4SjFEGFvQvZrw",
      topic: "Music, Reggae",
      subscribers: 264000,
      subsGained30d: 6000,
      growthPct: 2.3,
      viewsGained30d: 2319488,
      channelCreatedAt: "2020-02-29",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Music niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Anslom",
    note: "an established channel (created 2013) that gained 22,400 subscribers in 30 days, a 31.0% increase over its subscriber base a month earlier",
  },
};
