// Single source of truth for the YouTube Fashion channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Fashion" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeFashionReport: YoutubeNicheReport = {
  niche: "Fashion",
  region: "global",
  dataAsOf: "2026-10-07",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "BarQode Fashion",
      channelUrl: "https://www.youtube.com/channel/UCnOca60yTdOxv2W9es0FLUg",
      topic: "Lifestyle (sociology), Fashion",
      subscribers: 95600,
      subsGained30d: 40800,
      growthPct: 74.5,
      viewsGained30d: 41558431,
      channelCreatedAt: "2022-09-13",
    },
    {
      channelName: "Midlife Posh Closet",
      channelUrl: "https://www.youtube.com/channel/UC6kK_zoyGp1LcwN520Nk7TA",
      topic: "Fashion, Lifestyle (sociology)",
      subscribers: 142000,
      subsGained30d: 52300,
      growthPct: 58.3,
      viewsGained30d: 515932,
      channelCreatedAt: "2022-12-01",
    },
    {
      channelName: "Style Alchemy By Priyanshi",
      channelUrl: "https://www.youtube.com/channel/UC7dwIrrYuOOs1LyLSXDHFHQ",
      topic: "Lifestyle (sociology), Fashion",
      subscribers: 66200,
      subsGained30d: 23100,
      growthPct: 53.6,
      viewsGained30d: 20091161,
      channelCreatedAt: "2024-07-30",
    },
    {
      channelName: "Agus Ngonten",
      channelUrl: "https://www.youtube.com/channel/UCq1oEzDHX1SUCn7AedepfHg",
      topic: "Lifestyle (sociology), Fashion",
      subscribers: 113000,
      subsGained30d: 39300,
      growthPct: 53.3,
      viewsGained30d: 81724355,
      channelCreatedAt: "2025-04-09",
    },
    {
      channelName: "Lekha kumar",
      channelUrl: "https://www.youtube.com/channel/UCWTWAdb2TmmtD7rrn19KzDg",
      topic: "Fashion, Lifestyle (sociology)",
      subscribers: 104000,
      subsGained30d: 33800,
      growthPct: 48.1,
      viewsGained30d: 74635073,
      channelCreatedAt: "2019-03-10",
    },
    {
      channelName: "びすこ visco",
      channelUrl: "https://www.youtube.com/channel/UCKhv4yLR1e-kYJ1n1xM0sPw",
      topic: "Fashion, Lifestyle (sociology)",
      subscribers: 55200,
      subsGained30d: 17700,
      growthPct: 47.2,
      viewsGained30d: 1938350,
      channelCreatedAt: "2023-08-24",
    },
    {
      channelName: "Emily Bianca",
      channelUrl: "https://www.youtube.com/channel/UC61pWjEP87hvofrfVDGhlFQ",
      topic: "Lifestyle (sociology), Fashion",
      subscribers: 224000,
      subsGained30d: 70000,
      growthPct: 45.5,
      viewsGained30d: 30180261,
      channelCreatedAt: "2025-03-11",
    },
    {
      channelName: "KaRtIkAy",
      channelUrl: "https://www.youtube.com/channel/UCk7Ds_OAzpmcnJy_zAcX_PQ",
      topic: "Lifestyle (sociology), Fashion",
      subscribers: 294000,
      subsGained30d: 90000,
      growthPct: 44.1,
      viewsGained30d: 138245548,
      channelCreatedAt: "2017-12-01",
    },
    {
      channelName: "Justina",
      channelUrl: "https://www.youtube.com/channel/UCQ8SRxehWl_cbboVCI3MDpQ",
      topic: "Lifestyle (sociology), Fashion",
      subscribers: 77900,
      subsGained30d: 23300,
      growthPct: 42.7,
      viewsGained30d: 5791985,
      channelCreatedAt: "2022-06-19",
    },
    {
      channelName: "Ashanti Finds",
      channelUrl: "https://www.youtube.com/channel/UCQ37I3RXFxJcYZeUX1frdWA",
      topic: "Fashion, Lifestyle (sociology)",
      subscribers: 66900,
      subsGained30d: 19300,
      growthPct: 40.5,
      viewsGained30d: 11281440,
      channelCreatedAt: "2017-10-08",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "BarQode Fashion",
    note: "an established channel (created 2022) that gained 40,800 subscribers in 30 days, a 74.5% increase over its subscriber base a month earlier",
  },
};
