// Single source of truth for the YouTube Television program channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Television program" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeTvReport: YoutubeNicheReport = {
  niche: "Television program",
  region: "global",
  dataAsOf: "2026-10-09",
  updatedAt: "2026-10-09",
  channels: [
    {
      channelName: "trisha.",
      channelUrl: "https://www.youtube.com/channel/UCbKPM3vIsVbDq_twW4II0nw",
      topic: "Entertainment, Television program",
      subscribers: 51100,
      subsGained30d: 17800,
      growthPct: 53.5,
      viewsGained30d: 126526964,
      channelCreatedAt: "2026-06-27",
    },
    {
      channelName: "La Granja VIP México",
      channelUrl: "https://www.youtube.com/channel/UCxpdJ_TaB2SV9dW6TMpXWkg",
      topic: "Entertainment, Television program",
      subscribers: 258000,
      subsGained30d: 57000,
      growthPct: 28.4,
      viewsGained30d: 115926154,
      channelCreatedAt: "2025-07-08",
    },
    {
      channelName: "Tyler Henry - The Hollywood Medium - Official Page",
      channelUrl: "https://www.youtube.com/channel/UC9aRKPT_J5mtgics0v9wNHg",
      topic: "Television program, Entertainment",
      subscribers: 64000,
      subsGained30d: 10800,
      growthPct: 20.3,
      viewsGained30d: 20431,
      channelCreatedAt: "2019-03-15",
    },
    {
      channelName: "Reality new",
      channelUrl: "https://www.youtube.com/channel/UCLkgpRImTIqkgzQO4wKsqcw",
      topic: "Television program, Entertainment",
      subscribers: 50300,
      subsGained30d: 7900,
      growthPct: 18.6,
      viewsGained30d: 2597840,
      channelCreatedAt: "2013-09-25",
    },
    {
      channelName: "Mehfil e Ramzan - Danish Taimoor & Rabia Anum",
      channelUrl: "https://www.youtube.com/channel/UC44SC58z4MAeZLYYAby0c6Q",
      topic: "Television program, Entertainment",
      subscribers: 201000,
      subsGained30d: 25000,
      growthPct: 14.2,
      viewsGained30d: 42265917,
      channelCreatedAt: "2026-01-28",
    },
    {
      channelName: "Narox Edit",
      channelUrl: "https://www.youtube.com/channel/UCQiMHqvzIxEi_EqW9ryj_cw",
      topic: "Television program, Entertainment",
      subscribers: 70200,
      subsGained30d: 8500,
      growthPct: 13.8,
      viewsGained30d: 2553510,
      channelCreatedAt: "2026-01-19",
    },
    {
      channelName: "ละครสั้นโรแมนติก",
      channelUrl: "https://www.youtube.com/channel/UCOT1HIpOyQx58JCcq-z6fUg",
      topic: "Television program, Entertainment",
      subscribers: 75700,
      subsGained30d: 9000,
      growthPct: 13.5,
      viewsGained30d: 4682053,
      channelCreatedAt: "2025-06-24",
    },
    {
      channelName: "Reality Art Pod",
      channelUrl: "https://www.youtube.com/channel/UCKRC7rrFsUc0je5cUbN0wCw",
      topic: "Television program, Entertainment",
      subscribers: 64600,
      subsGained30d: 6800,
      growthPct: 11.8,
      viewsGained30d: 184859,
      channelCreatedAt: "2023-07-14",
    },
    {
      channelName: "Yuwaedit",
      channelUrl: "https://www.youtube.com/channel/UClZ16ZkUG6eF94ZIv3uBdVg",
      topic: "Television program, Entertainment",
      subscribers: 456000,
      subsGained30d: 41000,
      growthPct: 9.9,
      viewsGained30d: 60843256,
      channelCreatedAt: "2025-06-14",
    },
    {
      channelName: "Arman silawat",
      channelUrl: "https://www.youtube.com/channel/UCT2dJlCZe7_3slvegzYc8xw",
      topic: "Television program, Entertainment",
      subscribers: 53000,
      subsGained30d: 4500,
      growthPct: 9.3,
      viewsGained30d: 61259351,
      channelCreatedAt: "2024-04-22",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "trisha.",
    note: "a newer channel (created 2026) that gained 17,800 subscribers in 30 days, a 53.5% increase over its subscriber base a month earlier",
  },
};
