// Single source of truth for the YouTube Religion channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Religion" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeReligionReport: YoutubeNicheReport = {
  niche: "Religion",
  region: "global",
  dataAsOf: "2026-10-07",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Lecciones De Sabios",
      channelUrl: "https://www.youtube.com/channel/UCnKM6eWPSHKhA65L4HOI1ZQ",
      topic: "Society, Religion",
      subscribers: 208000,
      subsGained30d: 173400,
      growthPct: 501.2,
      viewsGained30d: 3179678,
      channelCreatedAt: "2025-05-16",
    },
    {
      channelName: "Amira Arora & Aryaan Arora",
      channelUrl: "https://www.youtube.com/channel/UCzuo1FFstOnPOTirMfD0tjg",
      topic: "Religion, Society",
      subscribers: 1070000,
      subsGained30d: 768000,
      growthPct: 254.3,
      viewsGained30d: 12733722,
      channelCreatedAt: "2023-06-03",
    },
    {
      channelName: "TOXIC ROSTER",
      channelUrl: "https://www.youtube.com/channel/UCDHz3eq0FIFHGomcEE2r1pg",
      topic: "Religion, Society",
      subscribers: 69100,
      subsGained30d: 45400,
      growthPct: 191.6,
      viewsGained30d: 6944200,
      channelCreatedAt: "2023-01-16",
    },
    {
      channelName: "Naju Mary",
      channelUrl: "https://www.youtube.com/channel/UC3wAxdCmGkaUmMga8x0pxKQ",
      topic: "Religion, Society",
      subscribers: 66200,
      subsGained30d: 35600,
      growthPct: 116.3,
      viewsGained30d: 1340122,
      channelCreatedAt: "2013-10-14",
    },
    {
      channelName: "Greg Fritz",
      channelUrl: "https://www.youtube.com/channel/UCrR9Rsx4h_RqYigda2PysZQ",
      topic: "Society, Religion",
      subscribers: 109000,
      subsGained30d: 47600,
      growthPct: 77.5,
      viewsGained30d: 528063,
      channelCreatedAt: "2017-07-27",
    },
    {
      channelName: "Paul S Joshua",
      channelUrl: "https://www.youtube.com/channel/UChRbKdwDadrNY1RUVTjRC-g",
      topic: "Society, Religion",
      subscribers: 337000,
      subsGained30d: 139000,
      growthPct: 70.2,
      viewsGained30d: 1580421,
      channelCreatedAt: "2014-01-04",
    },
    {
      channelName: "Faith & Fiction Bookclub",
      channelUrl: "https://www.youtube.com/channel/UCHHi89Dhsoqp9zkFQXvIF0w",
      topic: "Lifestyle (sociology), Religion",
      subscribers: 52000,
      subsGained30d: 18900,
      growthPct: 57.1,
      viewsGained30d: 2553398,
      channelCreatedAt: "2025-07-03",
    },
    {
      channelName: "ReasonableFaithOrg",
      channelUrl: "https://www.youtube.com/channel/UCXHkMZGwB9g4rW4BV45ISbA",
      topic: "Society, Religion",
      subscribers: 220000,
      subsGained30d: 79000,
      growthPct: 56.0,
      viewsGained30d: 873785,
      channelCreatedAt: "2011-04-19",
    },
    {
      channelName: "Braj ke Sant",
      channelUrl: "https://www.youtube.com/channel/UCgPDtG95sT6SsKz5MA8LLKg",
      topic: "Society, Religion",
      subscribers: 70700,
      subsGained30d: 25300,
      growthPct: 55.7,
      viewsGained30d: 16204922,
      channelCreatedAt: "2024-10-03",
    },
    {
      channelName: "MOTIVATIONAL GAPPU 09",
      channelUrl: "https://www.youtube.com/channel/UCATRB0v1r1qU6pQFRjOLguQ",
      topic: "Society, Religion",
      subscribers: 87400,
      subsGained30d: 30400,
      growthPct: 53.3,
      viewsGained30d: 23296615,
      channelCreatedAt: "2025-05-10",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Lecciones De Sabios",
    note: "a newer channel (created 2025) that gained 173,400 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
