// Single source of truth for the YouTube Music channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Music" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeMusicReport: YoutubeNicheReport = {
  niche: "Music",
  region: "global",
  dataAsOf: "2026-10-06",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Ambient Interludes",
      channelUrl: "https://www.youtube.com/channel/UC5FZd7doj7I-nc8EkPHM-EA",
      topic: "Electronic music, Music",
      subscribers: 110000,
      subsGained30d: 82300,
      growthPct: 297.1,
      viewsGained30d: 507021,
      channelCreatedAt: "2025-11-28",
    },
    {
      channelName: "Eldruna",
      channelUrl: "https://www.youtube.com/channel/UC8GwGrfyesS_qWqd-WeO_cA",
      topic: "Music, Lifestyle (sociology)",
      subscribers: 166000,
      subsGained30d: 114100,
      growthPct: 219.8,
      viewsGained30d: 43026636,
      channelCreatedAt: "2026-02-25",
    },
    {
      channelName: "Sandhu GS World",
      channelUrl: "https://www.youtube.com/channel/UCOKFsYrHT_w9UUwzmPEkvOA",
      topic: "Music, Music of Asia",
      subscribers: 62400,
      subsGained30d: 37000,
      growthPct: 145.7,
      viewsGained30d: 32488899,
      channelCreatedAt: "2020-09-26",
    },
    {
      channelName: "Dan Mylor",
      channelUrl: "https://www.youtube.com/channel/UClxlb8FBD-t4zaHlk411uKw",
      topic: "Electronic music, Music",
      subscribers: 103000,
      subsGained30d: 60000,
      growthPct: 139.5,
      viewsGained30d: 626593,
      channelCreatedAt: "2021-05-26",
    },
    {
      channelName: "Sea Beauty",
      channelUrl: "https://www.youtube.com/channel/UC6T-hLWsv9bJpcXStd1OUaw",
      topic: "Lifestyle (sociology), Music of Asia",
      subscribers: 101000,
      subsGained30d: 56800,
      growthPct: 128.5,
      viewsGained30d: 70870540,
      channelCreatedAt: "2025-04-12",
    },
    {
      channelName: "Bhai Manpreet Singh Ji Kanpuri - Topic",
      channelUrl: "https://www.youtube.com/channel/UCOcjUT32hH7XsRZsgv35Yyw",
      topic: "Music, Music of Asia",
      subscribers: 55600,
      subsGained30d: 28000,
      growthPct: 101.4,
      viewsGained30d: 1040234,
      channelCreatedAt: "2022-07-11",
    },
    {
      channelName: "CIRCOLOCO",
      channelUrl: "https://www.youtube.com/channel/UCanV1p6ynx_FzdsraKLousQ",
      topic: "Music, Electronic music",
      subscribers: 124000,
      subsGained30d: 59200,
      growthPct: 91.4,
      viewsGained30d: 1256397,
      channelCreatedAt: "2013-05-14",
    },
    {
      channelName: "People\\'s Vybe",
      channelUrl: "https://www.youtube.com/channel/UCOo1MTcMkhYWI6hEOIh9d0g",
      topic: "Music of Asia, Music",
      subscribers: 59800,
      subsGained30d: 28400,
      growthPct: 90.4,
      viewsGained30d: 31700634,
      channelCreatedAt: "2021-02-03",
    },
    {
      channelName: "Ai after 50 with Pops",
      channelUrl: "https://www.youtube.com/channel/UCCccvR3f07P9VAi1Ip2s2EQ",
      topic: "Lifestyle (sociology), Music",
      subscribers: 78600,
      subsGained30d: 35800,
      growthPct: 83.6,
      viewsGained30d: 2692659,
      channelCreatedAt: "2026-02-22",
    },
    {
      channelName: "Yamaha Music India",
      channelUrl: "https://www.youtube.com/channel/UCOr0lS8PGv0dKl0QldyKkqw",
      topic: "Rock music, Music",
      subscribers: 62400,
      subsGained30d: 28100,
      growthPct: 81.9,
      viewsGained30d: 2485465,
      channelCreatedAt: "2011-07-27",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Ambient Interludes",
    note: "a newer channel (created 2025) that gained 82,300 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
