// Single source of truth for the YouTube Music of Latin America channel growth report
// (part of Music).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Music of Latin America" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeMusicOfLatinAmericaSubReport: YoutubeSubgenreReport = {
  subgenre: "Music of Latin America",
  parentCategory: "Music",
  parentSlug: "music",
  region: "global",
  dataAsOf: "2026-10-08",
  updatedAt: "2026-10-08",
  channels: [
    {
      channelName: "Aprende con musica infantil",
      channelUrl: "https://www.youtube.com/channel/UC0DL6Sn5-I4p4_Wy2nu-s2A",
      topic: "Music, Music of Latin America",
      subscribers: 76700,
      subsGained30d: 24800,
      growthPct: 47.8,
      viewsGained30d: 7166119,
      channelCreatedAt: "2025-03-01",
    },
    {
      channelName: "Allê No Beat",
      channelUrl: "https://www.youtube.com/channel/UCPIKprANiVFmB0JSa3Fwx3g",
      topic: "Music of Latin America, Music",
      subscribers: 75800,
      subsGained30d: 21600,
      growthPct: 39.9,
      viewsGained30d: 19100287,
      channelCreatedAt: "2021-05-17",
    },
    {
      channelName: "Heitor Santos",
      channelUrl: "https://www.youtube.com/channel/UClOzTICWhUiv1Mo3aQEBSJA",
      topic: "Music of Latin America, Music",
      subscribers: 211000,
      subsGained30d: 47000,
      growthPct: 28.7,
      viewsGained30d: 63602451,
      channelCreatedAt: "2021-01-07",
    },
    {
      channelName: "Dinero Nuevo Records",
      channelUrl: "https://www.youtube.com/channel/UCMiQjKOnve7K_gTz-5oDB0Q",
      topic: "Music of Latin America, Music",
      subscribers: 85800,
      subsGained30d: 12300,
      growthPct: 16.7,
      viewsGained30d: 452701,
      channelCreatedAt: "2020-06-19",
    },
    {
      channelName: "Mc Chaverin",
      channelUrl: "https://www.youtube.com/channel/UCMMdPt6IQD1sVY6ouHYhFtQ",
      topic: "Music of Latin America, Music",
      subscribers: 108000,
      subsGained30d: 15200,
      growthPct: 16.4,
      viewsGained30d: 6979738,
      channelCreatedAt: "2020-04-24",
    },
    {
      channelName: "Dalvin La Melodia",
      channelUrl: "https://www.youtube.com/channel/UCOrJOjD3lXUyZBiJTNeBOzw",
      topic: "Music, Music of Latin America",
      subscribers: 678000,
      subsGained30d: 95000,
      growthPct: 16.3,
      viewsGained30d: 94123356,
      channelCreatedAt: "2024-06-11",
    },
    {
      channelName: "Zé Ngola",
      channelUrl: "https://www.youtube.com/channel/UCd6vQdTdK0Ofga-L1aI4wNw",
      topic: "Music, Music of Latin America",
      subscribers: 71500,
      subsGained30d: 9700,
      growthPct: 15.7,
      viewsGained30d: 7280523,
      channelCreatedAt: "2026-04-12",
    },
    {
      channelName: "Frutas Bailando Oficial",
      channelUrl: "https://www.youtube.com/channel/UCRzmrDJEaXT1iAcVs5MscGg",
      topic: "Music of Latin America, Music",
      subscribers: 275000,
      subsGained30d: 37000,
      growthPct: 15.5,
      viewsGained30d: 130724838,
      channelCreatedAt: "2023-05-24",
    },
    {
      channelName: "Plzuero TV",
      channelUrl: "https://www.youtube.com/channel/UCwqv_wO16JrSSsyymo5CJCg",
      topic: "Music of Latin America, Music",
      subscribers: 65400,
      subsGained30d: 8400,
      growthPct: 14.7,
      viewsGained30d: 1222813,
      channelCreatedAt: "2022-09-17",
    },
    {
      channelName: "Fil",
      channelUrl: "https://www.youtube.com/channel/UC-UuEgKVYa22CSXKUaTS-uQ",
      topic: "Music, Music of Latin America",
      subscribers: 320000,
      subsGained30d: 41000,
      growthPct: 14.7,
      viewsGained30d: 22030717,
      channelCreatedAt: "2017-06-11",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Music niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Aprende con musica infantil",
    note: "a newer channel (created 2025) that gained 24,800 subscribers in 30 days, a 47.8% increase over its subscriber base a month earlier",
  },
};
