// Single source of truth for the YouTube Physical attractiveness channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Physical attractiveness" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeBeautyReport: YoutubeNicheReport = {
  niche: "Physical attractiveness",
  region: "global",
  dataAsOf: "2026-10-10",
  updatedAt: "2026-10-10",
  channels: [
    {
      channelName: "MakeupDiscovery",
      channelUrl: "https://www.youtube.com/channel/UCDma-UpDUSHV252QedH6vSg",
      topic: "Lifestyle (sociology), Physical attractiveness",
      subscribers: 66300,
      subsGained30d: 16300,
      growthPct: 32.6,
      viewsGained30d: 8933815,
      channelCreatedAt: "2008-04-13",
    },
    {
      channelName: "FASHION ZONE",
      channelUrl: "https://www.youtube.com/channel/UCM1baoPv4R5JemF0YMk4RJg",
      topic: "Lifestyle (sociology), Physical attractiveness",
      subscribers: 153000,
      subsGained30d: 26000,
      growthPct: 20.5,
      viewsGained30d: 19627270,
      channelCreatedAt: "2025-10-01",
    },
    {
      channelName: "Fashion full asma",
      channelUrl: "https://www.youtube.com/channel/UCH4wGolnASt2L463tgbcH4Q",
      topic: "Physical attractiveness, Lifestyle (sociology)",
      subscribers: 52100,
      subsGained30d: 5400,
      growthPct: 11.6,
      viewsGained30d: 4609900,
      channelCreatedAt: "2022-12-15",
    },
    {
      channelName: "Aria Vale",
      channelUrl: "https://www.youtube.com/channel/UCHQMcSbHKDS6c-e97wmX_Ug",
      topic: "Lifestyle (sociology), Physical attractiveness",
      subscribers: 58700,
      subsGained30d: 6100,
      growthPct: 11.6,
      viewsGained30d: 1337370,
      channelCreatedAt: "2025-11-13",
    },
    {
      channelName: "Pink Vogue",
      channelUrl: "https://www.youtube.com/channel/UCN_mmUXd50HLP6M-4oXcvVQ",
      topic: "Lifestyle (sociology), Physical attractiveness",
      subscribers: 61400,
      subsGained30d: 5200,
      growthPct: 9.3,
      viewsGained30d: 4234985,
      channelCreatedAt: "2023-09-13",
    },
    {
      channelName: "Janelle Zharmenova",
      channelUrl: "https://www.youtube.com/channel/UCN-lpUPvzl3uVHA9G7hqjdw",
      topic: "Physical attractiveness, Lifestyle (sociology)",
      subscribers: 198000,
      subsGained30d: 16000,
      growthPct: 8.8,
      viewsGained30d: 11711751,
      channelCreatedAt: "2020-06-29",
    },
    {
      channelName: "Zoomology",
      channelUrl: "https://www.youtube.com/channel/UCGMndG_WdoQZEb1KD3UnVdA",
      topic: "Knowledge, Physical attractiveness",
      subscribers: 152000,
      subsGained30d: 10000,
      growthPct: 7.0,
      viewsGained30d: 3803159,
      channelCreatedAt: "2024-03-25",
    },
    {
      channelName: "Mandira dhungana",
      channelUrl: "https://www.youtube.com/channel/UCpcaWizJlbwDKtRosoCC1AQ",
      topic: "Lifestyle (sociology), Physical attractiveness",
      subscribers: 198000,
      subsGained30d: 12000,
      growthPct: 6.5,
      viewsGained30d: 30304925,
      channelCreatedAt: "2025-02-13",
    },
    {
      channelName: "Essence Elizabeth",
      channelUrl: "https://www.youtube.com/channel/UCiAbkMKmUgDz3EtfyA9MypQ",
      topic: "Physical attractiveness, Lifestyle (sociology)",
      subscribers: 61900,
      subsGained30d: 3600,
      growthPct: 6.2,
      viewsGained30d: 2691885,
      channelCreatedAt: "2022-05-03",
    },
    {
      channelName: "Paris Francisca",
      channelUrl: "https://www.youtube.com/channel/UCDitEaLG4FFrf0WQWX78nDw",
      topic: "Physical attractiveness, Lifestyle (sociology)",
      subscribers: 106000,
      subsGained30d: 6000,
      growthPct: 6.0,
      viewsGained30d: 13790715,
      channelCreatedAt: "2020-04-08",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "MakeupDiscovery",
    note: "an established channel (created 2008) that gained 16,300 subscribers in 30 days, a 32.6% increase over its subscriber base a month earlier",
  },
};
