// Single source of truth for the YouTube Music video game channel growth report
// (part of Video game culture).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Music video game" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeMusicVideoGameSubReport: YoutubeSubgenreReport = {
  subgenre: "Music video game",
  parentCategory: "Video game culture",
  parentSlug: "gaming",
  region: "global",
  dataAsOf: "2026-10-06",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Pouria SFMs",
      channelUrl: "https://www.youtube.com/channel/UCRzbNDQHsRI6xPj-YFHAlEw",
      topic: "Music video game, Video game culture",
      subscribers: 227000,
      subsGained30d: 25000,
      growthPct: 12.4,
      viewsGained30d: 6043970,
      channelCreatedAt: "2019-07-15",
    },
    {
      channelName: "wakeupvoid",
      channelUrl: "https://www.youtube.com/channel/UCbvpRLxcPXGFLeBhReUbt7g",
      topic: "Music video game, Video game culture",
      subscribers: 54100,
      subsGained30d: 4900,
      growthPct: 10.0,
      viewsGained30d: 6405510,
      channelCreatedAt: "2020-11-17",
    },
    {
      channelName: "ひろと",
      channelUrl: "https://www.youtube.com/channel/UC3iI4AriSEyFPFcGJAZd7ew",
      topic: "Video game culture, Music video game",
      subscribers: 88400,
      subsGained30d: 5900,
      growthPct: 7.2,
      viewsGained30d: 8696012,
      channelCreatedAt: "2018-10-08",
    },
    {
      channelName: "Magic Tiles 3 Official",
      channelUrl: "https://www.youtube.com/channel/UCo4q4zYut_1P9QpCWfr_Cxg",
      topic: "Video game culture, Music video game",
      subscribers: 136000,
      subsGained30d: 9000,
      growthPct: 7.1,
      viewsGained30d: 36950347,
      channelCreatedAt: "2019-02-26",
    },
    {
      channelName: "SuperPibby",
      channelUrl: "https://www.youtube.com/channel/UC1_NCQv70u1gUDsPlzaf-iw",
      topic: "Music video game, Video game culture",
      subscribers: 305000,
      subsGained30d: 20000,
      growthPct: 7.0,
      viewsGained30d: 22524467,
      channelCreatedAt: "2012-05-04",
    },
    {
      channelName: "TOKOYAMi",
      channelUrl: "https://www.youtube.com/channel/UCZ8wWU0teJKhqP56OK2tDzA",
      topic: "Music video game, Video game culture",
      subscribers: 177000,
      subsGained30d: 11000,
      growthPct: 6.6,
      viewsGained30d: 35273824,
      channelCreatedAt: "2021-08-29",
    },
    {
      channelName: "mrekkLIVE",
      channelUrl: "https://www.youtube.com/channel/UCR9fYkWlxT2VBFyoRLa304g",
      topic: "Music video game, Video game culture",
      subscribers: 50600,
      subsGained30d: 3100,
      growthPct: 6.5,
      viewsGained30d: 3300583,
      channelCreatedAt: "2019-07-20",
    },
    {
      channelName: "FridayNightFunkin",
      channelUrl: "https://www.youtube.com/channel/UC9RfC_6a8t8MaN9GwFSjG1A",
      topic: "Music video game, Video game culture",
      subscribers: 262000,
      subsGained30d: 12000,
      growthPct: 4.8,
      viewsGained30d: 490472,
      channelCreatedAt: "2024-02-25",
    },
    {
      channelName: "SPTUNKI LIVE",
      channelUrl: "https://www.youtube.com/channel/UCWKidFzcP-NjEBPPP7X1waQ",
      topic: "Music video game, Video game culture",
      subscribers: 220000,
      subsGained30d: 10000,
      growthPct: 4.8,
      viewsGained30d: 129237,
      channelCreatedAt: "2024-10-25",
    },
    {
      channelName: "mrekk",
      channelUrl: "https://www.youtube.com/channel/UCGccXmPtpSqfFFTHfN0jqMw",
      topic: "Music video game, Video game culture",
      subscribers: 224000,
      subsGained30d: 8000,
      growthPct: 3.7,
      viewsGained30d: 4293576,
      channelCreatedAt: "2017-05-13",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Video game culture niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Pouria SFMs",
    note: "an established channel (created 2019) that gained 25,000 subscribers in 30 days, a 12.4% increase over its subscriber base a month earlier",
  },
};
