// Single source of truth for the YouTube American football channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "American football" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeAmericanFootballReport: YoutubeNicheReport = {
  niche: "American football",
  region: "global",
  dataAsOf: "2026-10-06",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Jake Asman",
      channelUrl: "https://www.youtube.com/channel/UCt8ZeGlv3VM8jLYO_EoDMPw",
      topic: "Sport, American football",
      subscribers: 76900,
      subsGained30d: 10500,
      growthPct: 15.8,
      viewsGained30d: 1028476,
      channelCreatedAt: "2012-09-28",
    },
    {
      channelName: "Aaron Wilson",
      channelUrl: "https://www.youtube.com/channel/UCeauI2kqGE-WjpiaeOXjpTA",
      topic: "Sport, American football",
      subscribers: 59800,
      subsGained30d: 5900,
      growthPct: 10.9,
      viewsGained30d: 719194,
      channelCreatedAt: "2024-09-26",
    },
    {
      channelName: "Mile High Huddle",
      channelUrl: "https://www.youtube.com/channel/UC7b4j3SDwSaiSznPXZVbwEw",
      topic: "Sport, American football",
      subscribers: 51700,
      subsGained30d: 5000,
      growthPct: 10.7,
      viewsGained30d: 1024430,
      channelCreatedAt: "2015-05-19",
    },
    {
      channelName: "FRDi Football",
      channelUrl: "https://www.youtube.com/channel/UCuvl83t5GvP4-oNtqFFgYGQ",
      topic: "American football, Sport",
      subscribers: 78200,
      subsGained30d: 6500,
      growthPct: 9.1,
      viewsGained30d: 15034768,
      channelCreatedAt: "2013-10-07",
    },
    {
      channelName: "FieldFlix",
      channelUrl: "https://www.youtube.com/channel/UCNbbLyXISpAgT6MQqa7eUyg",
      topic: "American football, Sport",
      subscribers: 473000,
      subsGained30d: 36000,
      growthPct: 8.2,
      viewsGained30d: 23783451,
      channelCreatedAt: "2022-06-10",
    },
    {
      channelName: "Browns Report by Chat Sports",
      channelUrl: "https://www.youtube.com/channel/UCeADv4IDX1SbUdZHpB35ooA",
      topic: "Sport, American football",
      subscribers: 87000,
      subsGained30d: 5700,
      growthPct: 7.0,
      viewsGained30d: 6290325,
      channelCreatedAt: "2020-05-29",
    },
    {
      channelName: "Los Angeles Rams",
      channelUrl: "https://www.youtube.com/channel/UCyJ6yZdVUkBvt2vl4R03jcA",
      topic: "American football, Sport",
      subscribers: 463000,
      subsGained30d: 25000,
      growthPct: 5.7,
      viewsGained30d: 5666750,
      channelCreatedAt: "2015-05-28",
    },
    {
      channelName: "Ice Sports",
      channelUrl: "https://www.youtube.com/channel/UCJQVn10nU_jZqBPxTGpuqAg",
      topic: "Sport, American football",
      subscribers: 54900,
      subsGained30d: 2900,
      growthPct: 5.6,
      viewsGained30d: 9828753,
      channelCreatedAt: "2022-07-31",
    },
    {
      channelName: "ShedeurSandersTV",
      channelUrl: "https://www.youtube.com/channel/UCmNMY5JGOetwukgvTWb1kpg",
      topic: "American football, Sport",
      subscribers: 89300,
      subsGained30d: 4600,
      growthPct: 5.4,
      viewsGained30d: 10979865,
      channelCreatedAt: "2023-01-02",
    },
    {
      channelName: "Ravens Rundown by Chat Sports",
      channelUrl: "https://www.youtube.com/channel/UCQ-gm4PWPuboxqXvAGbvMug",
      topic: "American football, Sport",
      subscribers: 53200,
      subsGained30d: 2500,
      growthPct: 4.9,
      viewsGained30d: 2600250,
      channelCreatedAt: "2020-05-29",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Jake Asman",
    note: "an established channel (created 2012) that gained 10,500 subscribers in 30 days, a 15.8% increase over its subscriber base a month earlier",
  },
};
