// Single source of truth for the YouTube Knowledge channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Knowledge" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeKnowledgeReport: YoutubeNicheReport = {
  niche: "Knowledge",
  region: "global",
  dataAsOf: "2026-10-07",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Creature Vault",
      channelUrl: "https://www.youtube.com/channel/UC6rD9e3rQ2LRd1pX8uR8zvQ",
      topic: "Lifestyle (sociology), Knowledge",
      subscribers: 392000,
      subsGained30d: 286000,
      growthPct: 269.8,
      viewsGained30d: 11355144,
      channelCreatedAt: "2025-09-19",
    },
    {
      channelName: "インベスターM",
      channelUrl: "https://www.youtube.com/channel/UCnCbD4gu0w90-nL9dRk8H3Q",
      topic: "Knowledge",
      subscribers: 96000,
      subsGained30d: 58300,
      growthPct: 154.6,
      viewsGained30d: 423970,
      channelCreatedAt: "2022-10-02",
    },
    {
      channelName: "Marco Romero",
      channelUrl: "https://www.youtube.com/channel/UCcFfkvEIu2Nyj8zz0-kY94w",
      topic: "Knowledge, Society",
      subscribers: 52800,
      subsGained30d: 31600,
      growthPct: 149.1,
      viewsGained30d: 1039,
      channelCreatedAt: "2025-12-03",
    },
    {
      channelName: "Punjab Education Officiall",
      channelUrl: "https://www.youtube.com/channel/UCiwRJUOh3gj9lwREG5hnYeg",
      topic: "Knowledge",
      subscribers: 109000,
      subsGained30d: 60200,
      growthPct: 123.4,
      viewsGained30d: 7909169,
      channelCreatedAt: "2025-09-13",
    },
    {
      channelName: "Astro Creo",
      channelUrl: "https://www.youtube.com/channel/UCTyMNg7PhEbBUAn7ep7eRVg",
      topic: "Knowledge",
      subscribers: 384000,
      subsGained30d: 204000,
      growthPct: 113.3,
      viewsGained30d: 163823197,
      channelCreatedAt: "2024-12-11",
    },
    {
      channelName: "English with Shivani ma\\'am",
      channelUrl: "https://www.youtube.com/channel/UCTxxMgNKk2uq_a-nCXKDx0Q",
      topic: "Lifestyle (sociology), Knowledge",
      subscribers: 86600,
      subsGained30d: 43900,
      growthPct: 102.8,
      viewsGained30d: 2224758,
      channelCreatedAt: "2024-08-24",
    },
    {
      channelName: "JEET TUTORIAL",
      channelUrl: "https://www.youtube.com/channel/UCwNirLUlH3mPp30w--ptbdQ",
      topic: "Knowledge",
      subscribers: 79700,
      subsGained30d: 39800,
      growthPct: 99.7,
      viewsGained30d: 4866834,
      channelCreatedAt: "2025-08-13",
    },
    {
      channelName: "Tom FitzGerald",
      channelUrl: "https://www.youtube.com/channel/UC2Ge85n6Tk82LqKcOXDOkNw",
      topic: "Knowledge",
      subscribers: 76800,
      subsGained30d: 37400,
      growthPct: 94.9,
      viewsGained30d: 7919926,
      channelCreatedAt: "2022-11-20",
    },
    {
      channelName: "Abhishek Singh Lodhi",
      channelUrl: "https://www.youtube.com/channel/UCQxIFMebigj4DZTuPtx5T0w",
      topic: "Knowledge, Lifestyle (sociology)",
      subscribers: 85000,
      subsGained30d: 40400,
      growthPct: 90.6,
      viewsGained30d: 16195313,
      channelCreatedAt: "2021-10-22",
    },
    {
      channelName: "Clear Physics",
      channelUrl: "https://www.youtube.com/channel/UCusDMnu0ANwHCIuSon-Wyxg",
      topic: "Entertainment, Knowledge",
      subscribers: 273000,
      subsGained30d: 129000,
      growthPct: 89.6,
      viewsGained30d: 22245061,
      channelCreatedAt: "2024-04-23",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Creature Vault",
    note: "a newer channel (created 2025) that gained 286,000 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
