// Single source of truth for the YouTube Music channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Music" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeMusicReport: YoutubeNicheReport = {
  niche: "Music",
  region: "global",
  dataAsOf: "2026-10-08",
  updatedAt: "2026-10-08",
  channels: [
    {
      channelName: "Ambient Interludes",
      channelUrl: "https://www.youtube.com/channel/UC5FZd7doj7I-nc8EkPHM-EA",
      topic: "Electronic music, Music",
      subscribers: 111000,
      subsGained30d: 80500,
      growthPct: 263.9,
      viewsGained30d: 504066,
      channelCreatedAt: "2025-11-28",
    },
    {
      channelName: "Eldruna",
      channelUrl: "https://www.youtube.com/channel/UC8GwGrfyesS_qWqd-WeO_cA",
      topic: "Music, Lifestyle (sociology)",
      subscribers: 172000,
      subsGained30d: 116400,
      growthPct: 209.4,
      viewsGained30d: 44147619,
      channelCreatedAt: "2026-02-25",
    },
    {
      channelName: "Sandhu GS World",
      channelUrl: "https://www.youtube.com/channel/UCOKFsYrHT_w9UUwzmPEkvOA",
      topic: "Music, Music of Asia",
      subscribers: 63900,
      subsGained30d: 36100,
      growthPct: 129.9,
      viewsGained30d: 33968412,
      channelCreatedAt: "2020-09-26",
    },
    {
      channelName: "Sea Beauty",
      channelUrl: "https://www.youtube.com/channel/UC6T-hLWsv9bJpcXStd1OUaw",
      topic: "Lifestyle (sociology), Music of Asia",
      subscribers: 104000,
      subsGained30d: 58400,
      growthPct: 128.1,
      viewsGained30d: 72915955,
      channelCreatedAt: "2025-04-12",
    },
    {
      channelName: "Timeunheard",
      channelUrl: "https://www.youtube.com/channel/UCODZmz_Ve3DIN5_7A7OLXJw",
      topic: "Music, Pop music",
      subscribers: 55800,
      subsGained30d: 28100,
      growthPct: 101.4,
      viewsGained30d: 220285,
      channelCreatedAt: "2025-12-29",
    },
    {
      channelName: "Bhai Manpreet Singh Ji Kanpuri - Topic",
      channelUrl: "https://www.youtube.com/channel/UCOcjUT32hH7XsRZsgv35Yyw",
      topic: "Music, Music of Asia",
      subscribers: 55600,
      subsGained30d: 28000,
      growthPct: 101.4,
      viewsGained30d: 1071499,
      channelCreatedAt: "2022-07-11",
    },
    {
      channelName: "Dan Mylor",
      channelUrl: "https://www.youtube.com/channel/UClxlb8FBD-t4zaHlk411uKw",
      topic: "Electronic music, Music",
      subscribers: 103000,
      subsGained30d: 50000,
      growthPct: 94.3,
      viewsGained30d: 632981,
      channelCreatedAt: "2021-05-26",
    },
    {
      channelName: "People\\'s Vybe",
      channelUrl: "https://www.youtube.com/channel/UCOo1MTcMkhYWI6hEOIh9d0g",
      topic: "Music, Music of Asia",
      subscribers: 61600,
      subsGained30d: 28600,
      growthPct: 86.7,
      viewsGained30d: 33109408,
      channelCreatedAt: "2021-02-03",
    },
    {
      channelName: "CIRCOLOCO",
      channelUrl: "https://www.youtube.com/channel/UCanV1p6ynx_FzdsraKLousQ",
      topic: "Music, Electronic music",
      subscribers: 129000,
      subsGained30d: 58600,
      growthPct: 83.2,
      viewsGained30d: 1283347,
      channelCreatedAt: "2013-05-14",
    },
    {
      channelName: "Yamaha Music India",
      channelUrl: "https://www.youtube.com/channel/UCOr0lS8PGv0dKl0QldyKkqw",
      topic: "Music, Rock music",
      subscribers: 62500,
      subsGained30d: 28200,
      growthPct: 82.2,
      viewsGained30d: 2613739,
      channelCreatedAt: "2011-07-27",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Ambient Interludes",
    note: "a newer channel (created 2025) that gained 80,500 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
