// Single source of truth for the YouTube Food channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Food" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

export interface ChannelFact {
  channelName: string;
  channelUrl: string;
  topic: string; // YouTube's own topic classification (Wikipedia-based topicCategories), not Vira's
  subscribers: number;
  subsGained30d: number;
  growthPct: number; // subsGained30d / (subscribers - subsGained30d) * 100, rounded to 1 decimal
  viewsGained30d: number;
  channelCreatedAt: string | null; // date, null if unknown
}

export interface YoutubeNicheReport {
  niche: string;
  region: string;
  dataAsOf: string; // date, latest_stat_date backing the numbers
  updatedAt: string; // date, page "last updated"
  channels: ChannelFact[];
  methodologyNote: string;
  highlightChannel: {
    channelName: string;
    note: string;
  };
}

export const youtubeFoodReport: YoutubeNicheReport = {
  niche: "Food",
  region: "global",
  dataAsOf: "2026-10-05",
  updatedAt: "2026-10-05",
  channels: [
    {
      channelName: "Be Smart With Palak",
      channelUrl: "https://www.youtube.com/channel/UCqWijlzf_ulS1O3Bd7WEb0Q",
      topic: "Food, Lifestyle (sociology)",
      subscribers: 184000,
      subsGained30d: 119500,
      growthPct: 185.3,
      viewsGained30d: 18063603,
      channelCreatedAt: "2016-12-12",
    },
    {
      channelName: "Chalokuchkhaye",
      channelUrl: "https://www.youtube.com/channel/UCf0zagriCNxAp57yl5cY6BA",
      topic: "Food, Lifestyle (sociology)",
      subscribers: 56800,
      subsGained30d: 35400,
      growthPct: 165.4,
      viewsGained30d: 41145753,
      channelCreatedAt: "2023-05-03",
    },
    {
      channelName: "Hana Yoshida",
      channelUrl: "https://www.youtube.com/channel/UCdmpd39sAYyMAIY8RjrjXcA",
      topic: "Food, Lifestyle (sociology)",
      subscribers: 55900,
      subsGained30d: 33700,
      growthPct: 151.8,
      viewsGained30d: 2920991,
      channelCreatedAt: "2026-08-14",
    },
    {
      channelName: "Foodies by Tanya",
      channelUrl: "https://www.youtube.com/channel/UCOu4dY39ysAMm6zdPnHo-ew",
      topic: "Food, Lifestyle (sociology)",
      subscribers: 131000,
      subsGained30d: 77600,
      growthPct: 145.3,
      viewsGained30d: 33552549,
      channelCreatedAt: "2022-02-14",
    },
    {
      channelName: "Bertha Cooks",
      channelUrl: "https://www.youtube.com/channel/UCEpgRWDUGVu7UaYc7fB1Idw",
      topic: "Lifestyle (sociology), Food",
      subscribers: 168000,
      subsGained30d: 94600,
      growthPct: 128.9,
      viewsGained30d: 5376253,
      channelCreatedAt: "2019-05-25",
    },
    {
      channelName: "Vitality Desserts",
      channelUrl: "https://www.youtube.com/channel/UC4_XQgzwH0Xbt0ld4cn4xPQ",
      topic: "Food, Lifestyle (sociology)",
      subscribers: 69500,
      subsGained30d: 39100,
      growthPct: 128.6,
      viewsGained30d: 9569732,
      channelCreatedAt: "2026-02-03",
    },
    {
      channelName: "Tèo Tên Tây",
      channelUrl: "https://www.youtube.com/channel/UCVsIYblFfN78t9225j2Cl0g",
      topic: "Lifestyle (sociology), Food",
      subscribers: 240000,
      subsGained30d: 130000,
      growthPct: 118.2,
      viewsGained30d: 15007582,
      channelCreatedAt: "2023-10-07",
    },
    {
      channelName: "Asjad Tech",
      channelUrl: "https://www.youtube.com/channel/UCeZLS6OQx1N4UXz-lukFbIA",
      topic: "Lifestyle (sociology), Food",
      subscribers: 83100,
      subsGained30d: 44700,
      growthPct: 116.4,
      viewsGained30d: 29858927,
      channelCreatedAt: "2024-02-20",
    },
    {
      channelName: "Smruti\\'s animation",
      channelUrl: "https://www.youtube.com/channel/UCk_KaP6mkY14RGE-CJ_c5Yg",
      topic: "Food, Lifestyle (sociology)",
      subscribers: 50300,
      subsGained30d: 26400,
      growthPct: 110.5,
      viewsGained30d: 12074925,
      channelCreatedAt: "2021-05-30",
    },
    {
      channelName: "LouLouexplores",
      channelUrl: "https://www.youtube.com/channel/UCLmISWTaKC5JTFEdajIxrgw",
      topic: "Food, Lifestyle (sociology)",
      subscribers: 54100,
      subsGained30d: 26900,
      growthPct: 98.9,
      viewsGained30d: 8546290,
      channelCreatedAt: "2018-10-21",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Be Smart With Palak",
    note: "an established channel (created 2016) that gained 119,500 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
