// Single source of truth for the YouTube Electronic music channel growth report
// (part of Music).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Electronic music" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeElectronicMusicSubReport: YoutubeSubgenreReport = {
  subgenre: "Electronic music",
  parentCategory: "Music",
  parentSlug: "music",
  region: "global",
  dataAsOf: "2026-10-10",
  updatedAt: "2026-10-10",
  channels: [
    {
      channelName: "Ambient Interludes",
      channelUrl: "https://www.youtube.com/channel/UC5FZd7doj7I-nc8EkPHM-EA",
      topic: "Music, Electronic music",
      subscribers: 112000,
      subsGained30d: 75100,
      growthPct: 203.5,
      viewsGained30d: 475329,
      channelCreatedAt: "2025-11-28",
    },
    {
      channelName: "Dan Mylor",
      channelUrl: "https://www.youtube.com/channel/UClxlb8FBD-t4zaHlk411uKw",
      topic: "Music, Electronic music",
      subscribers: 103000,
      subsGained30d: 47800,
      growthPct: 86.6,
      viewsGained30d: 272256,
      channelCreatedAt: "2021-05-26",
    },
    {
      channelName: "CIRCOLOCO",
      channelUrl: "https://www.youtube.com/channel/UCanV1p6ynx_FzdsraKLousQ",
      topic: "Music, Electronic music",
      subscribers: 133000,
      subsGained30d: 59700,
      growthPct: 81.4,
      viewsGained30d: 1255601,
      channelCreatedAt: "2013-05-14",
    },
    {
      channelName: "Charles B",
      channelUrl: "https://www.youtube.com/channel/UCziJ6x_qx23rrzQDDJuqbqA",
      topic: "Music, Electronic music",
      subscribers: 118000,
      subsGained30d: 49900,
      growthPct: 73.3,
      viewsGained30d: 849402,
      channelCreatedAt: "2014-05-25",
    },
    {
      channelName: "RAVNIR",
      channelUrl: "https://www.youtube.com/channel/UC0iRV7ElaGmZ70SHnRruL5A",
      topic: "Electronic music, Music",
      subscribers: 208000,
      subsGained30d: 87000,
      growthPct: 71.9,
      viewsGained30d: 49518812,
      channelCreatedAt: "2026-01-23",
    },
    {
      channelName: "Late Hours | Relaxing Piano Music",
      channelUrl: "https://www.youtube.com/channel/UCg5L6P3E5MN8uZidiUg2dqA",
      topic: "Music, Electronic music",
      subscribers: 113000,
      subsGained30d: 34100,
      growthPct: 43.2,
      viewsGained30d: 496358,
      channelCreatedAt: "2025-12-30",
    },
    {
      channelName: "Void-Sign",
      channelUrl: "https://www.youtube.com/channel/UCU_ayeZkMFYqbq4JXrSlK9w",
      topic: "Electronic music, Music",
      subscribers: 151000,
      subsGained30d: 44000,
      growthPct: 41.1,
      viewsGained30d: 1179266,
      channelCreatedAt: "2013-11-01",
    },
    {
      channelName: "tienanh109 prod.",
      channelUrl: "https://www.youtube.com/channel/UCDPnqNYNexqlaKTgC7YW-dw",
      topic: "Electronic music, Music",
      subscribers: 64500,
      subsGained30d: 17500,
      growthPct: 37.2,
      viewsGained30d: 1242591,
      channelCreatedAt: "2025-09-25",
    },
    {
      channelName: "Dhruv Vajasi",
      channelUrl: "https://www.youtube.com/channel/UCYtRGkIa_tUHonysqYPIdUQ",
      topic: "Electronic music, Music",
      subscribers: 136000,
      subsGained30d: 36000,
      growthPct: 36.0,
      viewsGained30d: 9721504,
      channelCreatedAt: "2021-06-08",
    },
    {
      channelName: "Aurumn",
      channelUrl: "https://www.youtube.com/channel/UCBvXET4zoj1uQErg3tq6upQ",
      topic: "Electronic music, Music",
      subscribers: 59400,
      subsGained30d: 14200,
      growthPct: 31.4,
      viewsGained30d: 132274,
      channelCreatedAt: "2006-06-14",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Music niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Ambient Interludes",
    note: "a newer channel (created 2025) that gained 75,100 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
