// Single source of truth for the YouTube Baseball channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Baseball" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeBaseballReport: YoutubeNicheReport = {
  niche: "Baseball",
  region: "global",
  dataAsOf: "2026-10-06",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "ALL THE SMOKE BASEBALL",
      channelUrl: "https://www.youtube.com/channel/UCJA_EalIDqNzFTzmGUSfQ_Q",
      topic: "Sport, Baseball",
      subscribers: 86300,
      subsGained30d: 16300,
      growthPct: 23.3,
      viewsGained30d: 27874738,
      channelCreatedAt: "2026-03-06",
    },
    {
      channelName: "Campeones TV",
      channelUrl: "https://www.youtube.com/channel/UC-7dXG_EAx8x3Jj3S_HVITg",
      topic: "Sport, Baseball",
      subscribers: 61700,
      subsGained30d: 9200,
      growthPct: 17.5,
      viewsGained30d: 8000985,
      channelCreatedAt: "2025-02-28",
    },
    {
      channelName: "Shortstop",
      channelUrl: "https://www.youtube.com/channel/UCBIFuA0WZ1DSjA3ojcHybjA",
      topic: "Sport, Baseball",
      subscribers: 54100,
      subsGained30d: 4900,
      growthPct: 10.0,
      viewsGained30d: 29994062,
      channelCreatedAt: "2023-10-31",
    },
    {
      channelName: "Andros Nisha",
      channelUrl: "https://www.youtube.com/channel/UCLqdu-X-NmnrVCZc3bYAVGg",
      topic: "Baseball, Sport",
      subscribers: 97900,
      subsGained30d: 6100,
      growthPct: 6.6,
      viewsGained30d: 8341692,
      channelCreatedAt: "2025-08-13",
    },
    {
      channelName: "Podcast Doesn\\'t Exist",
      channelUrl: "https://www.youtube.com/channel/UCfsocaCHgELMJ2udpwr3SYA",
      topic: "Baseball, Sport",
      subscribers: 96300,
      subsGained30d: 5200,
      growthPct: 5.7,
      viewsGained30d: 3325406,
      channelCreatedAt: "2025-03-21",
    },
    {
      channelName: "ヒーローズTV【大谷翔平】",
      channelUrl: "https://www.youtube.com/channel/UCUi2bvxdlvitK-vcNWSOaYQ",
      topic: "Baseball, Sport",
      subscribers: 62300,
      subsGained30d: 3300,
      growthPct: 5.6,
      viewsGained30d: 32834053,
      channelCreatedAt: "2025-01-07",
    },
    {
      channelName: "LAスウィングショー",
      channelUrl: "https://www.youtube.com/channel/UCf88aVOVU6X3JrEpUL5m-QA",
      topic: "Sport, Baseball",
      subscribers: 52200,
      subsGained30d: 2600,
      growthPct: 5.2,
      viewsGained30d: 2720500,
      channelCreatedAt: "2025-11-28",
    },
    {
      channelName: "Perfect Game Baseball",
      channelUrl: "https://www.youtube.com/channel/UCj5pdBYmmElLAAFjU8Dbb2g",
      topic: "Sport, Baseball",
      subscribers: 280000,
      subsGained30d: 11000,
      growthPct: 4.1,
      viewsGained30d: 1398942,
      channelCreatedAt: "2011-07-19",
    },
    {
      channelName: "WIN Reality",
      channelUrl: "https://www.youtube.com/channel/UCKf9_SBioF8T2ezi8WJ5u4g",
      topic: "Baseball, Sport",
      subscribers: 54100,
      subsGained30d: 2000,
      growthPct: 3.8,
      viewsGained30d: 8584046,
      channelCreatedAt: "2020-01-10",
    },
    {
      channelName: "getwin_sport",
      channelUrl: "https://www.youtube.com/channel/UClY4BZ_s9l0Ak11piSi5QMA",
      topic: "Baseball, Sport",
      subscribers: 90000,
      subsGained30d: 3100,
      growthPct: 3.6,
      viewsGained30d: 4495816,
      channelCreatedAt: "2014-08-29",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "ALL THE SMOKE BASEBALL",
    note: "a newer channel (created 2026) that gained 16,300 subscribers in 30 days, a 23.3% increase over its subscriber base a month earlier",
  },
};
