// Single source of truth for the YouTube Action-adventure game channel growth report
// (part of Video game culture).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Action-adventure game" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeActionAdventureGameSubReport: YoutubeSubgenreReport = {
  subgenre: "Action-adventure game",
  parentCategory: "Video game culture",
  parentSlug: "gaming",
  region: "global",
  dataAsOf: "2026-10-09",
  updatedAt: "2026-10-09",
  channels: [
    {
      channelName: "Adagih",
      channelUrl: "https://www.youtube.com/channel/UCqvH9ExvEpP0-Ut1NlKdPUA",
      topic: "Action-adventure game, Video game culture",
      subscribers: 53300,
      subsGained30d: 15800,
      growthPct: 42.1,
      viewsGained30d: 1691075,
      channelCreatedAt: "2015-11-23",
    },
    {
      channelName: "FunyBroBoss",
      channelUrl: "https://www.youtube.com/channel/UC4Pvae0DGnb7LZY-uX1OpIQ",
      topic: "Action-adventure game, Video game culture",
      subscribers: 56700,
      subsGained30d: 11200,
      growthPct: 24.6,
      viewsGained30d: 35139748,
      channelCreatedAt: "2026-02-02",
    },
    {
      channelName: "AllameenxVerse",
      channelUrl: "https://www.youtube.com/channel/UCf-eqa9nVwgNQLNzpNOhdgA",
      topic: "Video game culture, Action-adventure game",
      subscribers: 205000,
      subsGained30d: 35000,
      growthPct: 20.6,
      viewsGained30d: 3886506,
      channelCreatedAt: "2024-09-30",
    },
    {
      channelName: "T2F JELLY95",
      channelUrl: "https://www.youtube.com/channel/UCtp_gZUmgQfceEjuDOw-vZQ",
      topic: "Action-adventure game, Video game culture",
      subscribers: 1020000,
      subsGained30d: 169000,
      growthPct: 19.9,
      viewsGained30d: 100840792,
      channelCreatedAt: "2026-02-06",
    },
    {
      channelName: "AremBlox",
      channelUrl: "https://www.youtube.com/channel/UCd5bJuHuT82bPx7abFBKBIg",
      topic: "Video game culture, Action-adventure game",
      subscribers: 71800,
      subsGained30d: 10600,
      growthPct: 17.3,
      viewsGained30d: 5756965,
      channelCreatedAt: "2014-05-25",
    },
    {
      channelName: "SoulScape",
      channelUrl: "https://www.youtube.com/channel/UCiSpI2ODKE_AEoH4bgQPYTA",
      topic: "Action-adventure game, Video game culture",
      subscribers: 54300,
      subsGained30d: 7100,
      growthPct: 15.0,
      viewsGained30d: 10132199,
      channelCreatedAt: "2025-03-24",
    },
    {
      channelName: "Mehmet Bey",
      channelUrl: "https://www.youtube.com/channel/UCXuj_hvYOKrcILNIH_bOOeA",
      topic: "Action-adventure game, Video game culture",
      subscribers: 147000,
      subsGained30d: 19000,
      growthPct: 14.8,
      viewsGained30d: 3356397,
      channelCreatedAt: "2021-06-12",
    },
    {
      channelName: "JMB GAMERZ PRO",
      channelUrl: "https://www.youtube.com/channel/UCm6HzuJlEZL2I7LSqkVfKig",
      topic: "Video game culture, Action-adventure game",
      subscribers: 160000,
      subsGained30d: 18000,
      growthPct: 12.7,
      viewsGained30d: 35570962,
      channelCreatedAt: "2026-02-01",
    },
    {
      channelName: "Angga Sadulur",
      channelUrl: "https://www.youtube.com/channel/UC6VAV2tUfrBSeb3r9g6HgLw",
      topic: "Action-adventure game, Video game culture",
      subscribers: 50300,
      subsGained30d: 5500,
      growthPct: 12.3,
      viewsGained30d: 5077588,
      channelCreatedAt: "2014-01-15",
    },
    {
      channelName: "TRIMGAMES",
      channelUrl: "https://www.youtube.com/channel/UCUyD0yZgYhJF3omJZG8JeXQ",
      topic: "Action-adventure game, Video game culture",
      subscribers: 79400,
      subsGained30d: 6700,
      growthPct: 9.2,
      viewsGained30d: 4682125,
      channelCreatedAt: "2021-02-13",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Video game culture niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Adagih",
    note: "an established channel (created 2015) that gained 15,800 subscribers in 30 days, a 42.1% increase over its subscriber base a month earlier",
  },
};
