// Single source of truth for the YouTube Music of Asia channel growth report
// (part of Music).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Music of Asia" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeMusicOfAsiaSubReport: YoutubeSubgenreReport = {
  subgenre: "Music of Asia",
  parentCategory: "Music",
  parentSlug: "music",
  region: "global",
  dataAsOf: "2026-10-07",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Sandhu GS World",
      channelUrl: "https://www.youtube.com/channel/UCOKFsYrHT_w9UUwzmPEkvOA",
      topic: "Music, Music of Asia",
      subscribers: 63300,
      subsGained30d: 37600,
      growthPct: 146.3,
      viewsGained30d: 33364519,
      channelCreatedAt: "2020-09-26",
    },
    {
      channelName: "Sea Beauty",
      channelUrl: "https://www.youtube.com/channel/UC6T-hLWsv9bJpcXStd1OUaw",
      topic: "Lifestyle (sociology), Music of Asia",
      subscribers: 102000,
      subsGained30d: 57800,
      growthPct: 130.8,
      viewsGained30d: 72450315,
      channelCreatedAt: "2025-04-12",
    },
    {
      channelName: "Bhai Manpreet Singh Ji Kanpuri - Topic",
      channelUrl: "https://www.youtube.com/channel/UCOcjUT32hH7XsRZsgv35Yyw",
      topic: "Music, Music of Asia",
      subscribers: 55600,
      subsGained30d: 28000,
      growthPct: 101.4,
      viewsGained30d: 1081455,
      channelCreatedAt: "2022-07-11",
    },
    {
      channelName: "People\\'s Vybe",
      channelUrl: "https://www.youtube.com/channel/UCOo1MTcMkhYWI6hEOIh9d0g",
      topic: "Music of Asia, Music",
      subscribers: 60700,
      subsGained30d: 29000,
      growthPct: 91.5,
      viewsGained30d: 32674062,
      channelCreatedAt: "2021-02-03",
    },
    {
      channelName: "Dudi Dudi Rhymes TV",
      channelUrl: "https://www.youtube.com/channel/UCzVCTwk2rSB4yxVstXqF2jg",
      topic: "Music of Asia, Music",
      subscribers: 104000,
      subsGained30d: 46600,
      growthPct: 81.2,
      viewsGained30d: 16733555,
      channelCreatedAt: "2025-05-30",
    },
    {
      channelName: "Andrew Kishor",
      channelUrl: "https://www.youtube.com/channel/UC-nqlUyT2jjHPKvMK-4mPDA",
      topic: "Music of Asia, Music",
      subscribers: 118000,
      subsGained30d: 47500,
      growthPct: 67.4,
      viewsGained30d: 4005584,
      channelCreatedAt: "2023-01-13",
    },
    {
      channelName: "Digital Gaana Distribution - Nonstop Juke Box",
      channelUrl: "https://www.youtube.com/channel/UCfQpO0qWmFpVapsqOCJPURQ",
      topic: "Music of Asia, Music",
      subscribers: 101000,
      subsGained30d: 40000,
      growthPct: 65.6,
      viewsGained30d: 5573523,
      channelCreatedAt: "2016-04-14",
    },
    {
      channelName: "Samayu Travel",
      channelUrl: "https://www.youtube.com/channel/UC_-gxz-VQG9C0dzeSVNwyhg",
      topic: "Music, Music of Asia",
      subscribers: 58400,
      subsGained30d: 22800,
      growthPct: 64.0,
      viewsGained30d: 17961877,
      channelCreatedAt: "2013-07-25",
    },
    {
      channelName: "Nihar Shembekar",
      channelUrl: "https://www.youtube.com/channel/UCXActGOdmsuzFQgKV_D7TeQ",
      topic: "Music, Music of Asia",
      subscribers: 71000,
      subsGained30d: 27600,
      growthPct: 63.6,
      viewsGained30d: 12677710,
      channelCreatedAt: "2013-08-26",
    },
    {
      channelName: "MrM Adda",
      channelUrl: "https://www.youtube.com/channel/UCPQrb9p5uhIAKZi6DWh0oaQ",
      topic: "Music, Music of Asia",
      subscribers: 128000,
      subsGained30d: 48800,
      growthPct: 61.6,
      viewsGained30d: 20964491,
      channelCreatedAt: "2021-08-02",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Music niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Sandhu GS World",
    note: "an established channel (created 2020) that gained 37,600 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
