// Single source of truth for the YouTube Society channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Society" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeSocietyReport: YoutubeNicheReport = {
  niche: "Society",
  region: "global",
  dataAsOf: "2026-10-08",
  updatedAt: "2026-10-08",
  channels: [
    {
      channelName: "Lecciones De Sabios",
      channelUrl: "https://www.youtube.com/channel/UCnKM6eWPSHKhA65L4HOI1ZQ",
      topic: "Society, Religion",
      subscribers: 208000,
      subsGained30d: 173400,
      growthPct: 501.2,
      viewsGained30d: 3030358,
      channelCreatedAt: "2025-05-16",
    },
    {
      channelName: "Amira Arora & Aryaan Arora",
      channelUrl: "https://www.youtube.com/channel/UCzuo1FFstOnPOTirMfD0tjg",
      topic: "Religion, Society",
      subscribers: 1220000,
      subsGained30d: 918000,
      growthPct: 304.0,
      viewsGained30d: 13432028,
      channelCreatedAt: "2023-06-03",
    },
    {
      channelName: "TOXIC ROSTER",
      channelUrl: "https://www.youtube.com/channel/UCDHz3eq0FIFHGomcEE2r1pg",
      topic: "Religion, Society",
      subscribers: 71500,
      subsGained30d: 47100,
      growthPct: 193.0,
      viewsGained30d: 7288670,
      channelCreatedAt: "2023-01-16",
    },
    {
      channelName: "제게 용기를 주세요.",
      channelUrl: "https://www.youtube.com/channel/UC9UlH4_AroLjzER6e7nPxmg",
      topic: "Society",
      subscribers: 59000,
      subsGained30d: 35800,
      growthPct: 154.3,
      viewsGained30d: 10954608,
      channelCreatedAt: "2022-12-11",
    },
    {
      channelName: "Reimer Thoughts by Erich Reimer",
      channelUrl: "https://www.youtube.com/channel/UCaO4aArN90oLLWpiu-1zfUw",
      topic: "Politics, Society",
      subscribers: 112000,
      subsGained30d: 64200,
      growthPct: 134.3,
      viewsGained30d: 2432925,
      channelCreatedAt: "2025-06-01",
    },
    {
      channelName: "Marco Romero",
      channelUrl: "https://www.youtube.com/channel/UCcFfkvEIu2Nyj8zz0-kY94w",
      topic: "Society, Knowledge",
      subscribers: 52800,
      subsGained30d: 29300,
      growthPct: 124.7,
      viewsGained30d: 1062,
      channelCreatedAt: "2025-12-03",
    },
    {
      channelName: "HANS",
      channelUrl: "https://www.youtube.com/channel/UChlBdEx0pwDXpG13VSxe-KQ",
      topic: "Society, Politics",
      subscribers: 75000,
      subsGained30d: 40700,
      growthPct: 118.7,
      viewsGained30d: 3759011,
      channelCreatedAt: "2018-01-09",
    },
    {
      channelName: "Malwa Abhitak मालवा अभीतक (सबसे तेज खबरे)",
      channelUrl: "https://www.youtube.com/channel/UCZF8JMVuSpQVJwceqhyQB4A",
      topic: "Society, Politics",
      subscribers: 51900,
      subsGained30d: 27900,
      growthPct: 116.3,
      viewsGained30d: 12514416,
      channelCreatedAt: "2014-01-25",
    },
    {
      channelName: "Smart Jyotish",
      channelUrl: "https://www.youtube.com/channel/UC-ZvaMJs9osz9Cf56zC5UJA",
      topic: "Religion, Society",
      subscribers: 50000,
      subsGained30d: 26700,
      growthPct: 114.6,
      viewsGained30d: 13882142,
      channelCreatedAt: "2026-03-26",
    },
    {
      channelName: "Naju Mary",
      channelUrl: "https://www.youtube.com/channel/UC3wAxdCmGkaUmMga8x0pxKQ",
      topic: "Religion, Society",
      subscribers: 67100,
      subsGained30d: 34700,
      growthPct: 107.1,
      viewsGained30d: 1350020,
      channelCreatedAt: "2013-10-14",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Lecciones De Sabios",
    note: "a newer channel (created 2025) that gained 173,400 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
