// Single source of truth for the YouTube Sport channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Sport" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeSportsReport: YoutubeNicheReport = {
  niche: "Sport",
  region: "global",
  dataAsOf: "2026-10-08",
  updatedAt: "2026-10-08",
  channels: [
    {
      channelName: "Artex",
      channelUrl: "https://www.youtube.com/channel/UCsntXZKABoxqvWmdwDxdONA",
      topic: "Sport, Association football",
      subscribers: 157000,
      subsGained30d: 119700,
      growthPct: 320.9,
      viewsGained30d: 40045878,
      channelCreatedAt: "2019-08-31",
    },
    {
      channelName: "Crest Count",
      channelUrl: "https://www.youtube.com/channel/UCZkxJCXJ4yYM8YX3ogXX5pQ",
      topic: "Sport, Entertainment",
      subscribers: 124000,
      subsGained30d: 74300,
      growthPct: 149.5,
      viewsGained30d: 2212848,
      channelCreatedAt: "2025-11-18",
    },
    {
      channelName: "SHORTS LM",
      channelUrl: "https://www.youtube.com/channel/UCixGm7bCi8jawA4XRdbbbQA",
      topic: "Sport, Association football",
      subscribers: 76400,
      subsGained30d: 35200,
      growthPct: 85.4,
      viewsGained30d: 114384161,
      channelCreatedAt: "2026-01-16",
    },
    {
      channelName: "KING PLAYER",
      channelUrl: "https://www.youtube.com/channel/UCrhzIFmFwvb9Xegt_q561aw",
      topic: "Sports game, Video game culture",
      subscribers: 117000,
      subsGained30d: 52100,
      growthPct: 80.3,
      viewsGained30d: 40783231,
      channelCreatedAt: "2020-02-01",
    },
    {
      channelName: "R PES GAMING",
      channelUrl: "https://www.youtube.com/channel/UC0sKozOrglalgTLlsne6BlQ",
      topic: "Sports game, Video game culture",
      subscribers: 101000,
      subsGained30d: 44100,
      growthPct: 77.5,
      viewsGained30d: 3085847,
      channelCreatedAt: "2020-05-16",
    },
    {
      channelName: "GD KAI YT",
      channelUrl: "https://www.youtube.com/channel/UC5h_Q7VlX2GpnN7Zl7sYS3g",
      topic: "Entertainment, Sport",
      subscribers: 105000,
      subsGained30d: 44800,
      growthPct: 74.4,
      viewsGained30d: 7007506,
      channelCreatedAt: "2024-11-21",
    },
    {
      channelName: "football ⚽",
      channelUrl: "https://www.youtube.com/channel/UCH8kjkJHvxPcNjO01hok-OQ",
      topic: "Association football, Sport",
      subscribers: 52400,
      subsGained30d: 20400,
      growthPct: 63.7,
      viewsGained30d: 10134845,
      channelCreatedAt: "2025-08-14",
    },
    {
      channelName: "yasinogabuga",
      channelUrl: "https://www.youtube.com/channel/UCb0L1jbQytUliLqX7WW62-g",
      topic: "Association football, Sport",
      subscribers: 75700,
      subsGained30d: 28600,
      growthPct: 60.7,
      viewsGained30d: 15041612,
      channelCreatedAt: "2020-08-21",
    },
    {
      channelName: "Full.90",
      channelUrl: "https://www.youtube.com/channel/UCyLJnUsaxp8O9eH8-dWgNeg",
      topic: "Association football, Sport",
      subscribers: 64800,
      subsGained30d: 23500,
      growthPct: 56.9,
      viewsGained30d: 23838272,
      channelCreatedAt: "2025-07-23",
    },
    {
      channelName: "Nexxo Recaps",
      channelUrl: "https://www.youtube.com/channel/UCY-2QRPXfHfcDDugOUr7A8Q",
      topic: "Entertainment, Sport",
      subscribers: 738000,
      subsGained30d: 263000,
      growthPct: 55.4,
      viewsGained30d: 499329821,
      channelCreatedAt: "2026-01-10",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Artex",
    note: "an established channel (created 2019) that gained 119,700 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
