// Single source of truth for the YouTube Classical music channel growth report
// (part of Music).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Classical music" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeClassicalMusicSubReport: YoutubeSubgenreReport = {
  subgenre: "Classical music",
  parentCategory: "Music",
  parentSlug: "music",
  region: "global",
  dataAsOf: "2026-10-07",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Poviolinist",
      channelUrl: "https://www.youtube.com/channel/UCMXg1cFPK2VkGfomkWdqBOA",
      topic: "Classical music, Music",
      subscribers: 589000,
      subsGained30d: 119000,
      growthPct: 25.3,
      viewsGained30d: 41376937,
      channelCreatedAt: "2022-02-23",
    },
    {
      channelName: "GoldenDöngü",
      channelUrl: "https://www.youtube.com/channel/UC2zjxGqGJliyQBoJ54yscqg",
      topic: "Classical music, Music",
      subscribers: 62100,
      subsGained30d: 8500,
      growthPct: 15.9,
      viewsGained30d: 5785630,
      channelCreatedAt: "2006-10-01",
    },
    {
      channelName: "ClassicalMusic Playlist",
      channelUrl: "https://www.youtube.com/channel/UCOfm8A5g8mn1TESPt7IM_KA",
      topic: "Classical music, Music",
      subscribers: 71400,
      subsGained30d: 8700,
      growthPct: 13.9,
      viewsGained30d: 2422369,
      channelCreatedAt: "2026-04-22",
    },
    {
      channelName: "Danlu",
      channelUrl: "https://www.youtube.com/channel/UCXBQ7CBw0_-__kZpo9KGKxg",
      topic: "Classical music, Music",
      subscribers: 308000,
      subsGained30d: 34000,
      growthPct: 12.4,
      viewsGained30d: 2639962,
      channelCreatedAt: "2020-08-04",
    },
    {
      channelName: "Mary Frances",
      channelUrl: "https://www.youtube.com/channel/UCAiHmoXsOyUgQ7eqVE0POIA",
      topic: "Classical music, Music",
      subscribers: 55000,
      subsGained30d: 5200,
      growthPct: 10.4,
      viewsGained30d: 5826219,
      channelCreatedAt: "2024-03-30",
    },
    {
      channelName: "Juan Arenosa",
      channelUrl: "https://www.youtube.com/channel/UC7T3t3WgN8sS3R2RIrnGWIw",
      topic: "Music, Classical music",
      subscribers: 110000,
      subsGained30d: 10000,
      growthPct: 10.0,
      viewsGained30d: 5655766,
      channelCreatedAt: "2018-01-17",
    },
    {
      channelName: "Marie Leloup ( Jouer du Violon )",
      channelUrl: "https://www.youtube.com/channel/UCb4kS20Xy3pyxU9LURvEc2g",
      topic: "Music, Classical music",
      subscribers: 79500,
      subsGained30d: 5700,
      growthPct: 7.7,
      viewsGained30d: 287803,
      channelCreatedAt: "2018-12-22",
    },
    {
      channelName: "Zade Dirani",
      channelUrl: "https://www.youtube.com/channel/UCTXlhnrVPzP-Zn1wx34PsoQ",
      topic: "Classical music, Music",
      subscribers: 361000,
      subsGained30d: 24000,
      growthPct: 7.1,
      viewsGained30d: 2346917,
      channelCreatedAt: "2009-10-01",
    },
    {
      channelName: "배쌤에 미쳐 Beseme Micho",
      channelUrl: "https://www.youtube.com/channel/UCwy_2MZ9VVZwfvchlHdOsRQ",
      topic: "Music, Classical music",
      subscribers: 86500,
      subsGained30d: 5300,
      growthPct: 6.5,
      viewsGained30d: 5870336,
      channelCreatedAt: "2017-10-02",
    },
    {
      channelName: "David Grumel",
      channelUrl: "https://www.youtube.com/channel/UCS4NqiR13_KMlNqE9G7AIVQ",
      topic: "Classical music, Music",
      subscribers: 55400,
      subsGained30d: 3200,
      growthPct: 6.1,
      viewsGained30d: 113942,
      channelCreatedAt: "2012-02-16",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Music niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Poviolinist",
    note: "an established channel (created 2022) that gained 119,000 subscribers in 30 days, a 25.3% increase over its subscriber base a month earlier",
  },
};
