// Single source of truth for the YouTube Food channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Food" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeFoodReport: YoutubeNicheReport = {
  niche: "Food",
  region: "global",
  dataAsOf: "2026-10-06",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Be Smart With Palak",
      channelUrl: "https://www.youtube.com/channel/UCqWijlzf_ulS1O3Bd7WEb0Q",
      topic: "Lifestyle (sociology), Food",
      subscribers: 185000,
      subsGained30d: 120500,
      growthPct: 186.8,
      viewsGained30d: 18310816,
      channelCreatedAt: "2016-12-12",
    },
    {
      channelName: "Chalokuchkhaye",
      channelUrl: "https://www.youtube.com/channel/UCf0zagriCNxAp57yl5cY6BA",
      topic: "Lifestyle (sociology), Food",
      subscribers: 58000,
      subsGained30d: 36200,
      growthPct: 166.1,
      viewsGained30d: 41470716,
      channelCreatedAt: "2023-05-03",
    },
    {
      channelName: "Hana Yoshida",
      channelUrl: "https://www.youtube.com/channel/UCdmpd39sAYyMAIY8RjrjXcA",
      topic: "Lifestyle (sociology), Food",
      subscribers: 56500,
      subsGained30d: 33400,
      growthPct: 144.6,
      viewsGained30d: 2895124,
      channelCreatedAt: "2026-08-14",
    },
    {
      channelName: "Foodies by Tanya",
      channelUrl: "https://www.youtube.com/channel/UCOu4dY39ysAMm6zdPnHo-ew",
      topic: "Lifestyle (sociology), Food",
      subscribers: 133000,
      subsGained30d: 75600,
      growthPct: 131.7,
      viewsGained30d: 32590825,
      channelCreatedAt: "2022-02-14",
    },
    {
      channelName: "Vitality Desserts",
      channelUrl: "https://www.youtube.com/channel/UC4_XQgzwH0Xbt0ld4cn4xPQ",
      topic: "Lifestyle (sociology), Food",
      subscribers: 70000,
      subsGained30d: 39600,
      growthPct: 130.3,
      viewsGained30d: 9656178,
      channelCreatedAt: "2026-02-03",
    },
    {
      channelName: "Smruti\\'s animation",
      channelUrl: "https://www.youtube.com/channel/UCk_KaP6mkY14RGE-CJ_c5Yg",
      topic: "Food, Lifestyle (sociology)",
      subscribers: 51500,
      subsGained30d: 26900,
      growthPct: 109.3,
      viewsGained30d: 12257157,
      channelCreatedAt: "2021-05-30",
    },
    {
      channelName: "Tèo Tên Tây",
      channelUrl: "https://www.youtube.com/channel/UCVsIYblFfN78t9225j2Cl0g",
      topic: "Food, Lifestyle (sociology)",
      subscribers: 249000,
      subsGained30d: 126000,
      growthPct: 102.4,
      viewsGained30d: 15166236,
      channelCreatedAt: "2023-10-07",
    },
    {
      channelName: "LouLouexplores",
      channelUrl: "https://www.youtube.com/channel/UCLmISWTaKC5JTFEdajIxrgw",
      topic: "Food, Lifestyle (sociology)",
      subscribers: 54300,
      subsGained30d: 27100,
      growthPct: 99.6,
      viewsGained30d: 8608434,
      channelCreatedAt: "2018-10-21",
    },
    {
      channelName: "Asjad Tech",
      channelUrl: "https://www.youtube.com/channel/UCeZLS6OQx1N4UXz-lukFbIA",
      topic: "Lifestyle (sociology), Food",
      subscribers: 83800,
      subsGained30d: 41700,
      growthPct: 99.0,
      viewsGained30d: 28806692,
      channelCreatedAt: "2024-02-20",
    },
    {
      channelName: "Koko Panda",
      channelUrl: "https://www.youtube.com/channel/UCypANQvu4TLWVNBbQ60TX6Q",
      topic: "Food, Lifestyle (sociology)",
      subscribers: 332000,
      subsGained30d: 158000,
      growthPct: 90.8,
      viewsGained30d: 5215373,
      channelCreatedAt: "2020-03-16",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Be Smart With Palak",
    note: "an established channel (created 2016) that gained 120,500 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
