// Single source of truth for the YouTube Role-playing video game channel growth report
// (part of Video game culture).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Role-playing video game" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeRolePlayingVideoGameSubReport: YoutubeSubgenreReport = {
  subgenre: "Role-playing video game",
  parentCategory: "Video game culture",
  parentSlug: "gaming",
  region: "global",
  dataAsOf: "2026-10-06",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Rahulji901",
      channelUrl: "https://www.youtube.com/channel/UCWbafbtx1PxpIyFCepX_Y8w",
      topic: "Role-playing video game, Video game culture",
      subscribers: 126000,
      subsGained30d: 91000,
      growthPct: 260.0,
      viewsGained30d: 483621,
      channelCreatedAt: "2025-07-24",
    },
    {
      channelName: "アシュch",
      channelUrl: "https://www.youtube.com/channel/UCUJ-ypQvpTB34_loU2-V-Jg",
      topic: "Role-playing video game, Video game culture",
      subscribers: 392000,
      subsGained30d: 186000,
      growthPct: 90.3,
      viewsGained30d: 153218582,
      channelCreatedAt: "2025-09-10",
    },
    {
      channelName: "NoWoriz",
      channelUrl: "https://www.youtube.com/channel/UCNQqEx0_m2z_mejnk-WIY7g",
      topic: "Video game culture, Role-playing video game",
      subscribers: 139000,
      subsGained30d: 55600,
      growthPct: 66.7,
      viewsGained30d: 125144063,
      channelCreatedAt: "2021-02-21",
    },
    {
      channelName: "JσhทCbsn A",
      channelUrl: "https://www.youtube.com/channel/UCKdw9O1SgPZKfF_cgAYNuGw",
      topic: "Role-playing video game, Video game culture",
      subscribers: 117000,
      subsGained30d: 45300,
      growthPct: 63.2,
      viewsGained30d: 11724317,
      channelCreatedAt: "2024-03-07",
    },
    {
      channelName: "Ashiatrix",
      channelUrl: "https://www.youtube.com/channel/UCMV5-2SpME1EOeQM03jFZ5g",
      topic: "Video game culture, Role-playing video game",
      subscribers: 61500,
      subsGained30d: 22400,
      growthPct: 57.3,
      viewsGained30d: 13644361,
      channelCreatedAt: "2021-04-30",
    },
    {
      channelName: "ITS_YUG_XD",
      channelUrl: "https://www.youtube.com/channel/UC0v2Y3WM3JinWd-h8Hv5e2A",
      topic: "Video game culture, Role-playing video game",
      subscribers: 399000,
      subsGained30d: 133000,
      growthPct: 50.0,
      viewsGained30d: 677835068,
      channelCreatedAt: "2023-11-17",
    },
    {
      channelName: "☾,𝐌𝘆.𝐙𝗵︩︪𝝴ׂ𐐼ׅ𐐼ׅ𐐼ׅ-ִ☁️",
      channelUrl: "https://www.youtube.com/channel/UCLHI0H20apVaCPBH-RB9JyQ",
      topic: "Video game culture, Role-playing video game",
      subscribers: 75900,
      subsGained30d: 24800,
      growthPct: 48.5,
      viewsGained30d: 1743050,
      channelCreatedAt: "2025-03-30",
    },
    {
      channelName: "HYPO TONE",
      channelUrl: "https://www.youtube.com/channel/UC-zufZPoVMrl3QODpYDZDHg",
      topic: "Role-playing video game, Video game culture",
      subscribers: 491000,
      subsGained30d: 149000,
      growthPct: 43.6,
      viewsGained30d: 62636106,
      channelCreatedAt: "2025-08-08",
    },
    {
      channelName: "Gâu gâu",
      channelUrl: "https://www.youtube.com/channel/UCNKym5twIeCbplb8-qhdNsQ",
      topic: "Role-playing video game, Video game culture",
      subscribers: 109000,
      subsGained30d: 32900,
      growthPct: 43.2,
      viewsGained30d: 64203958,
      channelCreatedAt: "2022-02-22",
    },
    {
      channelName: "CreeperSnakk",
      channelUrl: "https://www.youtube.com/channel/UCbqEhAVKFOH3Mqn6GRh8d8Q",
      topic: "Role-playing video game, Video game culture",
      subscribers: 67200,
      subsGained30d: 19900,
      growthPct: 42.1,
      viewsGained30d: 33066221,
      channelCreatedAt: "2025-09-11",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Video game culture niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Rahulji901",
    note: "a newer channel (created 2025) that gained 91,000 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
