// Single source of truth for the YouTube Strategy video game channel growth report
// (part of Video game culture).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Strategy video game" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeStrategyVideoGameSubReport: YoutubeSubgenreReport = {
  subgenre: "Strategy video game",
  parentCategory: "Video game culture",
  parentSlug: "gaming",
  region: "global",
  dataAsOf: "2026-10-08",
  updatedAt: "2026-10-08",
  channels: [
    {
      channelName: "Riofx",
      channelUrl: "https://www.youtube.com/channel/UCP4OgC2LpgGp_Bgyti-Cpbg",
      topic: "Strategy video game, Video game culture",
      subscribers: 108000,
      subsGained30d: 60900,
      growthPct: 129.3,
      viewsGained30d: 4701912,
      channelCreatedAt: "2023-01-31",
    },
    {
      channelName: "KingPea",
      channelUrl: "https://www.youtube.com/channel/UCHmhBEpWpD48vIupvjsYarw",
      topic: "Video game culture, Strategy video game",
      subscribers: 103000,
      subsGained30d: 12400,
      growthPct: 13.7,
      viewsGained30d: 11136677,
      channelCreatedAt: "2023-10-02",
    },
    {
      channelName: "Warhammer 40,000",
      channelUrl: "https://www.youtube.com/channel/UCm4UYMFMVFKtZBi9uk4HSCg",
      topic: "Strategy video game, Video game culture",
      subscribers: 148000,
      subsGained30d: 17000,
      growthPct: 13.0,
      viewsGained30d: 8034528,
      channelCreatedAt: "2026-03-24",
    },
    {
      channelName: "홍인규 게임TV",
      channelUrl: "https://www.youtube.com/channel/UC543-TDm6IvHHZXwdSFioMw",
      topic: "Video game culture, Strategy video game",
      subscribers: 97800,
      subsGained30d: 8200,
      growthPct: 9.2,
      viewsGained30d: 2584230,
      channelCreatedAt: "2025-03-14",
    },
    {
      channelName: "BinhGOAT",
      channelUrl: "https://www.youtube.com/channel/UC2EU7SDEgsk2yTFZcn00wCw",
      topic: "Video game culture, Strategy video game",
      subscribers: 318000,
      subsGained30d: 19000,
      growthPct: 6.4,
      viewsGained30d: 36805737,
      channelCreatedAt: "2025-02-23",
    },
    {
      channelName: "Kurono Chloa / 黝乃くろあ",
      channelUrl: "https://www.youtube.com/channel/UCPPWh-9QdkkuLBnT6OQzxEw",
      topic: "Strategy video game, Video game culture",
      subscribers: 87700,
      subsGained30d: 4700,
      growthPct: 5.7,
      viewsGained30d: 7031327,
      channelCreatedAt: "2020-12-04",
    },
    {
      channelName: "GTAAA",
      channelUrl: "https://www.youtube.com/channel/UC18bmcfuTKQwgg62C5uc3tA",
      topic: "Video game culture, Strategy video game",
      subscribers: 230000,
      subsGained30d: 12000,
      growthPct: 5.5,
      viewsGained30d: 27094942,
      channelCreatedAt: "2021-05-26",
    },
    {
      channelName: "imonlyhereforpikmin",
      channelUrl: "https://www.youtube.com/channel/UCcJ6Ec8gORJcs2UBAnfewNQ",
      topic: "Strategy video game, Video game culture",
      subscribers: 50100,
      subsGained30d: 2500,
      growthPct: 5.3,
      viewsGained30d: 1206996,
      channelCreatedAt: "2023-09-27",
    },
    {
      channelName: "Saturn Edit,s",
      channelUrl: "https://www.youtube.com/channel/UCB0EIeVcw3Gwy7Ye2owm7UQ",
      topic: "Video game culture, Strategy video game",
      subscribers: 52400,
      subsGained30d: 2600,
      growthPct: 5.2,
      viewsGained30d: 3052901,
      channelCreatedAt: "2025-01-01",
    },
    {
      channelName: "Neanderman",
      channelUrl: "https://www.youtube.com/channel/UCEga1OYy6fz2sQ83_8DkX_Q",
      topic: "Video game culture, Strategy video game",
      subscribers: 147000,
      subsGained30d: 6000,
      growthPct: 4.3,
      viewsGained30d: 11626890,
      channelCreatedAt: "2022-12-29",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Video game culture niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Riofx",
    note: "an established channel (created 2023) that gained 60,900 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
