// Single source of truth for the YouTube Sports game channel growth report
// (part of Video game culture).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Sports game" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeSportsGameSubReport: YoutubeSubgenreReport = {
  subgenre: "Sports game",
  parentCategory: "Video game culture",
  parentSlug: "gaming",
  region: "global",
  dataAsOf: "2026-10-06",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "KING PLAYER",
      channelUrl: "https://www.youtube.com/channel/UCrhzIFmFwvb9Xegt_q561aw",
      topic: "Sports game, Video game culture",
      subscribers: 114000,
      subsGained30d: 52900,
      growthPct: 86.6,
      viewsGained30d: 44151835,
      channelCreatedAt: "2020-02-01",
    },
    {
      channelName: "R PES GAMING",
      channelUrl: "https://www.youtube.com/channel/UC0sKozOrglalgTLlsne6BlQ",
      topic: "Sports game, Video game culture",
      subscribers: 99500,
      subsGained30d: 43500,
      growthPct: 77.7,
      viewsGained30d: 2952738,
      channelCreatedAt: "2020-05-16",
    },
    {
      channelName: "4zFAIZI GAMING",
      channelUrl: "https://www.youtube.com/channel/UC1KM9w7D3y0yynU_hmxpmKA",
      topic: "Video game culture, Sports game",
      subscribers: 131000,
      subsGained30d: 40200,
      growthPct: 44.3,
      viewsGained30d: 3772610,
      channelCreatedAt: "2020-06-11",
    },
    {
      channelName: "RixGo",
      channelUrl: "https://www.youtube.com/channel/UCN4dZDSn5pfuDWCV7Q89rjA",
      topic: "Video game culture, Sports game",
      subscribers: 114000,
      subsGained30d: 27200,
      growthPct: 31.3,
      viewsGained30d: 54334929,
      channelCreatedAt: "2025-02-11",
    },
    {
      channelName: "SOJEEB FCC",
      channelUrl: "https://www.youtube.com/channel/UCMFBTBaBDA_AB0XwCMDR99w",
      topic: "Video game culture, Sports game",
      subscribers: 114000,
      subsGained30d: 23700,
      growthPct: 26.2,
      viewsGained30d: 15925205,
      channelCreatedAt: "2024-10-28",
    },
    {
      channelName: "THE SIKE_FC",
      channelUrl: "https://www.youtube.com/channel/UCUF4YiIhhX3Cu9uBN7N1xEA",
      topic: "Video game culture, Sports game",
      subscribers: 127000,
      subsGained30d: 25000,
      growthPct: 24.5,
      viewsGained30d: 7381025,
      channelCreatedAt: "2022-12-03",
    },
    {
      channelName: "Kaueafc",
      channelUrl: "https://www.youtube.com/channel/UCCqZ9ubf9IcSEdFH8fwyxBw",
      topic: "Video game culture, Sports game",
      subscribers: 422000,
      subsGained30d: 82000,
      growthPct: 24.1,
      viewsGained30d: 38902845,
      channelCreatedAt: "2022-11-26",
    },
    {
      channelName: "Vanzi Game",
      channelUrl: "https://www.youtube.com/channel/UCETEO8MToxzWisEcVqA8nJg",
      topic: "Sports game, Video game culture",
      subscribers: 65100,
      subsGained30d: 12100,
      growthPct: 22.8,
      viewsGained30d: 21670879,
      channelCreatedAt: "2020-07-09",
    },
    {
      channelName: "Sepuh FC",
      channelUrl: "https://www.youtube.com/channel/UCoCPQJhls4xLOCL_BWQoX6A",
      topic: "Sports game, Video game culture",
      subscribers: 203000,
      subsGained30d: 34000,
      growthPct: 20.1,
      viewsGained30d: 81443870,
      channelCreatedAt: "2020-12-01",
    },
    {
      channelName: "XOTIC EA FC",
      channelUrl: "https://www.youtube.com/channel/UCPzDXgajYfAGFT575CYnjjA",
      topic: "Video game culture, Sports game",
      subscribers: 232000,
      subsGained30d: 37000,
      growthPct: 19.0,
      viewsGained30d: 92627559,
      channelCreatedAt: "2022-10-13",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Video game culture niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "KING PLAYER",
    note: "an established channel (created 2020) that gained 52,900 subscribers in 30 days, a 86.6% increase over its subscriber base a month earlier",
  },
};
