// Single source of truth for the YouTube Tourism channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Tourism" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeTourismReport: YoutubeNicheReport = {
  niche: "Tourism",
  region: "global",
  dataAsOf: "2026-10-06",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Haida în Lume",
      channelUrl: "https://www.youtube.com/channel/UCAnpgeqGxTN-00zJP0CCoJg",
      topic: "Lifestyle (sociology), Tourism",
      subscribers: 331000,
      subsGained30d: 139000,
      growthPct: 72.4,
      viewsGained30d: 517140568,
      channelCreatedAt: "2021-09-11",
    },
    {
      channelName: "Don | The Bearded Backpacker",
      channelUrl: "https://www.youtube.com/channel/UCvSARfr1T8LxH5ukdF3DpIw",
      topic: "Tourism, Lifestyle (sociology)",
      subscribers: 77300,
      subsGained30d: 28000,
      growthPct: 56.8,
      viewsGained30d: 5147191,
      channelCreatedAt: "2024-05-30",
    },
    {
      channelName: "Sagar and Ami",
      channelUrl: "https://www.youtube.com/channel/UCfxBixgMCpAOImDX2Tm5gDw",
      topic: "Tourism, Lifestyle (sociology)",
      subscribers: 81200,
      subsGained30d: 24900,
      growthPct: 44.2,
      viewsGained30d: 105832001,
      channelCreatedAt: "2017-06-08",
    },
    {
      channelName: "Chris Paul Lawlor",
      channelUrl: "https://www.youtube.com/channel/UC3c2NACY0bR4kYSe5rsGTKw",
      topic: "Lifestyle (sociology), Tourism",
      subscribers: 55000,
      subsGained30d: 15300,
      growthPct: 38.5,
      viewsGained30d: 3356573,
      channelCreatedAt: "2017-06-02",
    },
    {
      channelName: "Dream The Falls",
      channelUrl: "https://www.youtube.com/channel/UCI9E2HvV5JLioFHQTj6Eoyw",
      topic: "Lifestyle (sociology), Tourism",
      subscribers: 336000,
      subsGained30d: 87000,
      growthPct: 34.9,
      viewsGained30d: 104377015,
      channelCreatedAt: "2025-08-04",
    },
    {
      channelName: "Meher Mudassar Maghu",
      channelUrl: "https://www.youtube.com/channel/UCWm75fmHP9hG1HyFLpKJH9Q",
      topic: "Tourism, Lifestyle (sociology)",
      subscribers: 64600,
      subsGained30d: 16300,
      growthPct: 33.7,
      viewsGained30d: 14298119,
      channelCreatedAt: "2015-11-24",
    },
    {
      channelName: "wild Dip",
      channelUrl: "https://www.youtube.com/channel/UC8B7O5hA5Sf4pNgFofl5Ssw",
      topic: "Lifestyle (sociology), Tourism",
      subscribers: 95700,
      subsGained30d: 22100,
      growthPct: 30.0,
      viewsGained30d: 38841245,
      channelCreatedAt: "2025-09-29",
    },
    {
      channelName: "FUNFAIR VLOGS",
      channelUrl: "https://www.youtube.com/channel/UC6D5ZiRbKcLHoOD6DTsgPsQ",
      topic: "Lifestyle (sociology), Tourism",
      subscribers: 171000,
      subsGained30d: 38000,
      growthPct: 28.6,
      viewsGained30d: 49989361,
      channelCreatedAt: "2022-04-06",
    },
    {
      channelName: "Korea Tourism Organization Manila Office",
      channelUrl: "https://www.youtube.com/channel/UC8Ru2JTfC0rFAAKhqceB_Fg",
      topic: "Lifestyle (sociology), Tourism",
      subscribers: 56400,
      subsGained30d: 12400,
      growthPct: 28.2,
      viewsGained30d: 142311,
      channelCreatedAt: "2019-11-18",
    },
    {
      channelName: "Thoothukudi Mapla",
      channelUrl: "https://www.youtube.com/channel/UCWKyBGBiyYb6Li3k-0LABEQ",
      topic: "Lifestyle (sociology), Tourism",
      subscribers: 82800,
      subsGained30d: 17600,
      growthPct: 27.0,
      viewsGained30d: 132680,
      channelCreatedAt: "2023-06-02",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Haida în Lume",
    note: "an established channel (created 2021) that gained 139,000 subscribers in 30 days, a 72.4% increase over its subscriber base a month earlier",
  },
};
