// Single source of truth for the YouTube Soul music channel growth report
// (part of Music).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Soul music" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeSoulMusicSubReport: YoutubeSubgenreReport = {
  subgenre: "Soul music",
  parentCategory: "Music",
  parentSlug: "music",
  region: "global",
  dataAsOf: "2026-10-08",
  updatedAt: "2026-10-08",
  channels: [
    {
      channelName: "AJ Ghent",
      channelUrl: "https://www.youtube.com/channel/UCJUtUZ7TAwbomgqPLfHhxsg",
      topic: "Soul music, Music",
      subscribers: 155000,
      subsGained30d: 2000,
      growthPct: 1.3,
      viewsGained30d: 518060,
      channelCreatedAt: "2012-01-09",
    },
    {
      channelName: "Music For Muslim",
      channelUrl: "https://www.youtube.com/channel/UCxDF3R3ZWakodozPHwfpoNQ",
      topic: "Soul music, Music",
      subscribers: 59100,
      subsGained30d: 400,
      growthPct: 0.7,
      viewsGained30d: 216365,
      channelCreatedAt: "2024-06-25",
    },
    {
      channelName: "Soothing Soul",
      channelUrl: "https://www.youtube.com/channel/UCZmAixeX48BhtAHXmD9l5Ug",
      topic: "Music, Soul music",
      subscribers: 223000,
      subsGained30d: 1000,
      growthPct: 0.5,
      viewsGained30d: 1245269,
      channelCreatedAt: "2023-09-19",
    },
    {
      channelName: "Healing Soul",
      channelUrl: "https://www.youtube.com/channel/UCnLjr0czO5zPsJYubbrvHCw",
      topic: "Music, Soul music",
      subscribers: 282000,
      subsGained30d: 1000,
      growthPct: 0.4,
      viewsGained30d: 1585746,
      channelCreatedAt: "2021-09-27",
    },
    {
      channelName: "afrosunny",
      channelUrl: "https://www.youtube.com/channel/UCLGJ7_fQVIsK4uS-AvNvNtg",
      topic: "Music, Soul music",
      subscribers: 72700,
      subsGained30d: 200,
      growthPct: 0.3,
      viewsGained30d: 154821,
      channelCreatedAt: "2020-02-27",
    },
    {
      channelName: "Open Heart Music - Helios 4K",
      channelUrl: "https://www.youtube.com/channel/UC4L-dSrzbPoZcr1Av5GvwKw",
      topic: "Music, Soul music",
      subscribers: 818000,
      subsGained30d: 0,
      growthPct: 0.0,
      viewsGained30d: 238794,
      channelCreatedAt: "2020-03-23",
    },
    {
      channelName: "Open Mic UK",
      channelUrl: "https://www.youtube.com/channel/UC6wSmqdZVHwFL5CCRY7xZ-g",
      topic: "Music, Soul music",
      subscribers: 52300,
      subsGained30d: 0,
      growthPct: 0.0,
      viewsGained30d: 20476,
      channelCreatedAt: "2009-12-22",
    },
    {
      channelName: "BGC Melody",
      channelUrl: "https://www.youtube.com/channel/UCAomlcHScamQ91lPTGj5hDQ",
      topic: "Soul music, Music",
      subscribers: 118000,
      subsGained30d: 0,
      growthPct: 0.0,
      viewsGained30d: 45613,
      channelCreatedAt: "2006-08-21",
    },
    {
      channelName: "Jake Bennett — Curador do Fado",
      channelUrl: "https://www.youtube.com/channel/UCEliM7QoRWqDbU4c0nagQgQ",
      topic: "Soul music, Music",
      subscribers: 337000,
      subsGained30d: 0,
      growthPct: 0.0,
      viewsGained30d: 94996,
      channelCreatedAt: "2024-01-24",
    },
    {
      channelName: "Blue Lantern Blues Club",
      channelUrl: "https://www.youtube.com/channel/UCJN7bayOfm_SF1xH3ntzkcw",
      topic: "Music, Soul music",
      subscribers: 125000,
      subsGained30d: 0,
      growthPct: 0.0,
      viewsGained30d: 8,
      channelCreatedAt: "2024-06-15",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Music niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "AJ Ghent",
    note: "an established channel (created 2012) that gained 2,000 subscribers in 30 days, a 1.3% increase over its subscriber base a month earlier",
  },
};
