// Single source of truth for the YouTube Classical music channel growth report
// (part of Music).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Classical music" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeClassicalMusicSubReport: YoutubeSubgenreReport = {
  subgenre: "Classical music",
  parentCategory: "Music",
  parentSlug: "music",
  region: "global",
  dataAsOf: "2026-10-10",
  updatedAt: "2026-10-10",
  channels: [
    {
      channelName: "Poviolinist",
      channelUrl: "https://www.youtube.com/channel/UCMXg1cFPK2VkGfomkWdqBOA",
      topic: "Classical music, Music",
      subscribers: 599000,
      subsGained30d: 115000,
      growthPct: 23.8,
      viewsGained30d: 35856141,
      channelCreatedAt: "2022-02-23",
    },
    {
      channelName: "ClassicalMusic Playlist",
      channelUrl: "https://www.youtube.com/channel/UCOfm8A5g8mn1TESPt7IM_KA",
      topic: "Classical music, Music",
      subscribers: 72400,
      subsGained30d: 9000,
      growthPct: 14.2,
      viewsGained30d: 2544373,
      channelCreatedAt: "2026-04-22",
    },
    {
      channelName: "GoldenDöngü",
      channelUrl: "https://www.youtube.com/channel/UC2zjxGqGJliyQBoJ54yscqg",
      topic: "Classical music, Music",
      subscribers: 62400,
      subsGained30d: 6800,
      growthPct: 12.2,
      viewsGained30d: 4248244,
      channelCreatedAt: "2006-10-01",
    },
    {
      channelName: "Mary Frances",
      channelUrl: "https://www.youtube.com/channel/UCAiHmoXsOyUgQ7eqVE0POIA",
      topic: "Music, Classical music",
      subscribers: 55700,
      subsGained30d: 5700,
      growthPct: 11.4,
      viewsGained30d: 6323584,
      channelCreatedAt: "2024-03-30",
    },
    {
      channelName: "Danlu",
      channelUrl: "https://www.youtube.com/channel/UCXBQ7CBw0_-__kZpo9KGKxg",
      topic: "Music, Classical music",
      subscribers: 309000,
      subsGained30d: 31000,
      growthPct: 11.2,
      viewsGained30d: 3994675,
      channelCreatedAt: "2020-08-04",
    },
    {
      channelName: "Juan Arenosa",
      channelUrl: "https://www.youtube.com/channel/UC7T3t3WgN8sS3R2RIrnGWIw",
      topic: "Classical music, Music",
      subscribers: 110000,
      subsGained30d: 8000,
      growthPct: 7.8,
      viewsGained30d: 5405761,
      channelCreatedAt: "2018-01-17",
    },
    {
      channelName: "Louis Philippson",
      channelUrl: "https://www.youtube.com/channel/UCfpOKO3hIYpvpoflw61PGQA",
      topic: "Music, Classical music",
      subscribers: 97200,
      subsGained30d: 6000,
      growthPct: 6.6,
      viewsGained30d: 6563302,
      channelCreatedAt: "2021-10-07",
    },
    {
      channelName: "배쌤에 미쳐 Beseme Micho",
      channelUrl: "https://www.youtube.com/channel/UCwy_2MZ9VVZwfvchlHdOsRQ",
      topic: "Classical music, Music",
      subscribers: 87100,
      subsGained30d: 5200,
      growthPct: 6.3,
      viewsGained30d: 5687734,
      channelCreatedAt: "2017-10-02",
    },
    {
      channelName: "Baby Sleep",
      channelUrl: "https://www.youtube.com/channel/UC-baLvXyHvQkLSnvHNZbK7A",
      topic: "Classical music, Music",
      subscribers: 53100,
      subsGained30d: 2800,
      growthPct: 5.6,
      viewsGained30d: 2264523,
      channelCreatedAt: "2023-02-23",
    },
    {
      channelName: "Classical KING",
      channelUrl: "https://www.youtube.com/channel/UCHen90XjpJ7Jn1Sq9R_adKQ",
      topic: "Classical music, Music",
      subscribers: 77000,
      subsGained30d: 4000,
      growthPct: 5.5,
      viewsGained30d: 85486,
      channelCreatedAt: "2008-01-28",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Music niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Poviolinist",
    note: "an established channel (created 2022) that gained 115,000 subscribers in 30 days, a 23.8% increase over its subscriber base a month earlier",
  },
};
