// Single source of truth for the YouTube Christian music channel growth report
// (part of Music).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Christian music" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeChristianMusicSubReport: YoutubeSubgenreReport = {
  subgenre: "Christian music",
  parentCategory: "Music",
  parentSlug: "music",
  region: "global",
  dataAsOf: "2026-10-10",
  updatedAt: "2026-10-10",
  channels: [
    {
      channelName: "SAMMY G",
      channelUrl: "https://www.youtube.com/channel/UChaqP_A7bQaQM1OUxdDu8sg",
      topic: "Christian music, Music",
      subscribers: 93200,
      subsGained30d: 21400,
      growthPct: 29.8,
      viewsGained30d: 909064,
      channelCreatedAt: "2021-04-18",
    },
    {
      channelName: "Christmas music TV",
      channelUrl: "https://www.youtube.com/channel/UC4y7RZDPQv4u63nL5WADU1g",
      topic: "Christian music, Music",
      subscribers: 65800,
      subsGained30d: 8400,
      growthPct: 14.6,
      viewsGained30d: 97058,
      channelCreatedAt: "2015-08-31",
    },
    {
      channelName: "Busy Bee Onyiego",
      channelUrl: "https://www.youtube.com/channel/UC_Z51QVc2fgyfssySm9uwSg",
      topic: "Christian music, Music",
      subscribers: 75300,
      subsGained30d: 7500,
      growthPct: 11.1,
      viewsGained30d: 1010135,
      channelCreatedAt: "2019-04-09",
    },
    {
      channelName: "Rachats classic",
      channelUrl: "https://www.youtube.com/channel/UC9yn-Qj47yCdBgmaLDX4m5A",
      topic: "Christian music, Music",
      subscribers: 94800,
      subsGained30d: 9200,
      growthPct: 10.7,
      viewsGained30d: 2414130,
      channelCreatedAt: "2021-05-03",
    },
    {
      channelName: "Kano Choir",
      channelUrl: "https://www.youtube.com/channel/UCdlMyzem19huTuUUzhxY0yA",
      topic: "Christian music, Music",
      subscribers: 119000,
      subsGained30d: 10000,
      growthPct: 9.2,
      viewsGained30d: 10454132,
      channelCreatedAt: "2025-12-01",
    },
    {
      channelName: "Ryan jones ( Child of the Most High God)",
      channelUrl: "https://www.youtube.com/channel/UCDb3hpepcphZi8bqEk9U3xQ",
      topic: "Christian music, Music",
      subscribers: 236000,
      subsGained30d: 16000,
      growthPct: 7.3,
      viewsGained30d: 2696523,
      channelCreatedAt: "2017-05-21",
    },
    {
      channelName: "Ornella mwenzela grâce officielle",
      channelUrl: "https://www.youtube.com/channel/UCP8x9RiMcEyyfgosIwG9PdA",
      topic: "Christian music, Music",
      subscribers: 90000,
      subsGained30d: 5700,
      growthPct: 6.8,
      viewsGained30d: 927426,
      channelCreatedAt: "2022-11-17",
    },
    {
      channelName: "Daniel Lima filho",
      channelUrl: "https://www.youtube.com/channel/UCZYwmWH-9jKshgkdx1Wepog",
      topic: "Music, Christian music",
      subscribers: 71900,
      subsGained30d: 4100,
      growthPct: 6.0,
      viewsGained30d: 5249512,
      channelCreatedAt: "2026-04-20",
    },
    {
      channelName: "DIEZ PERFORMANCE",
      channelUrl: "https://www.youtube.com/channel/UCnRqUGDiRb44sd7PBExwelA",
      topic: "Christian music, Music",
      subscribers: 91900,
      subsGained30d: 5000,
      growthPct: 5.8,
      viewsGained30d: 1081112,
      channelCreatedAt: "2023-11-15",
    },
    {
      channelName: "Soul Touch Brand",
      channelUrl: "https://www.youtube.com/channel/UC_Cz3jYcIZzJHVBZ2DvuiFA",
      topic: "Music, Christian music",
      subscribers: 139000,
      subsGained30d: 7000,
      growthPct: 5.3,
      viewsGained30d: 2690128,
      channelCreatedAt: "2021-03-27",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Music niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "SAMMY G",
    note: "an established channel (created 2021) that gained 21,400 subscribers in 30 days, a 29.8% increase over its subscriber base a month earlier",
  },
};
