// Single source of truth for the YouTube Vehicle channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Vehicle" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeVehiclesReport: YoutubeNicheReport = {
  niche: "Vehicle",
  region: "global",
  dataAsOf: "2026-10-09",
  updatedAt: "2026-10-09",
  channels: [
    {
      channelName: "Nostalgia Car POV Drives",
      channelUrl: "https://www.youtube.com/channel/UCN3bdqvg2EdqUpmLY2vB8lw",
      topic: "Lifestyle (sociology), Vehicle",
      subscribers: 140000,
      subsGained30d: 69100,
      growthPct: 97.5,
      viewsGained30d: 489558,
      channelCreatedAt: "2009-09-16",
    },
    {
      channelName: "Bjune Works",
      channelUrl: "https://www.youtube.com/channel/UC3evoavF2m-pZuc31ug8iSg",
      topic: "Lifestyle (sociology), Vehicle",
      subscribers: 114000,
      subsGained30d: 55900,
      growthPct: 96.2,
      viewsGained30d: 87199190,
      channelCreatedAt: "2025-04-19",
    },
    {
      channelName: "LITH-TECH MOBILITY",
      channelUrl: "https://www.youtube.com/channel/UCCt7A-U0mHI8wMTvvb86c6Q",
      topic: "Vehicle, Lifestyle (sociology)",
      subscribers: 79100,
      subsGained30d: 36900,
      growthPct: 87.4,
      viewsGained30d: 651506,
      channelCreatedAt: "2019-01-27",
    },
    {
      channelName: "Maxlider Bros. Broncos, Tacos & Golf!",
      channelUrl: "https://www.youtube.com/channel/UC0kehgOavLrc8BOugznxpbQ",
      topic: "Vehicle, Lifestyle (sociology)",
      subscribers: 67100,
      subsGained30d: 28400,
      growthPct: 73.4,
      viewsGained30d: 307119,
      channelCreatedAt: "2016-12-22",
    },
    {
      channelName: "AVEXN",
      channelUrl: "https://www.youtube.com/channel/UCY978kXpidhx6ffAmoVIoAg",
      topic: "Lifestyle (sociology), Vehicle",
      subscribers: 77200,
      subsGained30d: 29200,
      growthPct: 60.8,
      viewsGained30d: 23088423,
      channelCreatedAt: "2023-08-04",
    },
    {
      channelName: "Railway Fans Club",
      channelUrl: "https://www.youtube.com/channel/UCvcOZcKYgAUP6wu5MAlchBA",
      topic: "Lifestyle (sociology), Vehicle",
      subscribers: 69500,
      subsGained30d: 25900,
      growthPct: 59.4,
      viewsGained30d: 25604012,
      channelCreatedAt: "2012-05-28",
    },
    {
      channelName: "Drive Goal",
      channelUrl: "https://www.youtube.com/channel/UCCBfRwe1wN2w2PgGfsyvxnQ",
      topic: "Lifestyle (sociology), Vehicle",
      subscribers: 96000,
      subsGained30d: 35200,
      growthPct: 57.9,
      viewsGained30d: 60770383,
      channelCreatedAt: "2025-04-04",
    },
    {
      channelName: "Terminal 2W",
      channelUrl: "https://www.youtube.com/channel/UCHy3nnMa5pyD9woj3fKPzeg",
      topic: "Lifestyle (sociology), Vehicle",
      subscribers: 93500,
      subsGained30d: 33900,
      growthPct: 56.9,
      viewsGained30d: 192766,
      channelCreatedAt: "2024-10-20",
    },
    {
      channelName: "Rail and Travels",
      channelUrl: "https://www.youtube.com/channel/UCXODUekPbLs8kCODtg8chOg",
      topic: "Vehicle, Lifestyle (sociology)",
      subscribers: 55200,
      subsGained30d: 19600,
      growthPct: 55.1,
      viewsGained30d: 31964004,
      channelCreatedAt: "2025-01-21",
    },
    {
      channelName: "Pay attention to Thrilling road",
      channelUrl: "https://www.youtube.com/channel/UCUN6VTH7RoCSyzpLMQb60Bg",
      topic: "Lifestyle (sociology), Vehicle",
      subscribers: 130000,
      subsGained30d: 45600,
      growthPct: 54.0,
      viewsGained30d: 31839512,
      channelCreatedAt: "2025-02-18",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Nostalgia Car POV Drives",
    note: "an established channel (created 2009) that gained 69,100 subscribers in 30 days, a 97.5% increase over its subscriber base a month earlier",
  },
};
