// Single source of truth for the YouTube Puzzle video game channel growth report
// (part of Video game culture).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Puzzle video game" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubePuzzleVideoGameSubReport: YoutubeSubgenreReport = {
  subgenre: "Puzzle video game",
  parentCategory: "Video game culture",
  parentSlug: "gaming",
  region: "global",
  dataAsOf: "2026-10-08",
  updatedAt: "2026-10-08",
  channels: [
    {
      channelName: "SS95 GAMING",
      channelUrl: "https://www.youtube.com/channel/UCTdUPf0tVk-WxMhz3bn29IA",
      topic: "Puzzle video game, Video game culture",
      subscribers: 87800,
      subsGained30d: 35800,
      growthPct: 68.8,
      viewsGained30d: 116237,
      channelCreatedAt: "2025-11-20",
    },
    {
      channelName: "ZX PLAYZ",
      channelUrl: "https://www.youtube.com/channel/UCQrE0op6xSfU_nalL5UXU9g",
      topic: "Video game culture, Puzzle video game",
      subscribers: 59600,
      subsGained30d: 23900,
      growthPct: 66.9,
      viewsGained30d: 34201724,
      channelCreatedAt: "2026-03-25",
    },
    {
      channelName: "『Tᴀᴍɪʟᴀɴ』Gᴀᴍɪɴɢ.",
      channelUrl: "https://www.youtube.com/channel/UCaFYpT4DZ163tX35x3wyM-g",
      topic: "Puzzle video game, Video game culture",
      subscribers: 121000,
      subsGained30d: 21100,
      growthPct: 21.1,
      viewsGained30d: 67444632,
      channelCreatedAt: "2025-06-02",
    },
    {
      channelName: "Lagged",
      channelUrl: "https://www.youtube.com/channel/UCSFFRjTrbboKQOjvF6c1KGQ",
      topic: "Video game culture, Puzzle video game",
      subscribers: 131000,
      subsGained30d: 22000,
      growthPct: 20.2,
      viewsGained30d: 14842869,
      channelCreatedAt: "2015-08-28",
    },
    {
      channelName: "Babul Official",
      channelUrl: "https://www.youtube.com/channel/UCnb8jeFmtLCWFbbaLeNo9rg",
      topic: "Video game culture, Puzzle video game",
      subscribers: 63000,
      subsGained30d: 9300,
      growthPct: 17.3,
      viewsGained30d: 1724669,
      channelCreatedAt: "2024-10-19",
    },
    {
      channelName: "kingR islive",
      channelUrl: "https://www.youtube.com/channel/UCmOR7QuiHAKnHvdYdx9gFgQ",
      topic: "Puzzle video game, Video game culture",
      subscribers: 117000,
      subsGained30d: 16000,
      growthPct: 15.8,
      viewsGained30d: 25014002,
      channelCreatedAt: "2018-03-03",
    },
    {
      channelName: "Kalliu Game World Official",
      channelUrl: "https://www.youtube.com/channel/UCQoZbTrY9qWLbVXX3kY28gw",
      topic: "Video game culture, Puzzle video game",
      subscribers: 185000,
      subsGained30d: 22000,
      growthPct: 13.5,
      viewsGained30d: 8497000,
      channelCreatedAt: "2025-06-19",
    },
    {
      channelName: "PatilG",
      channelUrl: "https://www.youtube.com/channel/UC1r8t63A3T6Pd-rsjFbP40Q",
      topic: "Video game culture, Puzzle video game",
      subscribers: 58800,
      subsGained30d: 6500,
      growthPct: 12.4,
      viewsGained30d: 10747509,
      channelCreatedAt: "2018-11-27",
    },
    {
      channelName: "Mohini game2.0",
      channelUrl: "https://www.youtube.com/channel/UCg81RC9g1sI_9XWd-tDVp2g",
      topic: "Video game culture, Puzzle video game",
      subscribers: 101000,
      subsGained30d: 10700,
      growthPct: 11.8,
      viewsGained30d: 2440512,
      channelCreatedAt: "2024-03-26",
    },
    {
      channelName: "Saffulla YT",
      channelUrl: "https://www.youtube.com/channel/UCB4A8hG1ESEAKc3e5JZRBRw",
      topic: "Video game culture, Puzzle video game",
      subscribers: 104000,
      subsGained30d: 10700,
      growthPct: 11.5,
      viewsGained30d: 23115101,
      channelCreatedAt: "2021-12-14",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Video game culture niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "SS95 GAMING",
    note: "a newer channel (created 2025) that gained 35,800 subscribers in 30 days, a 68.8% increase over its subscriber base a month earlier",
  },
};
