// Single source of truth for the YouTube Health channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Health" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeHealthReport: YoutubeNicheReport = {
  niche: "Health",
  region: "global",
  dataAsOf: "2026-10-10",
  updatedAt: "2026-10-10",
  channels: [
    {
      channelName: "Tj Power",
      channelUrl: "https://www.youtube.com/channel/UCkTqsjNtYqS5nxfTWgAYtjw",
      topic: "Health, Lifestyle (sociology)",
      subscribers: 71700,
      subsGained30d: 37600,
      growthPct: 110.3,
      viewsGained30d: 3554168,
      channelCreatedAt: "2024-07-07",
    },
    {
      channelName: "堀大輔の日常",
      channelUrl: "https://www.youtube.com/channel/UCvvvp06BNBYpuiT5zKHYLXA",
      topic: "Lifestyle (sociology), Health",
      subscribers: 271000,
      subsGained30d: 134000,
      growthPct: 97.8,
      viewsGained30d: 60909206,
      channelCreatedAt: "2015-03-01",
    },
    {
      channelName: "The Restore Clinic",
      channelUrl: "https://www.youtube.com/channel/UCuRkI0j-EImBFEJJ7TsCMaw",
      topic: "Lifestyle (sociology), Health",
      subscribers: 81000,
      subsGained30d: 37700,
      growthPct: 87.1,
      viewsGained30d: 1115109,
      channelCreatedAt: "2012-08-11",
    },
    {
      channelName: "Sarvodaya Health Club [सर्वोदय हेल्थ क्लब]",
      channelUrl: "https://www.youtube.com/channel/UC3qx3jqecIHlQtE3oxuC2xQ",
      topic: "Lifestyle (sociology), Health",
      subscribers: 203000,
      subsGained30d: 80000,
      growthPct: 65.0,
      viewsGained30d: 21516588,
      channelCreatedAt: "2020-06-26",
    },
    {
      channelName: "health diet",
      channelUrl: "https://www.youtube.com/channel/UCQ1QXAkKN4TGRs8v4x89peQ",
      topic: "Health, Lifestyle (sociology)",
      subscribers: 132000,
      subsGained30d: 46300,
      growthPct: 54.0,
      viewsGained30d: 55179250,
      channelCreatedAt: "2023-08-24",
    },
    {
      channelName: "Life is beautiful",
      channelUrl: "https://www.youtube.com/channel/UChoHJ0R2Hb78gNxQKy7E-aQ",
      topic: "Health, Lifestyle (sociology)",
      subscribers: 97800,
      subsGained30d: 33500,
      growthPct: 52.1,
      viewsGained30d: 24037565,
      channelCreatedAt: "2023-02-08",
    },
    {
      channelName: "Vandana Kitchen",
      channelUrl: "https://www.youtube.com/channel/UCEtYNg_QwDUuJVHqw4iI0yw",
      topic: "Health, Lifestyle (sociology)",
      subscribers: 166000,
      subsGained30d: 56000,
      growthPct: 50.9,
      viewsGained30d: 37323061,
      channelCreatedAt: "2018-02-09",
    },
    {
      channelName: "Uttam Roy",
      channelUrl: "https://www.youtube.com/channel/UC6L2Fx9T4sCtNWTUQKpRX_g",
      topic: "Health, Lifestyle (sociology)",
      subscribers: 142000,
      subsGained30d: 45500,
      growthPct: 47.2,
      viewsGained30d: 17995510,
      channelCreatedAt: "2013-11-13",
    },
    {
      channelName: "Başak Sayan",
      channelUrl: "https://www.youtube.com/channel/UCCZgiTl_8fdUj_lN4X_Fhbw",
      topic: "Health, Lifestyle (sociology)",
      subscribers: 58900,
      subsGained30d: 18300,
      growthPct: 45.1,
      viewsGained30d: 654076,
      channelCreatedAt: "2017-02-13",
    },
    {
      channelName: "Healthly Bite",
      channelUrl: "https://www.youtube.com/channel/UC-1yF8Lf9Tu0QEvxJaXiCsA",
      topic: "Health, Lifestyle (sociology)",
      subscribers: 60700,
      subsGained30d: 18200,
      growthPct: 42.8,
      viewsGained30d: 4238586,
      channelCreatedAt: "2025-10-30",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Tj Power",
    note: "an established channel (created 2024) that gained 37,600 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
