// Single source of truth for the YouTube Pop music channel growth report
// (part of Music).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Pop music" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubePopMusicSubReport: YoutubeSubgenreReport = {
  subgenre: "Pop music",
  parentCategory: "Music",
  parentSlug: "music",
  region: "global",
  dataAsOf: "2026-10-08",
  updatedAt: "2026-10-08",
  channels: [
    {
      channelName: "Timeunheard",
      channelUrl: "https://www.youtube.com/channel/UCODZmz_Ve3DIN5_7A7OLXJw",
      topic: "Music, Pop music",
      subscribers: 55800,
      subsGained30d: 28100,
      growthPct: 101.4,
      viewsGained30d: 220285,
      channelCreatedAt: "2025-12-29",
    },
    {
      channelName: "FIA",
      channelUrl: "https://www.youtube.com/channel/UCN8VcDN_-a1GFYs8_O390WQ",
      topic: "Music, Pop music",
      subscribers: 123000,
      subsGained30d: 49300,
      growthPct: 66.9,
      viewsGained30d: 12251627,
      channelCreatedAt: "2021-01-30",
    },
    {
      channelName: "Alyssa Grace",
      channelUrl: "https://www.youtube.com/channel/UC6DEAumiJdezDDYCOrNW6Qg",
      topic: "Pop music, Music",
      subscribers: 142000,
      subsGained30d: 36000,
      growthPct: 34.0,
      viewsGained30d: 12107916,
      channelCreatedAt: "2019-12-07",
    },
    {
      channelName: "Kazdoura",
      channelUrl: "https://www.youtube.com/channel/UCQA3tmZUtSLLmeQ58n6m5oA",
      topic: "Music, Pop music",
      subscribers: 62700,
      subsGained30d: 13200,
      growthPct: 26.7,
      viewsGained30d: 280482,
      channelCreatedAt: "2021-10-22",
    },
    {
      channelName: "X-FACTOR",
      channelUrl: "https://www.youtube.com/channel/UCKCf86MhQ3ShIrTUi7MRtag",
      topic: "Pop music, Music",
      subscribers: 84100,
      subsGained30d: 14800,
      growthPct: 21.4,
      viewsGained30d: 31561514,
      channelCreatedAt: "2023-01-08",
    },
    {
      channelName: "Göksel İpekçi",
      channelUrl: "https://www.youtube.com/channel/UC1SfmoqbmaVIszKOH6P99dQ",
      topic: "Music, Pop music",
      subscribers: 147000,
      subsGained30d: 25000,
      growthPct: 20.5,
      viewsGained30d: 7138492,
      channelCreatedAt: "2020-02-13",
    },
    {
      channelName: "RRStudio 🎷 Музыка для Души",
      channelUrl: "https://www.youtube.com/channel/UCHICsCkYtG_aGlccMin87jg",
      topic: "Pop music, Music",
      subscribers: 109000,
      subsGained30d: 16300,
      growthPct: 17.6,
      viewsGained30d: 4611256,
      channelCreatedAt: "2011-10-15",
    },
    {
      channelName: "Gitaris Virtual",
      channelUrl: "https://www.youtube.com/channel/UCxmD4IlfIkKbwnMZ2qO6jaQ",
      topic: "Music, Pop music",
      subscribers: 127000,
      subsGained30d: 18000,
      growthPct: 16.5,
      viewsGained30d: 11953123,
      channelCreatedAt: "2024-07-11",
    },
    {
      channelName: "Nagy Bogi",
      channelUrl: "https://www.youtube.com/channel/UCMNfe5ziYK_EGUHKe7qx8Ww",
      topic: "Pop music, Music",
      subscribers: 105000,
      subsGained30d: 13900,
      growthPct: 15.3,
      viewsGained30d: 9610055,
      channelCreatedAt: "2013-10-19",
    },
    {
      channelName: "Giorgos Mazonakis",
      channelUrl: "https://www.youtube.com/channel/UCuHZOTk8MkEzamxYfd3LMNQ",
      topic: "Pop music, Music",
      subscribers: 338000,
      subsGained30d: 44000,
      growthPct: 15.0,
      viewsGained30d: 39344264,
      channelCreatedAt: "2015-05-08",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Music niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Timeunheard",
    note: "a newer channel (created 2025) that gained 28,100 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
