// Single source of truth for the YouTube Entertainment channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Entertainment" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeEntertainmentReport: YoutubeNicheReport = {
  niche: "Entertainment",
  region: "global",
  dataAsOf: "2026-10-07",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Haryanvi Saas Bhu Rasoi",
      channelUrl: "https://www.youtube.com/channel/UCHRCTZ3WcYl_JDIP6Ti_7wA",
      topic: "Lifestyle (sociology), Entertainment",
      subscribers: 244000,
      subsGained30d: 224000,
      growthPct: 1120.0,
      viewsGained30d: 70560897,
      channelCreatedAt: "2026-02-06",
    },
    {
      channelName: "Chittu Kuruvi",
      channelUrl: "https://www.youtube.com/channel/UCkEY39gdZyIkJPSiEVelj0w",
      topic: "Film, Entertainment",
      subscribers: 154000,
      subsGained30d: 123200,
      growthPct: 400.0,
      viewsGained30d: 12688830,
      channelCreatedAt: "2017-12-31",
    },
    {
      channelName: "LijDaily Toonz",
      channelUrl: "https://www.youtube.com/channel/UCZzvnpURNKOJd1DvmurGP8g",
      topic: "Entertainment",
      subscribers: 157000,
      subsGained30d: 124600,
      growthPct: 384.6,
      viewsGained30d: 3088423,
      channelCreatedAt: "2025-11-18",
    },
    {
      channelName: "KinTirob",
      channelUrl: "https://www.youtube.com/channel/UCXslVaWv7lLmU_Atb1B0cTA",
      topic: "Lifestyle (sociology), Entertainment",
      subscribers: 92200,
      subsGained30d: 71900,
      growthPct: 354.2,
      viewsGained30d: 913189,
      channelCreatedAt: "2026-01-27",
    },
    {
      channelName: "Velvet Frames",
      channelUrl: "https://www.youtube.com/channel/UCqq1qORHBZMSrLqE7UqbSTg",
      topic: "Entertainment",
      subscribers: 186000,
      subsGained30d: 144500,
      growthPct: 348.2,
      viewsGained30d: 4626075,
      channelCreatedAt: "2026-02-10",
    },
    {
      channelName: "Mateus Silva jr",
      channelUrl: "https://www.youtube.com/channel/UCJ7qELxe_pAObhAgHLIgBTg",
      topic: "Entertainment, Lifestyle (sociology)",
      subscribers: 154000,
      subsGained30d: 119600,
      growthPct: 347.7,
      viewsGained30d: 3150518,
      channelCreatedAt: "2015-12-06",
    },
    {
      channelName: "LyraLStory",
      channelUrl: "https://www.youtube.com/channel/UCSPbZoaGkho_3gZpZXKz31g",
      topic: "Lifestyle (sociology), Entertainment",
      subscribers: 302000,
      subsGained30d: 224100,
      growthPct: 287.7,
      viewsGained30d: 4841735,
      channelCreatedAt: "2025-05-16",
    },
    {
      channelName: "Blackout Docs",
      channelUrl: "https://www.youtube.com/channel/UCAJurFpws8jtYVV3aX21Tgg",
      topic: "Lifestyle (sociology), Entertainment",
      subscribers: 96300,
      subsGained30d: 71100,
      growthPct: 282.1,
      viewsGained30d: 514129551,
      channelCreatedAt: "2025-03-01",
    },
    {
      channelName: "RanyFanty! 🩷",
      channelUrl: "https://www.youtube.com/channel/UCpuEG7e23YbxDSqW6MBQ_qw",
      topic: "Entertainment",
      subscribers: 99900,
      subsGained30d: 70300,
      growthPct: 237.5,
      viewsGained30d: 34012676,
      channelCreatedAt: "2020-09-29",
    },
    {
      channelName: "NK Stories Zone",
      channelUrl: "https://www.youtube.com/channel/UCqGR0h9xSyjLkRtVozLincg",
      topic: "Entertainment, Film",
      subscribers: 82300,
      subsGained30d: 57700,
      growthPct: 234.6,
      viewsGained30d: 10752815,
      channelCreatedAt: "2020-07-27",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Haryanvi Saas Bhu Rasoi",
    note: "a newer channel (created 2026) that gained 224,000 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
