// Single source of truth for the YouTube Politics channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Politics" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubePoliticsReport: YoutubeNicheReport = {
  niche: "Politics",
  region: "global",
  dataAsOf: "2026-10-10",
  updatedAt: "2026-10-10",
  channels: [
    {
      channelName: "Reimer Thoughts by Erich Reimer",
      channelUrl: "https://www.youtube.com/channel/UCaO4aArN90oLLWpiu-1zfUw",
      topic: "Politics, Society",
      subscribers: 115000,
      subsGained30d: 63400,
      growthPct: 122.9,
      viewsGained30d: 2507852,
      channelCreatedAt: "2025-06-01",
    },
    {
      channelName: "HANS",
      channelUrl: "https://www.youtube.com/channel/UChlBdEx0pwDXpG13VSxe-KQ",
      topic: "Society, Politics",
      subscribers: 77300,
      subsGained30d: 42500,
      growthPct: 122.1,
      viewsGained30d: 4254229,
      channelCreatedAt: "2018-01-09",
    },
    {
      channelName: "Malwa Abhitak मालवा अभीतक (सबसे तेज खबरे)",
      channelUrl: "https://www.youtube.com/channel/UCZF8JMVuSpQVJwceqhyQB4A",
      topic: "Society, Politics",
      subscribers: 52400,
      subsGained30d: 28400,
      growthPct: 118.3,
      viewsGained30d: 12957017,
      channelCreatedAt: "2014-01-25",
    },
    {
      channelName: "邓洪说法 - 律師解讀美國時事法律新聞",
      channelUrl: "https://www.youtube.com/channel/UCtRTNrm3Fdu1G5Psrg6xptA",
      topic: "Politics, Society",
      subscribers: 85700,
      subsGained30d: 36300,
      growthPct: 73.5,
      viewsGained30d: 2408461,
      channelCreatedAt: "2010-02-03",
    },
    {
      channelName: "Cortes Investigates",
      channelUrl: "https://www.youtube.com/channel/UCWEGJtDun_ilgcZKITVm0Zg",
      topic: "Politics, Society",
      subscribers: 64200,
      subsGained30d: 25500,
      growthPct: 65.9,
      viewsGained30d: 2240931,
      channelCreatedAt: "2011-10-06",
    },
    {
      channelName: "DIASZ",
      channelUrl: "https://www.youtube.com/channel/UC7RqfSAxL9bU7gjHjpiFENg",
      topic: "Society, Politics",
      subscribers: 76700,
      subsGained30d: 29900,
      growthPct: 63.9,
      viewsGained30d: 39045656,
      channelCreatedAt: "2025-01-31",
    },
    {
      channelName: "Hines On Air Podcast",
      channelUrl: "https://www.youtube.com/channel/UCVCtOsZ6jBiimvEy7MHVifQ",
      topic: "Politics, Society",
      subscribers: 53700,
      subsGained30d: 20300,
      growthPct: 60.8,
      viewsGained30d: 465764,
      channelCreatedAt: "2024-01-18",
    },
    {
      channelName: "Independência Financeira",
      channelUrl: "https://www.youtube.com/channel/UCQS_rrl4VVwUs_Gld8S9dvQ",
      topic: "Politics, Society",
      subscribers: 98800,
      subsGained30d: 33800,
      growthPct: 52.0,
      viewsGained30d: 20267365,
      channelCreatedAt: "2011-12-27",
    },
    {
      channelName: "corte compilados",
      channelUrl: "https://www.youtube.com/channel/UCDPgpJrkELl7EtrXtS36NaA",
      topic: "Society, Politics",
      subscribers: 66200,
      subsGained30d: 22100,
      growthPct: 50.1,
      viewsGained30d: 17582602,
      channelCreatedAt: "2021-06-01",
    },
    {
      channelName: "Fight for Canada",
      channelUrl: "https://www.youtube.com/channel/UCMxzgAW2C3g07KTJGCzlP3A",
      topic: "Politics, Society",
      subscribers: 60600,
      subsGained30d: 20000,
      growthPct: 49.3,
      viewsGained30d: 7189187,
      channelCreatedAt: "2025-06-19",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Reimer Thoughts by Erich Reimer",
    note: "a newer channel (created 2025) that gained 63,400 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
