// Single source of truth for the YouTube Boxing channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Boxing" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeBoxingReport: YoutubeNicheReport = {
  niche: "Boxing",
  region: "global",
  dataAsOf: "2026-10-06",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Toxic Media",
      channelUrl: "https://www.youtube.com/channel/UCpkJNz0pd8lClTY7-ad9koQ",
      topic: "Boxing, Entertainment",
      subscribers: 72600,
      subsGained30d: 3000,
      growthPct: 4.3,
      viewsGained30d: 11944588,
      channelCreatedAt: "2022-06-13",
    },
    {
      channelName: "Yelloworks Podcasts",
      channelUrl: "https://www.youtube.com/channel/UCFsnrxz2WeturNgI5_1O4Jw",
      topic: "Entertainment, Boxing",
      subscribers: 111000,
      subsGained30d: 3000,
      growthPct: 2.8,
      viewsGained30d: 2032144,
      channelCreatedAt: "2023-07-12",
    },
    {
      channelName: "Terry Stone Connection",
      channelUrl: "https://www.youtube.com/channel/UClBjVrwflmntwCrbyC5QHzQ",
      topic: "Entertainment, Boxing",
      subscribers: 172000,
      subsGained30d: 2000,
      growthPct: 1.2,
      viewsGained30d: 1587492,
      channelCreatedAt: "2023-08-31",
    },
    {
      channelName: "EpicPlay Zone",
      channelUrl: "https://www.youtube.com/channel/UCtmTw4q6DDXXutL1PPnXjhQ",
      topic: "Boxing, Sport",
      subscribers: 112000,
      subsGained30d: 1000,
      growthPct: 0.9,
      viewsGained30d: 2911551,
      channelCreatedAt: "2025-11-15",
    },
    {
      channelName: "Global Sports Clip",
      channelUrl: "https://www.youtube.com/channel/UCUGBrp01jRaxBjW72FDyE8g",
      topic: "Sport, Boxing",
      subscribers: 68600,
      subsGained30d: 300,
      growthPct: 0.4,
      viewsGained30d: 36758,
      channelCreatedAt: "2023-02-28",
    },
    {
      channelName: "Barbershop Conversations",
      channelUrl: "https://www.youtube.com/channel/UCk9XU-w3MOsJMEsiNk7rX1g",
      topic: "Boxing, Sport",
      subscribers: 76800,
      subsGained30d: 100,
      growthPct: 0.1,
      viewsGained30d: 3151,
      channelCreatedAt: "2014-03-16",
    },
    {
      channelName: "ТИЛЭКС",
      channelUrl: "https://www.youtube.com/channel/UC5nx4a3ZRjl0qXDMhMdKq6g",
      topic: "Entertainment, Boxing",
      subscribers: 483000,
      subsGained30d: 0,
      growthPct: 0.0,
      viewsGained30d: 401330,
      channelCreatedAt: "2016-01-26",
    },
    {
      channelName: "ADE BANGOR",
      channelUrl: "https://www.youtube.com/channel/UCFoYjBphlcOW5CvzZRLA5lA",
      topic: "Boxing, Entertainment",
      subscribers: 125000,
      subsGained30d: 0,
      growthPct: 0.0,
      viewsGained30d: 6776,
      channelCreatedAt: "2016-03-15",
    },
    {
      channelName: "Jon Marianek",
      channelUrl: "https://www.youtube.com/channel/UCeI5j-iTz9wQ69l_c4VAz_Q",
      topic: "Boxing, Lifestyle (sociology)",
      subscribers: 1010000,
      subsGained30d: 0,
      growthPct: 0.0,
      viewsGained30d: 1064746,
      channelCreatedAt: "2012-02-03",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Toxic Media",
    note: "an established channel (created 2022) that gained 3,000 subscribers in 30 days, a 4.3% increase over its subscriber base a month earlier",
  },
};
