// Single source of truth for the YouTube Sport channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Sport" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeSportsReport: YoutubeNicheReport = {
  niche: "Sport",
  region: "global",
  dataAsOf: "2026-10-10",
  updatedAt: "2026-10-10",
  channels: [
    {
      channelName: "Artex",
      channelUrl: "https://www.youtube.com/channel/UCsntXZKABoxqvWmdwDxdONA",
      topic: "Association football, Sport",
      subscribers: 161000,
      subsGained30d: 123700,
      growthPct: 331.6,
      viewsGained30d: 41167581,
      channelCreatedAt: "2019-08-31",
    },
    {
      channelName: "Crest Count",
      channelUrl: "https://www.youtube.com/channel/UCZkxJCXJ4yYM8YX3ogXX5pQ",
      topic: "Entertainment, Sport",
      subscribers: 127000,
      subsGained30d: 77200,
      growthPct: 155.0,
      viewsGained30d: 2545389,
      channelCreatedAt: "2025-11-18",
    },
    {
      channelName: "SHORTS LM",
      channelUrl: "https://www.youtube.com/channel/UCixGm7bCi8jawA4XRdbbbQA",
      topic: "Sport, Association football",
      subscribers: 82000,
      subsGained30d: 40800,
      growthPct: 99.0,
      viewsGained30d: 127946923,
      channelCreatedAt: "2026-01-16",
    },
    {
      channelName: "KING PLAYER",
      channelUrl: "https://www.youtube.com/channel/UCrhzIFmFwvb9Xegt_q561aw",
      topic: "Video game culture, Sports game",
      subscribers: 119000,
      subsGained30d: 54100,
      growthPct: 83.4,
      viewsGained30d: 43295568,
      channelCreatedAt: "2020-02-01",
    },
    {
      channelName: "R PES GAMING",
      channelUrl: "https://www.youtube.com/channel/UC0sKozOrglalgTLlsne6BlQ",
      topic: "Video game culture, Sports game",
      subscribers: 102000,
      subsGained30d: 44400,
      growthPct: 77.1,
      viewsGained30d: 2649876,
      channelCreatedAt: "2020-05-16",
    },
    {
      channelName: "GD KAI YT",
      channelUrl: "https://www.youtube.com/channel/UC5h_Q7VlX2GpnN7Zl7sYS3g",
      topic: "Sport, Entertainment",
      subscribers: 106000,
      subsGained30d: 42200,
      growthPct: 66.1,
      viewsGained30d: 5022947,
      channelCreatedAt: "2024-11-21",
    },
    {
      channelName: "yasinogabuga",
      channelUrl: "https://www.youtube.com/channel/UCb0L1jbQytUliLqX7WW62-g",
      topic: "Association football, Sport",
      subscribers: 76400,
      subsGained30d: 29200,
      growthPct: 61.9,
      viewsGained30d: 15686053,
      channelCreatedAt: "2020-08-21",
    },
    {
      channelName: "Full.90",
      channelUrl: "https://www.youtube.com/channel/UCyLJnUsaxp8O9eH8-dWgNeg",
      topic: "Association football, Sport",
      subscribers: 66600,
      subsGained30d: 25300,
      growthPct: 61.3,
      viewsGained30d: 26573077,
      channelCreatedAt: "2025-07-23",
    },
    {
      channelName: "football ⚽",
      channelUrl: "https://www.youtube.com/channel/UCH8kjkJHvxPcNjO01hok-OQ",
      topic: "Association football, Sport",
      subscribers: 53100,
      subsGained30d: 19800,
      growthPct: 59.5,
      viewsGained30d: 8991747,
      channelCreatedAt: "2025-08-14",
    },
    {
      channelName: "Sikisik",
      channelUrl: "https://www.youtube.com/channel/UCFjRajMwAYdMIPwxPnGJ0YA",
      topic: "Sport, Association football",
      subscribers: 109000,
      subsGained30d: 39700,
      growthPct: 57.3,
      viewsGained30d: 116936225,
      channelCreatedAt: "2017-08-19",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Artex",
    note: "an established channel (created 2019) that gained 123,700 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
