// Single source of truth for the YouTube Tourism channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Tourism" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeTourismReport: YoutubeNicheReport = {
  niche: "Tourism",
  region: "global",
  dataAsOf: "2026-10-09",
  updatedAt: "2026-10-09",
  channels: [
    {
      channelName: "Haida în Lume",
      channelUrl: "https://www.youtube.com/channel/UCAnpgeqGxTN-00zJP0CCoJg",
      topic: "Tourism, Lifestyle (sociology)",
      subscribers: 337000,
      subsGained30d: 136000,
      growthPct: 67.7,
      viewsGained30d: 544001662,
      channelCreatedAt: "2021-09-11",
    },
    {
      channelName: "Don | The Bearded Backpacker",
      channelUrl: "https://www.youtube.com/channel/UCvSARfr1T8LxH5ukdF3DpIw",
      topic: "Tourism, Lifestyle (sociology)",
      subscribers: 77700,
      subsGained30d: 23700,
      growthPct: 43.9,
      viewsGained30d: 5114640,
      channelCreatedAt: "2024-05-30",
    },
    {
      channelName: "Sagar and Ami",
      channelUrl: "https://www.youtube.com/channel/UCfxBixgMCpAOImDX2Tm5gDw",
      topic: "Tourism, Lifestyle (sociology)",
      subscribers: 83800,
      subsGained30d: 24800,
      growthPct: 42.0,
      viewsGained30d: 102043105,
      channelCreatedAt: "2017-06-08",
    },
    {
      channelName: "Onemig Bondoc",
      channelUrl: "https://www.youtube.com/channel/UCzIE0ZrEa0UJZAl649ZaQuA",
      topic: "Tourism, Lifestyle (sociology)",
      subscribers: 99200,
      subsGained30d: 27900,
      growthPct: 39.1,
      viewsGained30d: 2963760,
      channelCreatedAt: "2025-12-05",
    },
    {
      channelName: "Chris Paul Lawlor",
      channelUrl: "https://www.youtube.com/channel/UC3c2NACY0bR4kYSe5rsGTKw",
      topic: "Lifestyle (sociology), Tourism",
      subscribers: 55300,
      subsGained30d: 15200,
      growthPct: 37.9,
      viewsGained30d: 3494092,
      channelCreatedAt: "2017-06-02",
    },
    {
      channelName: "Dream The Falls",
      channelUrl: "https://www.youtube.com/channel/UCI9E2HvV5JLioFHQTj6Eoyw",
      topic: "Lifestyle (sociology), Tourism",
      subscribers: 341000,
      subsGained30d: 87000,
      growthPct: 34.3,
      viewsGained30d: 106854759,
      channelCreatedAt: "2025-08-04",
    },
    {
      channelName: "Meher Mudassar Maghu",
      channelUrl: "https://www.youtube.com/channel/UCWm75fmHP9hG1HyFLpKJH9Q",
      topic: "Lifestyle (sociology), Tourism",
      subscribers: 65200,
      subsGained30d: 15800,
      growthPct: 32.0,
      viewsGained30d: 14823811,
      channelCreatedAt: "2015-11-24",
    },
    {
      channelName: "FUNFAIR VLOGS",
      channelUrl: "https://www.youtube.com/channel/UC6D5ZiRbKcLHoOD6DTsgPsQ",
      topic: "Tourism, Lifestyle (sociology)",
      subscribers: 178000,
      subsGained30d: 41000,
      growthPct: 29.9,
      viewsGained30d: 54133451,
      channelCreatedAt: "2022-04-06",
    },
    {
      channelName: "wild Dip",
      channelUrl: "https://www.youtube.com/channel/UC8B7O5hA5Sf4pNgFofl5Ssw",
      topic: "Lifestyle (sociology), Tourism",
      subscribers: 98000,
      subsGained30d: 22000,
      growthPct: 28.9,
      viewsGained30d: 35613942,
      channelCreatedAt: "2025-09-29",
    },
    {
      channelName: "Korea Tourism Organization Manila Office",
      channelUrl: "https://www.youtube.com/channel/UC8Ru2JTfC0rFAAKhqceB_Fg",
      topic: "Lifestyle (sociology), Tourism",
      subscribers: 56400,
      subsGained30d: 12400,
      growthPct: 28.2,
      viewsGained30d: 142363,
      channelCreatedAt: "2019-11-18",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Haida în Lume",
    note: "an established channel (created 2021) that gained 136,000 subscribers in 30 days, a 67.7% increase over its subscriber base a month earlier",
  },
};
