// Single source of truth for the YouTube Country music channel growth report
// (part of Music).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Country music" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeCountryMusicSubReport: YoutubeSubgenreReport = {
  subgenre: "Country music",
  parentCategory: "Music",
  parentSlug: "music",
  region: "global",
  dataAsOf: "2026-10-09",
  updatedAt: "2026-10-09",
  channels: [
    {
      channelName: "Dusty Country",
      channelUrl: "https://www.youtube.com/channel/UC0FXPwxgSzIUOMmqF9fa7-w",
      topic: "Music, Country music",
      subscribers: 61200,
      subsGained30d: 4700,
      growthPct: 8.3,
      viewsGained30d: 5225032,
      channelCreatedAt: "2025-10-15",
    },
    {
      channelName: "Diesel Country",
      channelUrl: "https://www.youtube.com/channel/UCZuT4yT-IFXw_h4CObdVSqQ",
      topic: "Music, Country music",
      subscribers: 78900,
      subsGained30d: 5800,
      growthPct: 7.9,
      viewsGained30d: 5742809,
      channelCreatedAt: "2025-08-26",
    },
    {
      channelName: "Golden Country Memories",
      channelUrl: "https://www.youtube.com/channel/UCK4kG8EUiwUWNU3VnkFxVyw",
      topic: "Music, Country music",
      subscribers: 85400,
      subsGained30d: 5200,
      growthPct: 6.5,
      viewsGained30d: 4772222,
      channelCreatedAt: "2025-12-01",
    },
    {
      channelName: "Country Angel",
      channelUrl: "https://www.youtube.com/channel/UCDUahJ_UA2prGH2_lnGW1pA",
      topic: "Country music, Music",
      subscribers: 59000,
      subsGained30d: 2000,
      growthPct: 3.5,
      viewsGained30d: 4084808,
      channelCreatedAt: "2025-05-04",
    },
    {
      channelName: "Country Boots Music",
      channelUrl: "https://www.youtube.com/channel/UCxnvMb3tmn30kL-7M3GhqBw",
      topic: "Music, Country music",
      subscribers: 51100,
      subsGained30d: 1700,
      growthPct: 3.4,
      viewsGained30d: 1181066,
      channelCreatedAt: "2025-08-23",
    },
    {
      channelName: "Murphy Campbell",
      channelUrl: "https://www.youtube.com/channel/UCn34p7SgtX2vk502qt7EhJw",
      topic: "Music, Country music",
      subscribers: 53500,
      subsGained30d: 1300,
      growthPct: 2.5,
      viewsGained30d: 361796,
      channelCreatedAt: "2022-04-02",
    },
    {
      channelName: "Backwoods Bluegrass Band",
      channelUrl: "https://www.youtube.com/channel/UC58wsHYBBTwwZ5Y1b_UgwOw",
      topic: "Music, Country music",
      subscribers: 63400,
      subsGained30d: 1400,
      growthPct: 2.3,
      viewsGained30d: 1420345,
      channelCreatedAt: "2021-01-29",
    },
    {
      channelName: "Country\\'s Family Reunion",
      channelUrl: "https://www.youtube.com/channel/UCVh1ZR1OrEnni7HSbaDGnIg",
      topic: "Music, Country music",
      subscribers: 269000,
      subsGained30d: 5000,
      growthPct: 1.9,
      viewsGained30d: 11326763,
      channelCreatedAt: "2010-02-10",
    },
    {
      channelName: "CMA",
      channelUrl: "https://www.youtube.com/channel/UCP8NpF8uAYjQkoVbHREss_w",
      topic: "Music, Country music",
      subscribers: 225000,
      subsGained30d: 4000,
      growthPct: 1.8,
      viewsGained30d: 14092054,
      channelCreatedAt: "2007-08-22",
    },
    {
      channelName: "DN Anthems",
      channelUrl: "https://www.youtube.com/channel/UC-g2Rb_rM1j6fj0H23lEiXg",
      topic: "Music, Country music",
      subscribers: 99800,
      subsGained30d: 1600,
      growthPct: 1.6,
      viewsGained30d: 886629,
      channelCreatedAt: "2016-11-19",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Music niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Dusty Country",
    note: "a newer channel (created 2025) that gained 4,700 subscribers in 30 days, a 8.3% increase over its subscriber base a month earlier",
  },
};
