// Single source of truth for the YouTube Association football channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Association football" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeSoccerReport: YoutubeNicheReport = {
  niche: "Association football",
  region: "global",
  dataAsOf: "2026-10-07",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Artex",
      channelUrl: "https://www.youtube.com/channel/UCsntXZKABoxqvWmdwDxdONA",
      topic: "Sport, Association football",
      subscribers: 155000,
      subsGained30d: 118700,
      growthPct: 327.0,
      viewsGained30d: 39927061,
      channelCreatedAt: "2019-08-31",
    },
    {
      channelName: "SHORTS LM",
      channelUrl: "https://www.youtube.com/channel/UCixGm7bCi8jawA4XRdbbbQA",
      topic: "Sport, Association football",
      subscribers: 75200,
      subsGained30d: 34000,
      growthPct: 82.5,
      viewsGained30d: 108048881,
      channelCreatedAt: "2026-01-16",
    },
    {
      channelName: "football ⚽",
      channelUrl: "https://www.youtube.com/channel/UCH8kjkJHvxPcNjO01hok-OQ",
      topic: "Sport, Association football",
      subscribers: 51900,
      subsGained30d: 20400,
      growthPct: 64.8,
      viewsGained30d: 9954382,
      channelCreatedAt: "2025-08-14",
    },
    {
      channelName: "yasinogabuga",
      channelUrl: "https://www.youtube.com/channel/UCb0L1jbQytUliLqX7WW62-g",
      topic: "Sport, Association football",
      subscribers: 74900,
      subsGained30d: 28000,
      growthPct: 59.7,
      viewsGained30d: 14859218,
      channelCreatedAt: "2020-08-21",
    },
    {
      channelName: "Full.90",
      channelUrl: "https://www.youtube.com/channel/UCyLJnUsaxp8O9eH8-dWgNeg",
      topic: "Sport, Association football",
      subscribers: 64000,
      subsGained30d: 22700,
      growthPct: 55.0,
      viewsGained30d: 23123854,
      channelCreatedAt: "2025-07-23",
    },
    {
      channelName: "cl7tch",
      channelUrl: "https://www.youtube.com/channel/UCoShywrn8hWRdsA5FRlpt2A",
      topic: "Sport, Association football",
      subscribers: 69300,
      subsGained30d: 21500,
      growthPct: 45.0,
      viewsGained30d: 12918325,
      channelCreatedAt: "2023-02-20",
    },
    {
      channelName: "WL gamer",
      channelUrl: "https://www.youtube.com/channel/UCjCE_5Bi4OuohmW4tQiU4Fg",
      topic: "Association football, Sport",
      subscribers: 143000,
      subsGained30d: 44300,
      growthPct: 44.9,
      viewsGained30d: 244621,
      channelCreatedAt: "2024-01-20",
    },
    {
      channelName: "Skillz Aep",
      channelUrl: "https://www.youtube.com/channel/UCade3HXb8JTmCW7r3zpglVQ",
      topic: "Sport, Association football",
      subscribers: 83800,
      subsGained30d: 23200,
      growthPct: 38.3,
      viewsGained30d: 19384863,
      channelCreatedAt: "2025-06-10",
    },
    {
      channelName: "neha shah",
      channelUrl: "https://www.youtube.com/channel/UCmQrD2dEwVF7LUxDcM4_jsQ",
      topic: "Association football, Sport",
      subscribers: 74800,
      subsGained30d: 19600,
      growthPct: 35.5,
      viewsGained30d: 7671548,
      channelCreatedAt: "2025-12-29",
    },
    {
      channelName: "suoni dalle curve",
      channelUrl: "https://www.youtube.com/channel/UCZ9WTBinahnOaYZxo6pdUvw",
      topic: "Association football, Sport",
      subscribers: 53400,
      subsGained30d: 13800,
      growthPct: 34.8,
      viewsGained30d: 70486034,
      channelCreatedAt: "2011-11-19",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Artex",
    note: "an established channel (created 2019) that gained 118,700 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
