// Single source of truth for the YouTube Fashion channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Fashion" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeFashionReport: YoutubeNicheReport = {
  niche: "Fashion",
  region: "global",
  dataAsOf: "2026-10-06",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "BarQode Fashion",
      channelUrl: "https://www.youtube.com/channel/UCnOca60yTdOxv2W9es0FLUg",
      topic: "Fashion, Lifestyle (sociology)",
      subscribers: 87600,
      subsGained30d: 32800,
      growthPct: 59.9,
      viewsGained30d: 37812587,
      channelCreatedAt: "2022-09-13",
    },
    {
      channelName: "Midlife Posh Closet",
      channelUrl: "https://www.youtube.com/channel/UC6kK_zoyGp1LcwN520Nk7TA",
      topic: "Lifestyle (sociology), Fashion",
      subscribers: 141000,
      subsGained30d: 51300,
      growthPct: 57.2,
      viewsGained30d: 505265,
      channelCreatedAt: "2022-12-01",
    },
    {
      channelName: "Agus Ngonten",
      channelUrl: "https://www.youtube.com/channel/UCq1oEzDHX1SUCn7AedepfHg",
      topic: "Fashion, Lifestyle (sociology)",
      subscribers: 113000,
      subsGained30d: 39300,
      growthPct: 53.3,
      viewsGained30d: 81699609,
      channelCreatedAt: "2025-04-09",
    },
    {
      channelName: "Style Alchemy By Priyanshi",
      channelUrl: "https://www.youtube.com/channel/UC7dwIrrYuOOs1LyLSXDHFHQ",
      topic: "Fashion, Lifestyle (sociology)",
      subscribers: 65400,
      subsGained30d: 22600,
      growthPct: 52.8,
      viewsGained30d: 19016483,
      channelCreatedAt: "2024-07-30",
    },
    {
      channelName: "KaRtIkAy",
      channelUrl: "https://www.youtube.com/channel/UCk7Ds_OAzpmcnJy_zAcX_PQ",
      topic: "Lifestyle (sociology), Fashion",
      subscribers: 292000,
      subsGained30d: 96000,
      growthPct: 49.0,
      viewsGained30d: 135370552,
      channelCreatedAt: "2017-12-01",
    },
    {
      channelName: "Lekha kumar",
      channelUrl: "https://www.youtube.com/channel/UCWTWAdb2TmmtD7rrn19KzDg",
      topic: "Lifestyle (sociology), Fashion",
      subscribers: 104000,
      subsGained30d: 33900,
      growthPct: 48.4,
      viewsGained30d: 72810714,
      channelCreatedAt: "2019-03-10",
    },
    {
      channelName: "びすこ visco",
      channelUrl: "https://www.youtube.com/channel/UCKhv4yLR1e-kYJ1n1xM0sPw",
      topic: "Lifestyle (sociology), Fashion",
      subscribers: 54900,
      subsGained30d: 17500,
      growthPct: 46.8,
      viewsGained30d: 1883534,
      channelCreatedAt: "2023-08-24",
    },
    {
      channelName: "Justina",
      channelUrl: "https://www.youtube.com/channel/UCQ8SRxehWl_cbboVCI3MDpQ",
      topic: "Fashion, Lifestyle (sociology)",
      subscribers: 77800,
      subsGained30d: 24400,
      growthPct: 45.7,
      viewsGained30d: 5731361,
      channelCreatedAt: "2022-06-19",
    },
    {
      channelName: "Emily Bianca",
      channelUrl: "https://www.youtube.com/channel/UC61pWjEP87hvofrfVDGhlFQ",
      topic: "Lifestyle (sociology), Fashion",
      subscribers: 221000,
      subsGained30d: 67000,
      growthPct: 43.5,
      viewsGained30d: 28701730,
      channelCreatedAt: "2025-03-11",
    },
    {
      channelName: "Ashanti Finds",
      channelUrl: "https://www.youtube.com/channel/UCQ37I3RXFxJcYZeUX1frdWA",
      topic: "Fashion, Lifestyle (sociology)",
      subscribers: 66200,
      subsGained30d: 18900,
      growthPct: 40.0,
      viewsGained30d: 10913690,
      channelCreatedAt: "2017-10-08",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "BarQode Fashion",
    note: "an established channel (created 2022) that gained 32,800 subscribers in 30 days, a 59.9% increase over its subscriber base a month earlier",
  },
};
