// Single source of truth for the YouTube Film channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Film" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeFilmReport: YoutubeNicheReport = {
  niche: "Film",
  region: "global",
  dataAsOf: "2026-10-09",
  updatedAt: "2026-10-09",
  channels: [
    {
      channelName: "Chittu Kuruvi",
      channelUrl: "https://www.youtube.com/channel/UCkEY39gdZyIkJPSiEVelj0w",
      topic: "Film, Entertainment",
      subscribers: 154000,
      subsGained30d: 123200,
      growthPct: 400.0,
      viewsGained30d: 12875369,
      channelCreatedAt: "2017-12-31",
    },
    {
      channelName: "瑤瑤AI短劇",
      channelUrl: "https://www.youtube.com/channel/UC_wFVsA9do4LfmKudQKvGYA",
      topic: "Entertainment, Film",
      subscribers: 77700,
      subsGained30d: 53700,
      growthPct: 223.7,
      viewsGained30d: 13550680,
      channelCreatedAt: "2026-04-23",
    },
    {
      channelName: "NK Stories Zone",
      channelUrl: "https://www.youtube.com/channel/UCqGR0h9xSyjLkRtVozLincg",
      topic: "Entertainment, Film",
      subscribers: 82800,
      subsGained30d: 54900,
      growthPct: 196.8,
      viewsGained30d: 11504182,
      channelCreatedAt: "2020-07-27",
    },
    {
      channelName: "AMAN SHAH",
      channelUrl: "https://www.youtube.com/channel/UClylm6_8puy1ZQ9wwXQH9yw",
      topic: "Film, Entertainment",
      subscribers: 106000,
      subsGained30d: 67600,
      growthPct: 176.0,
      viewsGained30d: 19894286,
      channelCreatedAt: "2025-06-14",
    },
    {
      channelName: "Snip Snip France",
      channelUrl: "https://www.youtube.com/channel/UC1qHzBZuXEyN9g14y1f6-Fg",
      topic: "Entertainment, Film",
      subscribers: 170000,
      subsGained30d: 105300,
      growthPct: 162.8,
      viewsGained30d: 153800848,
      channelCreatedAt: "2026-01-16",
    },
    {
      channelName: "HappyShortTvNO1",
      channelUrl: "https://www.youtube.com/channel/UCymSgemTjY0LHy1HlXzHFkQ",
      topic: "Entertainment, Film",
      subscribers: 85300,
      subsGained30d: 49000,
      growthPct: 135.0,
      viewsGained30d: 11073382,
      channelCreatedAt: "2026-06-03",
    },
    {
      channelName: "星火剧场SuperDrama",
      channelUrl: "https://www.youtube.com/channel/UCLuU2iYXnEFHLqjuLPthtbA",
      topic: "Film, Entertainment",
      subscribers: 78500,
      subsGained30d: 43400,
      growthPct: 123.6,
      viewsGained30d: 23341066,
      channelCreatedAt: "2025-12-19",
    },
    {
      channelName: "Oye Explainer Hindi",
      channelUrl: "https://www.youtube.com/channel/UCSUg0PUeRCbTPFR14cF_9qg",
      topic: "Film, Entertainment",
      subscribers: 52100,
      subsGained30d: 28700,
      growthPct: 122.6,
      viewsGained30d: 12952978,
      channelCreatedAt: "2022-02-25",
    },
    {
      channelName: "AaryanX",
      channelUrl: "https://www.youtube.com/channel/UCU2IXDLt7nJ9c4-_XHCLZTA",
      topic: "Film, Entertainment",
      subscribers: 58100,
      subsGained30d: 31800,
      growthPct: 120.9,
      viewsGained30d: 8660720,
      channelCreatedAt: "2017-09-24",
    },
    {
      channelName: "rapper wonhee! ★",
      channelUrl: "https://www.youtube.com/channel/UCPgQBXUa4_vChJAa9fgaCvQ",
      topic: "Entertainment, Film",
      subscribers: 104000,
      subsGained30d: 55800,
      growthPct: 115.8,
      viewsGained30d: 13162991,
      channelCreatedAt: "2018-06-30",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Chittu Kuruvi",
    note: "an established channel (created 2017) that gained 123,200 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
