// Single source of truth for the YouTube Basketball channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Basketball" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeBasketballReport: YoutubeNicheReport = {
  niche: "Basketball",
  region: "global",
  dataAsOf: "2026-10-08",
  updatedAt: "2026-10-08",
  channels: [
    {
      channelName: "Hayden Jones",
      channelUrl: "https://www.youtube.com/channel/UCUgouh8Az3p3fzyCJvNs-eg",
      topic: "Sport, Basketball",
      subscribers: 1920000,
      subsGained30d: 280000,
      growthPct: 17.1,
      viewsGained30d: 32768520,
      channelCreatedAt: "2017-04-16",
    },
    {
      channelName: "Bernadine Moen",
      channelUrl: "https://www.youtube.com/channel/UCcsb3MfmP--lFYVNOUS4ggQ",
      topic: "Basketball, Sport",
      subscribers: 56500,
      subsGained30d: 7800,
      growthPct: 16.0,
      viewsGained30d: 8845676,
      channelCreatedAt: "2025-07-19",
    },
    {
      channelName: "ZedBall",
      channelUrl: "https://www.youtube.com/channel/UCQaUyVUXDEHS6m1KWW4K8VA",
      topic: "Sport, Basketball",
      subscribers: 220000,
      subsGained30d: 29000,
      growthPct: 15.2,
      viewsGained30d: 22730522,
      channelCreatedAt: "2024-10-27",
    },
    {
      channelName: "Philadelphia 76ers",
      channelUrl: "https://www.youtube.com/channel/UC5qJUyng_ezl0TVjVJFqtfQ",
      topic: "Sport, Basketball",
      subscribers: 124000,
      subsGained30d: 16000,
      growthPct: 14.8,
      viewsGained30d: 3274012,
      channelCreatedAt: "2006-06-12",
    },
    {
      channelName: "농구분석가 농떼르만 [김진용]",
      channelUrl: "https://www.youtube.com/channel/UCF7m9V1DiHORGTmNrkHrT5Q",
      topic: "Basketball, Sport",
      subscribers: 65600,
      subsGained30d: 8200,
      growthPct: 14.3,
      viewsGained30d: 18987634,
      channelCreatedAt: "2021-03-03",
    },
    {
      channelName: "Jayden Beloti",
      channelUrl: "https://www.youtube.com/channel/UCR7rAVnTwwNkGpanJb28qvw",
      topic: "Sport, Basketball",
      subscribers: 134000,
      subsGained30d: 16000,
      growthPct: 13.6,
      viewsGained30d: 11852840,
      channelCreatedAt: "2014-06-15",
    },
    {
      channelName: "SAVI Coaching",
      channelUrl: "https://www.youtube.com/channel/UCeWWGsIbnBQW0tdJTObakKg",
      topic: "Basketball, Sport",
      subscribers: 71300,
      subsGained30d: 8000,
      growthPct: 12.6,
      viewsGained30d: 645932,
      channelCreatedAt: "2021-04-07",
    },
    {
      channelName: "The Phillips Brothers",
      channelUrl: "https://www.youtube.com/channel/UCvFdSjbqpWSCjQFutJOhyRA",
      topic: "Basketball, Sport",
      subscribers: 89300,
      subsGained30d: 9700,
      growthPct: 12.2,
      viewsGained30d: 7650966,
      channelCreatedAt: "2011-10-11",
    },
    {
      channelName: "Breakaway Clips",
      channelUrl: "https://www.youtube.com/channel/UCHLQXoPj6jCe7KwxGzPaTsA",
      topic: "Basketball, Sport",
      subscribers: 108000,
      subsGained30d: 11400,
      growthPct: 11.8,
      viewsGained30d: 50289125,
      channelCreatedAt: "2025-12-17",
    },
    {
      channelName: "Connor Essegian",
      channelUrl: "https://www.youtube.com/channel/UCOt7j6WhKaDYHCWp2_lPAng",
      topic: "Basketball, Sport",
      subscribers: 55700,
      subsGained30d: 5700,
      growthPct: 11.4,
      viewsGained30d: 2479827,
      channelCreatedAt: "2024-05-05",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Hayden Jones",
    note: "an established channel (created 2017) that gained 280,000 subscribers in 30 days, a 17.1% increase over its subscriber base a month earlier",
  },
};
