// Single source of truth for the YouTube Cricket channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Cricket" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeCricketReport: YoutubeNicheReport = {
  niche: "Cricket",
  region: "global",
  dataAsOf: "2026-10-08",
  updatedAt: "2026-10-08",
  channels: [
    {
      channelName: "Sports Cricket Hub",
      channelUrl: "https://www.youtube.com/channel/UCjg4n1MdNfyenSj0tw2g5TA",
      topic: "Cricket, Sport",
      subscribers: 116000,
      subsGained30d: 17000,
      growthPct: 17.2,
      viewsGained30d: 8561360,
      channelCreatedAt: "2026-02-26",
    },
    {
      channelName: "AAM INSAAN",
      channelUrl: "https://www.youtube.com/channel/UCxXpG1IzuYDeQnRt-QNSIjw",
      topic: "Sport, Cricket",
      subscribers: 74500,
      subsGained30d: 10400,
      growthPct: 16.2,
      viewsGained30d: 30957684,
      channelCreatedAt: "2023-06-23",
    },
    {
      channelName: "Crick Media",
      channelUrl: "https://www.youtube.com/channel/UClSCcU9CgyquaRSuSsCQa9w",
      topic: "Sport, Cricket",
      subscribers: 58700,
      subsGained30d: 6400,
      growthPct: 12.2,
      viewsGained30d: 3961404,
      channelCreatedAt: "2025-06-26",
    },
    {
      channelName: "SH cric Talk",
      channelUrl: "https://www.youtube.com/channel/UCFvO6YuvDulkULDinP_fglg",
      topic: "Sport, Cricket",
      subscribers: 83500,
      subsGained30d: 9000,
      growthPct: 12.1,
      viewsGained30d: 40668451,
      channelCreatedAt: "2024-06-24",
    },
    {
      channelName: "hungerforcricket",
      channelUrl: "https://www.youtube.com/channel/UCkXo1JdGnjxrOrZzWHtYTQQ",
      topic: "Sport, Cricket",
      subscribers: 318000,
      subsGained30d: 34000,
      growthPct: 12.0,
      viewsGained30d: 221791444,
      channelCreatedAt: "2018-03-06",
    },
    {
      channelName: "Rahul Sah crick react",
      channelUrl: "https://www.youtube.com/channel/UCLTzi5w0q_Q6aSZqzzdZb_Q",
      topic: "Sport, Cricket",
      subscribers: 76600,
      subsGained30d: 7000,
      growthPct: 10.1,
      viewsGained30d: 11730895,
      channelCreatedAt: "2022-12-24",
    },
    {
      channelName: "CricMemeSter",
      channelUrl: "https://www.youtube.com/channel/UCjoAwFX6n5dy4nl_X0-mi9A",
      topic: "Cricket, Sport",
      subscribers: 515000,
      subsGained30d: 45000,
      growthPct: 9.6,
      viewsGained30d: 25095639,
      channelCreatedAt: "2019-06-26",
    },
    {
      channelName: "RICKET LK",
      channelUrl: "https://www.youtube.com/channel/UCeFpMHjzvTU_4ISIeKNhSew",
      topic: "Cricket, Sport",
      subscribers: 78100,
      subsGained30d: 6200,
      growthPct: 8.6,
      viewsGained30d: 2009641,
      channelCreatedAt: "2020-06-13",
    },
    {
      channelName: "World Championship Of Legends",
      channelUrl: "https://www.youtube.com/channel/UC_-8LXJlcSQB25IAMbzs1vA",
      topic: "Cricket, Sport",
      subscribers: 59800,
      subsGained30d: 4500,
      growthPct: 8.1,
      viewsGained30d: 4800955,
      channelCreatedAt: "2024-04-03",
    },
    {
      channelName: "Jaid\\'s edits",
      channelUrl: "https://www.youtube.com/channel/UChGjwlKuk4_H1CMBAIF-zqA",
      topic: "Cricket, Sport",
      subscribers: 109000,
      subsGained30d: 7000,
      growthPct: 6.9,
      viewsGained30d: 7743523,
      channelCreatedAt: "2025-04-15",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Sports Cricket Hub",
    note: "a newer channel (created 2026) that gained 17,000 subscribers in 30 days, a 17.2% increase over its subscriber base a month earlier",
  },
};
