// Single source of truth for the YouTube Volleyball channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Volleyball" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeVolleyballReport: YoutubeNicheReport = {
  niche: "Volleyball",
  region: "global",
  dataAsOf: "2026-10-10",
  updatedAt: "2026-10-10",
  channels: [
    {
      channelName: "Sultanlar Ligi",
      channelUrl: "https://www.youtube.com/channel/UC5hZ2Zky3_X1zW2J3AdFxWg",
      topic: "Volleyball, Sport",
      subscribers: 52300,
      subsGained30d: 11100,
      growthPct: 26.9,
      viewsGained30d: 29535218,
      channelCreatedAt: "2024-03-27",
    },
    {
      channelName: "VolleyDiblesi",
      channelUrl: "https://www.youtube.com/channel/UCsR4VQq6WcmVgM8nyjrmlLQ",
      topic: "Sport, Volleyball",
      subscribers: 50600,
      subsGained30d: 4800,
      growthPct: 10.5,
      viewsGained30d: 23867749,
      channelCreatedAt: "2025-02-11",
    },
    {
      channelName: "Melissa Airlines",
      channelUrl: "https://www.youtube.com/channel/UC1IDqY7lcMU8bEC7z0zHkRg",
      topic: "Sport, Volleyball",
      subscribers: 102000,
      subsGained30d: 7100,
      growthPct: 7.5,
      viewsGained30d: 22516155,
      channelCreatedAt: "2025-04-09",
    },
    {
      channelName: "Channel JVA",
      channelUrl: "https://www.youtube.com/channel/UCzJWuGYiRQTvS6jg3ZaAoUg",
      topic: "Volleyball, Sport",
      subscribers: 250000,
      subsGained30d: 14000,
      growthPct: 5.9,
      viewsGained30d: 10022064,
      channelCreatedAt: "2015-01-09",
    },
    {
      channelName: "Zehra Gunes Official Page",
      channelUrl: "https://www.youtube.com/channel/UC7ustfb8XipoL6D9rYo8BiQ",
      topic: "Volleyball, Sport",
      subscribers: 198000,
      subsGained30d: 11000,
      growthPct: 5.9,
      viewsGained30d: 19084472,
      channelCreatedAt: "2016-09-23",
    },
    {
      channelName: "Do comment",
      channelUrl: "https://www.youtube.com/channel/UC5tdjlJr2A83ocIhKLQrtsQ",
      topic: "Sport, Volleyball",
      subscribers: 110000,
      subsGained30d: 5000,
      growthPct: 4.8,
      viewsGained30d: 6405427,
      channelCreatedAt: "2021-10-12",
    },
    {
      channelName: "TVF VOLEYBOL TV",
      channelUrl: "https://www.youtube.com/channel/UCTgQ8Bfq3AUuo1vWULdvRKw",
      topic: "Sport, Volleyball",
      subscribers: 237000,
      subsGained30d: 7000,
      growthPct: 3.0,
      viewsGained30d: 2061282,
      channelCreatedAt: "2020-03-11",
    },
    {
      channelName: "Volleyball Mastery",
      channelUrl: "https://www.youtube.com/channel/UCgS1yz9A1N5dahg91_dUVzQ",
      topic: "Volleyball, Sport",
      subscribers: 82000,
      subsGained30d: 2300,
      growthPct: 2.9,
      viewsGained30d: 1805921,
      channelCreatedAt: "2023-01-25",
    },
    {
      channelName: "TVA CHANNEL",
      channelUrl: "https://www.youtube.com/channel/UCDnK6_u8JKLq-Xx_N0GuuUg",
      topic: "Sport, Volleyball",
      subscribers: 332000,
      subsGained30d: 9000,
      growthPct: 2.8,
      viewsGained30d: 6192701,
      channelCreatedAt: "2017-07-21",
    },
    {
      channelName: "punchเชียร์กีฬา",
      channelUrl: "https://www.youtube.com/channel/UCVJ3kJAoz9ODOnnaNsYS71w",
      topic: "Volleyball, Sport",
      subscribers: 59000,
      subsGained30d: 1500,
      growthPct: 2.6,
      viewsGained30d: 2093685,
      channelCreatedAt: "2018-05-31",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Sultanlar Ligi",
    note: "an established channel (created 2024) that gained 11,100 subscribers in 30 days, a 26.9% increase over its subscriber base a month earlier",
  },
};
