// Single source of truth for the YouTube Hobby channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Hobby" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeHobbyReport: YoutubeNicheReport = {
  niche: "Hobby",
  region: "global",
  dataAsOf: "2026-10-09",
  updatedAt: "2026-10-09",
  channels: [
    {
      channelName: "Flex Fact",
      channelUrl: "https://www.youtube.com/channel/UCCRHPtFyp3RrFLojljUwVmA",
      topic: "Hobby, Lifestyle (sociology)",
      subscribers: 453000,
      subsGained30d: 406800,
      growthPct: 880.5,
      viewsGained30d: 16889529,
      channelCreatedAt: "2025-09-20",
    },
    {
      channelName: "Spoorthi Mandapati",
      channelUrl: "https://www.youtube.com/channel/UCsPXJ9ldKevTwPmLrkDHVCA",
      topic: "Hobby, Lifestyle (sociology)",
      subscribers: 230000,
      subsGained30d: 195200,
      growthPct: 560.9,
      viewsGained30d: 17976,
      channelCreatedAt: "2019-08-11",
    },
    {
      channelName: "Knot & Hack Master",
      channelUrl: "https://www.youtube.com/channel/UCqY7eP0MXwL-uYRED-ICuOw",
      topic: "Lifestyle (sociology), Hobby",
      subscribers: 100000,
      subsGained30d: 71300,
      growthPct: 248.4,
      viewsGained30d: 34431956,
      channelCreatedAt: "2025-11-10",
    },
    {
      channelName: "Insha MT",
      channelUrl: "https://www.youtube.com/channel/UClr1vyTAEhanJKv0vNw_Q-w",
      topic: "Lifestyle (sociology), Hobby",
      subscribers: 118000,
      subsGained30d: 81500,
      growthPct: 223.3,
      viewsGained30d: 2815263,
      channelCreatedAt: "2021-07-20",
    },
    {
      channelName: "ADARSH S J",
      channelUrl: "https://www.youtube.com/channel/UCn7Hzz_bs0seh-r0KN8A20g",
      topic: "Lifestyle (sociology), Hobby",
      subscribers: 145000,
      subsGained30d: 97300,
      growthPct: 204.0,
      viewsGained30d: 57961264,
      channelCreatedAt: "2019-05-07",
    },
    {
      channelName: "artist guddu",
      channelUrl: "https://www.youtube.com/channel/UCxwn_YFh9xtVi1kKjyRWeAA",
      topic: "Lifestyle (sociology), Hobby",
      subscribers: 58900,
      subsGained30d: 38600,
      growthPct: 190.1,
      viewsGained30d: 52055063,
      channelCreatedAt: "2026-05-23",
    },
    {
      channelName: "Sam Oeun Art",
      channelUrl: "https://www.youtube.com/channel/UC94UKlsWX25Asb8jsRSc3wg",
      topic: "Hobby, Lifestyle (sociology)",
      subscribers: 69000,
      subsGained30d: 44500,
      growthPct: 181.6,
      viewsGained30d: 50787491,
      channelCreatedAt: "2026-03-20",
    },
    {
      channelName: "Chapter Renovation",
      channelUrl: "https://www.youtube.com/channel/UCGY5Z4BBfGjB489zEEOpn4A",
      topic: "Hobby, Lifestyle (sociology)",
      subscribers: 56500,
      subsGained30d: 35900,
      growthPct: 174.3,
      viewsGained30d: 228695,
      channelCreatedAt: "2022-06-03",
    },
    {
      channelName: "Shruti art",
      channelUrl: "https://www.youtube.com/channel/UCl6CkgOUH0MBpmUZhGw8RSQ",
      topic: "Lifestyle (sociology), Hobby",
      subscribers: 443000,
      subsGained30d: 278000,
      growthPct: 168.5,
      viewsGained30d: 442794133,
      channelCreatedAt: "2021-05-14",
    },
    {
      channelName: "Jessimrcy",
      channelUrl: "https://www.youtube.com/channel/UCJQOrJWUmnM5cChX6PfUJPw",
      topic: "Hobby, Lifestyle (sociology)",
      subscribers: 74700,
      subsGained30d: 44500,
      growthPct: 147.4,
      viewsGained30d: 17644130,
      channelCreatedAt: "2025-11-19",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Flex Fact",
    note: "a newer channel (created 2025) that gained 406,800 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
