// Single source of truth for the YouTube Physical fitness channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Physical fitness" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeFitnessReport: YoutubeNicheReport = {
  niche: "Physical fitness",
  region: "global",
  dataAsOf: "2026-10-06",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Bobbie Dhanush (fp)",
      channelUrl: "https://www.youtube.com/channel/UCo3SUyHOMZVz1S3ZYOK1atQ",
      topic: "Lifestyle (sociology), Physical fitness",
      subscribers: 86500,
      subsGained30d: 17200,
      growthPct: 24.8,
      viewsGained30d: 16342205,
      channelCreatedAt: "2026-02-08",
    },
    {
      channelName: "That Same Guy",
      channelUrl: "https://www.youtube.com/channel/UCTp1U8xfVa0HO5Ancdyhs3Q",
      topic: "Lifestyle (sociology), Physical fitness",
      subscribers: 83500,
      subsGained30d: 14200,
      growthPct: 20.5,
      viewsGained30d: 262089,
      channelCreatedAt: "2025-04-19",
    },
    {
      channelName: "Nicolette IRL",
      channelUrl: "https://www.youtube.com/channel/UC3o2ztcJbE2JmtoxWoaAi8g",
      topic: "Physical fitness, Lifestyle (sociology)",
      subscribers: 54500,
      subsGained30d: 8600,
      growthPct: 18.7,
      viewsGained30d: 3147690,
      channelCreatedAt: "2020-09-30",
    },
    {
      channelName: "AKASH STREET WORK",
      channelUrl: "https://www.youtube.com/channel/UCv-nS_HzWcKyiAANygv-PoQ",
      topic: "Physical fitness, Lifestyle (sociology)",
      subscribers: 175000,
      subsGained30d: 27000,
      growthPct: 18.2,
      viewsGained30d: 9641882,
      channelCreatedAt: "2025-10-29",
    },
    {
      channelName: "Louise Stonham",
      channelUrl: "https://www.youtube.com/channel/UCJ5sxztB7e7ULt5li33TwAQ",
      topic: "Lifestyle (sociology), Physical fitness",
      subscribers: 58200,
      subsGained30d: 6500,
      growthPct: 12.6,
      viewsGained30d: 7754670,
      channelCreatedAt: "2020-05-08",
    },
    {
      channelName: "Abdurahmon workout",
      channelUrl: "https://www.youtube.com/channel/UCGGKvris3UcsiILAdxVjapA",
      topic: "Physical fitness, Lifestyle (sociology)",
      subscribers: 334000,
      subsGained30d: 33000,
      growthPct: 11.0,
      viewsGained30d: 58354055,
      channelCreatedAt: "2024-12-21",
    },
    {
      channelName: "Cortes do Balestrin [OFICIAL]",
      channelUrl: "https://www.youtube.com/channel/UCBPXUbZhvvfEi66WACxxmQg",
      topic: "Physical fitness, Lifestyle (sociology)",
      subscribers: 152000,
      subsGained30d: 15000,
      growthPct: 10.9,
      viewsGained30d: 3572647,
      channelCreatedAt: "2025-06-25",
    },
    {
      channelName: "Varshana Rana 💪",
      channelUrl: "https://www.youtube.com/channel/UCYAWVJyP4JiheL7ws1p7muA",
      topic: "Physical fitness, Lifestyle (sociology)",
      subscribers: 143000,
      subsGained30d: 14000,
      growthPct: 10.9,
      viewsGained30d: 6135974,
      channelCreatedAt: "2021-05-25",
    },
    {
      channelName: "Yoga girl",
      channelUrl: "https://www.youtube.com/channel/UCx5rkT1Gg91_C5cXpf1bdyQ",
      topic: "Lifestyle (sociology), Physical fitness",
      subscribers: 108000,
      subsGained30d: 9900,
      growthPct: 10.1,
      viewsGained30d: 24419289,
      channelCreatedAt: "2024-08-01",
    },
    {
      channelName: "DutchBrahs",
      channelUrl: "https://www.youtube.com/channel/UCiH7FwMpv2RO4X3wKkCUgpg",
      topic: "Physical fitness, Lifestyle (sociology)",
      subscribers: 100000,
      subsGained30d: 9000,
      growthPct: 9.9,
      viewsGained30d: 1291933,
      channelCreatedAt: "2026-02-03",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Bobbie Dhanush (fp)",
    note: "a newer channel (created 2026) that gained 17,200 subscribers in 30 days, a 24.8% increase over its subscriber base a month earlier",
  },
};
