// Single source of truth for the YouTube Military channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Military" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeMilitaryReport: YoutubeNicheReport = {
  niche: "Military",
  region: "global",
  dataAsOf: "2026-10-08",
  updatedAt: "2026-10-08",
  channels: [
    {
      channelName: "VantaCore",
      channelUrl: "https://www.youtube.com/channel/UCLaBlLjvWDx3Ontq0ilsrig",
      topic: "Entertainment, Military",
      subscribers: 108000,
      subsGained30d: 34600,
      growthPct: 47.1,
      viewsGained30d: 211077018,
      channelCreatedAt: "2025-10-03",
    },
    {
      channelName: "ARMY LOVER",
      channelUrl: "https://www.youtube.com/channel/UCG9ZNapZqh2B6YGF1khf-gg",
      topic: "Military, Lifestyle (sociology)",
      subscribers: 131000,
      subsGained30d: 30000,
      growthPct: 29.7,
      viewsGained30d: 23836709,
      channelCreatedAt: "2024-04-27",
    },
    {
      channelName: "@HindustaniHeroes",
      channelUrl: "https://www.youtube.com/channel/UCwZrgrwjnG-zLQWOAFMVhew",
      topic: "Society, Military",
      subscribers: 166000,
      subsGained30d: 33000,
      growthPct: 24.8,
      viewsGained30d: 38777991,
      channelCreatedAt: "2025-07-19",
    },
    {
      channelName: "VEER JAWAN",
      channelUrl: "https://www.youtube.com/channel/UCCL3GKYsGaBEgwk47MMiGFw",
      topic: "Society, Military",
      subscribers: 449000,
      subsGained30d: 81000,
      growthPct: 22.0,
      viewsGained30d: 326634297,
      channelCreatedAt: "2018-03-19",
    },
    {
      channelName: "Desh🇮🇳Bhakti",
      channelUrl: "https://www.youtube.com/channel/UCJsBRmhMd4KPU_cQxtH4PrQ",
      topic: "Entertainment, Military",
      subscribers: 377000,
      subsGained30d: 42000,
      growthPct: 12.5,
      viewsGained30d: 28187130,
      channelCreatedAt: "2025-08-11",
    },
    {
      channelName: "Патриот России🇷🇺",
      channelUrl: "https://www.youtube.com/channel/UCSD8nWjs-F7CbHH6ZRYkZXA",
      topic: "Society, Military",
      subscribers: 175000,
      subsGained30d: 18000,
      growthPct: 11.5,
      viewsGained30d: 3784704,
      channelCreatedAt: "2019-02-02",
    },
    {
      channelName: "Zoom Drishti",
      channelUrl: "https://www.youtube.com/channel/UCvfO3YVl3C7o9anCgEXMstQ",
      topic: "Society, Military",
      subscribers: 66400,
      subsGained30d: 6200,
      growthPct: 10.3,
      viewsGained30d: 2307899,
      channelCreatedAt: "2025-11-11",
    },
    {
      channelName: "VotFakt",
      channelUrl: "https://www.youtube.com/channel/UCAjwH0CeOCtVIdp_2zLi3_A",
      topic: "Military, Society",
      subscribers: 95600,
      subsGained30d: 8900,
      growthPct: 10.3,
      viewsGained30d: 21277966,
      channelCreatedAt: "2023-02-17",
    },
    {
      channelName: "Special Forces TV",
      channelUrl: "https://www.youtube.com/channel/UCRvB7vscpepPN38-ECZjcTQ",
      topic: "Military, Society",
      subscribers: 63400,
      subsGained30d: 5100,
      growthPct: 8.7,
      viewsGained30d: 2531155,
      channelCreatedAt: "2024-01-09",
    },
    {
      channelName: "Indian Army ( News )",
      channelUrl: "https://www.youtube.com/channel/UCX39fWjX_EBTmka_kx2Jt6w",
      topic: "Military, Society",
      subscribers: 117000,
      subsGained30d: 9000,
      growthPct: 8.3,
      viewsGained30d: 13560312,
      channelCreatedAt: "2018-06-27",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "VantaCore",
    note: "a newer channel (created 2025) that gained 34,600 subscribers in 30 days, a 47.1% increase over its subscriber base a month earlier",
  },
};
