// Single source of truth for the YouTube Society channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Society" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeSocietyReport: YoutubeNicheReport = {
  niche: "Society",
  region: "global",
  dataAsOf: "2026-10-09",
  updatedAt: "2026-10-09",
  channels: [
    {
      channelName: "Amira Arora & Aryaan Arora",
      channelUrl: "https://www.youtube.com/channel/UCzuo1FFstOnPOTirMfD0tjg",
      topic: "Religion, Society",
      subscribers: 1310000,
      subsGained30d: 1008000,
      growthPct: 333.8,
      viewsGained30d: 13828669,
      channelCreatedAt: "2023-06-03",
    },
    {
      channelName: "Lecciones De Sabios",
      channelUrl: "https://www.youtube.com/channel/UCnKM6eWPSHKhA65L4HOI1ZQ",
      topic: "Society, Religion",
      subscribers: 208000,
      subsGained30d: 159200,
      growthPct: 326.2,
      viewsGained30d: 2693879,
      channelCreatedAt: "2025-05-16",
    },
    {
      channelName: "TOXIC ROSTER",
      channelUrl: "https://www.youtube.com/channel/UCDHz3eq0FIFHGomcEE2r1pg",
      topic: "Religion, Society",
      subscribers: 74500,
      subsGained30d: 49500,
      growthPct: 198.0,
      viewsGained30d: 6673930,
      channelCreatedAt: "2023-01-16",
    },
    {
      channelName: "제게 용기를 주세요.",
      channelUrl: "https://www.youtube.com/channel/UC9UlH4_AroLjzER6e7nPxmg",
      topic: "Society",
      subscribers: 62000,
      subsGained30d: 38800,
      growthPct: 167.2,
      viewsGained30d: 11664445,
      channelCreatedAt: "2022-12-11",
    },
    {
      channelName: "Reimer Thoughts by Erich Reimer",
      channelUrl: "https://www.youtube.com/channel/UCaO4aArN90oLLWpiu-1zfUw",
      topic: "Society, Politics",
      subscribers: 114000,
      subsGained30d: 65700,
      growthPct: 136.0,
      viewsGained30d: 2490674,
      channelCreatedAt: "2025-06-01",
    },
    {
      channelName: "HANS",
      channelUrl: "https://www.youtube.com/channel/UChlBdEx0pwDXpG13VSxe-KQ",
      topic: "Society, Politics",
      subscribers: 77000,
      subsGained30d: 42600,
      growthPct: 123.8,
      viewsGained30d: 3946008,
      channelCreatedAt: "2018-01-09",
    },
    {
      channelName: "Malwa Abhitak मालवा अभीतक (सबसे तेज खबरे)",
      channelUrl: "https://www.youtube.com/channel/UCZF8JMVuSpQVJwceqhyQB4A",
      topic: "Politics, Society",
      subscribers: 52200,
      subsGained30d: 28200,
      growthPct: 117.5,
      viewsGained30d: 12635846,
      channelCreatedAt: "2014-01-25",
    },
    {
      channelName: "Vinay RB",
      channelUrl: "https://www.youtube.com/channel/UCJqENBvMNX8h2dpOdqPakUQ",
      topic: "Knowledge, Society",
      subscribers: 64300,
      subsGained30d: 34500,
      growthPct: 115.8,
      viewsGained30d: 4577003,
      channelCreatedAt: "2024-09-21",
    },
    {
      channelName: "Marco Romero",
      channelUrl: "https://www.youtube.com/channel/UCcFfkvEIu2Nyj8zz0-kY94w",
      topic: "Society, Knowledge",
      subscribers: 52800,
      subsGained30d: 28000,
      growthPct: 112.9,
      viewsGained30d: 1108,
      channelCreatedAt: "2025-12-03",
    },
    {
      channelName: "Smart Jyotish",
      channelUrl: "https://www.youtube.com/channel/UC-ZvaMJs9osz9Cf56zC5UJA",
      topic: "Religion, Society",
      subscribers: 50500,
      subsGained30d: 26500,
      growthPct: 110.4,
      viewsGained30d: 14091165,
      channelCreatedAt: "2026-03-26",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Amira Arora & Aryaan Arora",
    note: "an established channel (created 2023) that gained 1,008,000 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
