// Single source of truth for the YouTube Action game channel growth report
// (part of Video game culture).
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Action game" with at most one
// other YouTube topic tag, subscribers >= 50,000, had at least
// 20,000 subscribers before the last 30 days, 30-day history complete,
// latest_stat_date within the last 3 days). growthPct = subsGained30d /
// (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeSubgenreReport } from "./youtube-subgenre-report-types";

export const youtubeActionGameSubReport: YoutubeSubgenreReport = {
  subgenre: "Action game",
  parentCategory: "Video game culture",
  parentSlug: "gaming",
  region: "global",
  dataAsOf: "2026-10-08",
  updatedAt: "2026-10-08",
  channels: [
    {
      channelName: "Mʀ Pᴜʀᴘʟᴇ Oɴᴇ",
      channelUrl: "https://www.youtube.com/channel/UCM7RF0sKSApJ_V6YbdeWGlw",
      topic: "Video game culture, Action game",
      subscribers: 372000,
      subsGained30d: 290800,
      growthPct: 358.1,
      viewsGained30d: 6453040,
      channelCreatedAt: "2022-09-16",
    },
    {
      channelName: "Eurofihl",
      channelUrl: "https://www.youtube.com/channel/UCC30G2aahpAdA_0Mtj3gf8w",
      topic: "Video game culture, Action game",
      subscribers: 89300,
      subsGained30d: 63100,
      growthPct: 240.8,
      viewsGained30d: 1931798,
      channelCreatedAt: "2023-02-08",
    },
    {
      channelName: "JYMZ",
      channelUrl: "https://www.youtube.com/channel/UCzUEytJj-zpQFEWnlWqVGGg",
      topic: "Video game culture, Action game",
      subscribers: 244000,
      subsGained30d: 144800,
      growthPct: 146.0,
      viewsGained30d: 1906284,
      channelCreatedAt: "2025-04-14",
    },
    {
      channelName: "His Bloxy",
      channelUrl: "https://www.youtube.com/channel/UCPVt8nbUmxQvbb1k_AiWLLQ",
      topic: "Video game culture, Action game",
      subscribers: 107000,
      subsGained30d: 58400,
      growthPct: 120.2,
      viewsGained30d: 3921171,
      channelCreatedAt: "2025-09-01",
    },
    {
      channelName: "Ex Winx ff",
      channelUrl: "https://www.youtube.com/channel/UCQv27MELiF4A7Xlzgb-5cew",
      topic: "Video game culture, Action game",
      subscribers: 53000,
      subsGained30d: 28700,
      growthPct: 118.1,
      viewsGained30d: 11253861,
      channelCreatedAt: "2025-07-24",
    },
    {
      channelName: "SCARY GAMER",
      channelUrl: "https://www.youtube.com/channel/UCMKx29aJgj82IRdCIisC1gw",
      topic: "Video game culture, Action game",
      subscribers: 85600,
      subsGained30d: 45800,
      growthPct: 115.1,
      viewsGained30d: 4581772,
      channelCreatedAt: "2025-02-28",
    },
    {
      channelName: "ardytemanfora",
      channelUrl: "https://www.youtube.com/channel/UCAsBY7YRmlUNDO0Hac6hbJw",
      topic: "Action game, Video game culture",
      subscribers: 65000,
      subsGained30d: 33600,
      growthPct: 107.0,
      viewsGained30d: 7361056,
      channelCreatedAt: "2025-06-30",
    },
    {
      channelName: "Black Bunny",
      channelUrl: "https://www.youtube.com/channel/UCzraguiKnOSb9oH5n_JYq0g",
      topic: "Action game, Video game culture",
      subscribers: 66700,
      subsGained30d: 34300,
      growthPct: 105.9,
      viewsGained30d: 18459708,
      channelCreatedAt: "2022-02-04",
    },
    {
      channelName: "Yt-Aayanshgaming",
      channelUrl: "https://www.youtube.com/channel/UCA0hO9nB1B1_T3nHBb6RwOA",
      topic: "Action game, Video game culture",
      subscribers: 207000,
      subsGained30d: 106000,
      growthPct: 105.0,
      viewsGained30d: 2913216,
      channelCreatedAt: "2024-04-04",
    },
    {
      channelName: "Medal",
      channelUrl: "https://www.youtube.com/channel/UCs1xWFLN__Txt6QqFkxRpRA",
      topic: "Action game, Video game culture",
      subscribers: 150000,
      subsGained30d: 70400,
      growthPct: 88.4,
      viewsGained30d: 42343518,
      channelCreatedAt: "2017-06-21",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline, filtered to this one subgenre tag nested inside the broader Video game culture niche. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the match tight.",
  highlightChannel: {
    channelName: "Mʀ Pᴜʀᴘʟᴇ Oɴᴇ",
    note: "an established channel (created 2022) that gained 290,800 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
