// Single source of truth for the YouTube Lifestyle (sociology) channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Lifestyle (sociology)" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeLifestyleReport: YoutubeNicheReport = {
  niche: "Lifestyle (sociology)",
  region: "global",
  dataAsOf: "2026-10-10",
  updatedAt: "2026-10-10",
  channels: [
    {
      channelName: "Flex Fact",
      channelUrl: "https://www.youtube.com/channel/UCCRHPtFyp3RrFLojljUwVmA",
      topic: "Hobby, Lifestyle (sociology)",
      subscribers: 453000,
      subsGained30d: 406800,
      growthPct: 880.5,
      viewsGained30d: 16834256,
      channelCreatedAt: "2025-09-20",
    },
    {
      channelName: "KinTirob",
      channelUrl: "https://www.youtube.com/channel/UCXslVaWv7lLmU_Atb1B0cTA",
      topic: "Entertainment, Lifestyle (sociology)",
      subscribers: 146000,
      subsGained30d: 125600,
      growthPct: 615.7,
      viewsGained30d: 1941072,
      channelCreatedAt: "2026-01-27",
    },
    {
      channelName: "Spoorthi Mandapati",
      channelUrl: "https://www.youtube.com/channel/UCsPXJ9ldKevTwPmLrkDHVCA",
      topic: "Hobby, Lifestyle (sociology)",
      subscribers: 230000,
      subsGained30d: 195200,
      growthPct: 560.9,
      viewsGained30d: 18739,
      channelCreatedAt: "2019-08-11",
    },
    {
      channelName: "Kai ASMR",
      channelUrl: "https://www.youtube.com/channel/UCMeFWANbmyol84o4rZDkHVA",
      topic: "Lifestyle (sociology)",
      subscribers: 324000,
      subsGained30d: 274700,
      growthPct: 557.2,
      viewsGained30d: 827626397,
      channelCreatedAt: "2018-09-18",
    },
    {
      channelName: "Mateus Silva jr",
      channelUrl: "https://www.youtube.com/channel/UCJ7qELxe_pAObhAgHLIgBTg",
      topic: "Entertainment, Lifestyle (sociology)",
      subscribers: 160000,
      subsGained30d: 125600,
      growthPct: 365.1,
      viewsGained30d: 3739455,
      channelCreatedAt: "2015-12-06",
    },
    {
      channelName: "Court Uncovered",
      channelUrl: "https://www.youtube.com/channel/UCgss75ClZ7egCAA8s7kRYqA",
      topic: "Lifestyle (sociology)",
      subscribers: 133000,
      subsGained30d: 100300,
      growthPct: 306.7,
      viewsGained30d: 65701578,
      channelCreatedAt: "2025-12-14",
    },
    {
      channelName: "Creature Vault",
      channelUrl: "https://www.youtube.com/channel/UC6rD9e3rQ2LRd1pX8uR8zvQ",
      topic: "Knowledge, Lifestyle (sociology)",
      subscribers: 413000,
      subsGained30d: 307000,
      growthPct: 289.6,
      viewsGained30d: 13545834,
      channelCreatedAt: "2025-09-19",
    },
    {
      channelName: "LyraLStory",
      channelUrl: "https://www.youtube.com/channel/UCSPbZoaGkho_3gZpZXKz31g",
      topic: "Lifestyle (sociology), Entertainment",
      subscribers: 308000,
      subsGained30d: 228700,
      growthPct: 288.4,
      viewsGained30d: 4795075,
      channelCreatedAt: "2025-05-16",
    },
    {
      channelName: "Haryanvi Saas Bhu Rasoi",
      channelUrl: "https://www.youtube.com/channel/UCHRCTZ3WcYl_JDIP6Ti_7wA",
      topic: "Entertainment, Lifestyle (sociology)",
      subscribers: 250000,
      subsGained30d: 184500,
      growthPct: 281.7,
      viewsGained30d: 60463760,
      channelCreatedAt: "2026-02-06",
    },
    {
      channelName: "Ash Dykes",
      channelUrl: "https://www.youtube.com/channel/UCholW9FU8n9pCE_3OK6t2Lw",
      topic: "Lifestyle (sociology)",
      subscribers: 152000,
      subsGained30d: 110900,
      growthPct: 269.8,
      viewsGained30d: 2712205,
      channelCreatedAt: "2013-04-04",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Flex Fact",
    note: "a newer channel (created 2025) that gained 406,800 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
