// Single source of truth for the YouTube Basketball channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Basketball" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeBasketballReport: YoutubeNicheReport = {
  niche: "Basketball",
  region: "global",
  dataAsOf: "2026-10-07",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Bernadine Moen",
      channelUrl: "https://www.youtube.com/channel/UCcsb3MfmP--lFYVNOUS4ggQ",
      topic: "Sport, Basketball",
      subscribers: 56400,
      subsGained30d: 8600,
      growthPct: 18.0,
      viewsGained30d: 9546421,
      channelCreatedAt: "2025-07-19",
    },
    {
      channelName: "Hayden Jones",
      channelUrl: "https://www.youtube.com/channel/UCUgouh8Az3p3fzyCJvNs-eg",
      topic: "Basketball, Sport",
      subscribers: 1920000,
      subsGained30d: 280000,
      growthPct: 17.1,
      viewsGained30d: 32341891,
      channelCreatedAt: "2017-04-16",
    },
    {
      channelName: "Jayden Beloti",
      channelUrl: "https://www.youtube.com/channel/UCR7rAVnTwwNkGpanJb28qvw",
      topic: "Basketball, Sport",
      subscribers: 133000,
      subsGained30d: 19000,
      growthPct: 16.7,
      viewsGained30d: 18344323,
      channelCreatedAt: "2014-06-15",
    },
    {
      channelName: "Philadelphia 76ers",
      channelUrl: "https://www.youtube.com/channel/UC5qJUyng_ezl0TVjVJFqtfQ",
      topic: "Basketball, Sport",
      subscribers: 124000,
      subsGained30d: 16000,
      growthPct: 14.8,
      viewsGained30d: 3098493,
      channelCreatedAt: "2006-06-12",
    },
    {
      channelName: "농구분석가 농떼르만 [김진용]",
      channelUrl: "https://www.youtube.com/channel/UCF7m9V1DiHORGTmNrkHrT5Q",
      topic: "Sport, Basketball",
      subscribers: 65600,
      subsGained30d: 8300,
      growthPct: 14.5,
      viewsGained30d: 18973575,
      channelCreatedAt: "2021-03-03",
    },
    {
      channelName: "ZedBall",
      channelUrl: "https://www.youtube.com/channel/UCQaUyVUXDEHS6m1KWW4K8VA",
      topic: "Basketball, Sport",
      subscribers: 218000,
      subsGained30d: 27000,
      growthPct: 14.1,
      viewsGained30d: 22598581,
      channelCreatedAt: "2024-10-27",
    },
    {
      channelName: "The Phillips Brothers",
      channelUrl: "https://www.youtube.com/channel/UCvFdSjbqpWSCjQFutJOhyRA",
      topic: "Basketball, Sport",
      subscribers: 89100,
      subsGained30d: 10100,
      growthPct: 12.8,
      viewsGained30d: 7820417,
      channelCreatedAt: "2011-10-11",
    },
    {
      channelName: "Connor Essegian",
      channelUrl: "https://www.youtube.com/channel/UCOt7j6WhKaDYHCWp2_lPAng",
      topic: "Sport, Basketball",
      subscribers: 55500,
      subsGained30d: 5800,
      growthPct: 11.7,
      viewsGained30d: 2417240,
      channelCreatedAt: "2024-05-05",
    },
    {
      channelName: "Breakaway Clips",
      channelUrl: "https://www.youtube.com/channel/UCHLQXoPj6jCe7KwxGzPaTsA",
      topic: "Sport, Basketball",
      subscribers: 107000,
      subsGained30d: 10700,
      growthPct: 11.1,
      viewsGained30d: 49541102,
      channelCreatedAt: "2025-12-17",
    },
    {
      channelName: "SAVI Coaching",
      channelUrl: "https://www.youtube.com/channel/UCeWWGsIbnBQW0tdJTObakKg",
      topic: "Basketball, Sport",
      subscribers: 70200,
      subsGained30d: 6900,
      growthPct: 10.9,
      viewsGained30d: 634626,
      channelCreatedAt: "2021-04-07",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Bernadine Moen",
    note: "a newer channel (created 2025) that gained 8,600 subscribers in 30 days, a 18.0% increase over its subscriber base a month earlier",
  },
};
