// Single source of truth for the YouTube Cricket channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Cricket" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeCricketReport: YoutubeNicheReport = {
  niche: "Cricket",
  region: "global",
  dataAsOf: "2026-10-07",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Sports Cricket Hub",
      channelUrl: "https://www.youtube.com/channel/UCjg4n1MdNfyenSj0tw2g5TA",
      topic: "Sport, Cricket",
      subscribers: 115000,
      subsGained30d: 16000,
      growthPct: 16.2,
      viewsGained30d: 8035873,
      channelCreatedAt: "2026-02-26",
    },
    {
      channelName: "AAM INSAAN",
      channelUrl: "https://www.youtube.com/channel/UCxXpG1IzuYDeQnRt-QNSIjw",
      topic: "Sport, Cricket",
      subscribers: 74400,
      subsGained30d: 10300,
      growthPct: 16.1,
      viewsGained30d: 30489598,
      channelCreatedAt: "2023-06-23",
    },
    {
      channelName: "Crick Media",
      channelUrl: "https://www.youtube.com/channel/UClSCcU9CgyquaRSuSsCQa9w",
      topic: "Sport, Cricket",
      subscribers: 58700,
      subsGained30d: 6400,
      growthPct: 12.2,
      viewsGained30d: 3961326,
      channelCreatedAt: "2025-06-26",
    },
    {
      channelName: "SH cric Talk",
      channelUrl: "https://www.youtube.com/channel/UCFvO6YuvDulkULDinP_fglg",
      topic: "Cricket, Sport",
      subscribers: 83300,
      subsGained30d: 9000,
      growthPct: 12.1,
      viewsGained30d: 39440495,
      channelCreatedAt: "2024-06-24",
    },
    {
      channelName: "hungerforcricket",
      channelUrl: "https://www.youtube.com/channel/UCkXo1JdGnjxrOrZzWHtYTQQ",
      topic: "Sport, Cricket",
      subscribers: 316000,
      subsGained30d: 32000,
      growthPct: 11.3,
      viewsGained30d: 212835148,
      channelCreatedAt: "2018-03-06",
    },
    {
      channelName: "RICKET LK",
      channelUrl: "https://www.youtube.com/channel/UCeFpMHjzvTU_4ISIeKNhSew",
      topic: "Sport, Cricket",
      subscribers: 78100,
      subsGained30d: 7100,
      growthPct: 10.0,
      viewsGained30d: 2038284,
      channelCreatedAt: "2020-06-13",
    },
    {
      channelName: "Rahul Sah crick react",
      channelUrl: "https://www.youtube.com/channel/UCLTzi5w0q_Q6aSZqzzdZb_Q",
      topic: "Sport, Cricket",
      subscribers: 76500,
      subsGained30d: 6900,
      growthPct: 9.9,
      viewsGained30d: 11241564,
      channelCreatedAt: "2022-12-24",
    },
    {
      channelName: "CricMemeSter",
      channelUrl: "https://www.youtube.com/channel/UCjoAwFX6n5dy4nl_X0-mi9A",
      topic: "Sport, Cricket",
      subscribers: 513000,
      subsGained30d: 43000,
      growthPct: 9.1,
      viewsGained30d: 24491037,
      channelCreatedAt: "2019-06-26",
    },
    {
      channelName: "Cricket Vartalap",
      channelUrl: "https://www.youtube.com/channel/UC7G49ri-6II6NFfaN0L_O9w",
      topic: "Sport, Cricket",
      subscribers: 134000,
      subsGained30d: 8000,
      growthPct: 6.3,
      viewsGained30d: 15557933,
      channelCreatedAt: "2024-12-02",
    },
    {
      channelName: "The khel News • 210K views • 1 hours ago \\n\\n\\n...",
      channelUrl: "https://www.youtube.com/channel/UCJ9vS7TjdBYxPi0qsiKCsOA",
      topic: "Cricket, Sport",
      subscribers: 156000,
      subsGained30d: 9000,
      growthPct: 6.1,
      viewsGained30d: 5961786,
      channelCreatedAt: "2025-12-31",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Sports Cricket Hub",
    note: "a newer channel (created 2026) that gained 16,000 subscribers in 30 days, a 16.2% increase over its subscriber base a month earlier",
  },
};
