// Single source of truth for the YouTube Vehicle channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Vehicle" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeVehiclesReport: YoutubeNicheReport = {
  niche: "Vehicle",
  region: "global",
  dataAsOf: "2026-10-08",
  updatedAt: "2026-10-08",
  channels: [
    {
      channelName: "Nostalgia Car POV Drives",
      channelUrl: "https://www.youtube.com/channel/UCN3bdqvg2EdqUpmLY2vB8lw",
      topic: "Lifestyle (sociology), Vehicle",
      subscribers: 137000,
      subsGained30d: 66100,
      growthPct: 93.2,
      viewsGained30d: 472586,
      channelCreatedAt: "2009-09-16",
    },
    {
      channelName: "Bjune Works",
      channelUrl: "https://www.youtube.com/channel/UC3evoavF2m-pZuc31ug8iSg",
      topic: "Lifestyle (sociology), Vehicle",
      subscribers: 111000,
      subsGained30d: 52900,
      growthPct: 91.0,
      viewsGained30d: 83304563,
      channelCreatedAt: "2025-04-19",
    },
    {
      channelName: "LITH-TECH MOBILITY",
      channelUrl: "https://www.youtube.com/channel/UCCt7A-U0mHI8wMTvvb86c6Q",
      topic: "Vehicle, Lifestyle (sociology)",
      subscribers: 77800,
      subsGained30d: 36400,
      growthPct: 87.9,
      viewsGained30d: 638679,
      channelCreatedAt: "2019-01-27",
    },
    {
      channelName: "Maxlider Bros. Broncos, Tacos & Golf!",
      channelUrl: "https://www.youtube.com/channel/UC0kehgOavLrc8BOugznxpbQ",
      topic: "Lifestyle (sociology), Vehicle",
      subscribers: 64100,
      subsGained30d: 25600,
      growthPct: 66.5,
      viewsGained30d: 295832,
      channelCreatedAt: "2016-12-22",
    },
    {
      channelName: "AVEXN",
      channelUrl: "https://www.youtube.com/channel/UCY978kXpidhx6ffAmoVIoAg",
      topic: "Vehicle, Lifestyle (sociology)",
      subscribers: 76000,
      subsGained30d: 28600,
      growthPct: 60.3,
      viewsGained30d: 22457121,
      channelCreatedAt: "2023-08-04",
    },
    {
      channelName: "Drive Goal",
      channelUrl: "https://www.youtube.com/channel/UCCBfRwe1wN2w2PgGfsyvxnQ",
      topic: "Vehicle, Lifestyle (sociology)",
      subscribers: 95300,
      subsGained30d: 34800,
      growthPct: 57.5,
      viewsGained30d: 63311686,
      channelCreatedAt: "2025-04-04",
    },
    {
      channelName: "Railway Fans Club",
      channelUrl: "https://www.youtube.com/channel/UCvcOZcKYgAUP6wu5MAlchBA",
      topic: "Vehicle, Lifestyle (sociology)",
      subscribers: 68400,
      subsGained30d: 24800,
      growthPct: 56.9,
      viewsGained30d: 25072502,
      channelCreatedAt: "2012-05-28",
    },
    {
      channelName: "Rail and Travels",
      channelUrl: "https://www.youtube.com/channel/UCXODUekPbLs8kCODtg8chOg",
      topic: "Vehicle, Lifestyle (sociology)",
      subscribers: 54700,
      subsGained30d: 19700,
      growthPct: 56.3,
      viewsGained30d: 32277625,
      channelCreatedAt: "2025-01-21",
    },
    {
      channelName: "Terminal 2W",
      channelUrl: "https://www.youtube.com/channel/UCHy3nnMa5pyD9woj3fKPzeg",
      topic: "Lifestyle (sociology), Vehicle",
      subscribers: 92000,
      subsGained30d: 32700,
      growthPct: 55.1,
      viewsGained30d: 186165,
      channelCreatedAt: "2024-10-20",
    },
    {
      channelName: "Pay attention to Thrilling road",
      channelUrl: "https://www.youtube.com/channel/UCUN6VTH7RoCSyzpLMQb60Bg",
      topic: "Vehicle, Lifestyle (sociology)",
      subscribers: 129000,
      subsGained30d: 44700,
      growthPct: 53.0,
      viewsGained30d: 31753524,
      channelCreatedAt: "2025-02-18",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Nostalgia Car POV Drives",
    note: "an established channel (created 2009) that gained 66,100 subscribers in 30 days, a 93.2% increase over its subscriber base a month earlier",
  },
};
