// Single source of truth for the YouTube Sport channel growth report.
// Generated by scripts/generate-youtube-reports.py from ClickHouse
// `vira_analytics.channels_latest_mat` (topic contains "Sport" with at most one other
// YouTube topic tag, subscribers >= 50,000, had at least 20,000
// subscribers before the last 30 days, 30-day history complete, latest_stat_date within the last
// 3 days). growthPct = subsGained30d / (subscribers - subsGained30d) * 100.
// Do not hand-edit the numbers here -- rerun the generator instead. The same object feeds the
// human-readable page, /llms-full.txt and the JSON-LD blocks, so a change here changes all three
// at once (no drift between "visible" and "AI-facing" content).

import type { YoutubeNicheReport } from "./youtube-report-types";

export const youtubeSportsReport: YoutubeNicheReport = {
  niche: "Sport",
  region: "global",
  dataAsOf: "2026-10-07",
  updatedAt: "2026-10-07",
  channels: [
    {
      channelName: "Artex",
      channelUrl: "https://www.youtube.com/channel/UCsntXZKABoxqvWmdwDxdONA",
      topic: "Sport, Association football",
      subscribers: 155000,
      subsGained30d: 118700,
      growthPct: 327.0,
      viewsGained30d: 39927061,
      channelCreatedAt: "2019-08-31",
    },
    {
      channelName: "Crest Count",
      channelUrl: "https://www.youtube.com/channel/UCZkxJCXJ4yYM8YX3ogXX5pQ",
      topic: "Sport, Entertainment",
      subscribers: 116000,
      subsGained30d: 66300,
      growthPct: 133.4,
      viewsGained30d: 2156271,
      channelCreatedAt: "2025-11-18",
    },
    {
      channelName: "KING PLAYER",
      channelUrl: "https://www.youtube.com/channel/UCrhzIFmFwvb9Xegt_q561aw",
      topic: "Video game culture, Sports game",
      subscribers: 116000,
      subsGained30d: 54600,
      growthPct: 88.9,
      viewsGained30d: 45532276,
      channelCreatedAt: "2020-02-01",
    },
    {
      channelName: "SHORTS LM",
      channelUrl: "https://www.youtube.com/channel/UCixGm7bCi8jawA4XRdbbbQA",
      topic: "Sport, Association football",
      subscribers: 75200,
      subsGained30d: 34000,
      growthPct: 82.5,
      viewsGained30d: 108048881,
      channelCreatedAt: "2026-01-16",
    },
    {
      channelName: "GD KAI YT",
      channelUrl: "https://www.youtube.com/channel/UC5h_Q7VlX2GpnN7Zl7sYS3g",
      topic: "Sport, Entertainment",
      subscribers: 104000,
      subsGained30d: 45700,
      growthPct: 78.4,
      viewsGained30d: 7000260,
      channelCreatedAt: "2024-11-21",
    },
    {
      channelName: "R PES GAMING",
      channelUrl: "https://www.youtube.com/channel/UC0sKozOrglalgTLlsne6BlQ",
      topic: "Video game culture, Sports game",
      subscribers: 100000,
      subsGained30d: 43800,
      growthPct: 77.9,
      viewsGained30d: 3020489,
      channelCreatedAt: "2020-05-16",
    },
    {
      channelName: "Global Champions League",
      channelUrl: "https://www.youtube.com/channel/UC2eRUmCc9VZsm8oGcRzw7kg",
      topic: "Sport, Lifestyle (sociology)",
      subscribers: 109000,
      subsGained30d: 43800,
      growthPct: 67.2,
      viewsGained30d: 186675,
      channelCreatedAt: "2016-01-12",
    },
    {
      channelName: "football ⚽",
      channelUrl: "https://www.youtube.com/channel/UCH8kjkJHvxPcNjO01hok-OQ",
      topic: "Sport, Association football",
      subscribers: 51900,
      subsGained30d: 20400,
      growthPct: 64.8,
      viewsGained30d: 9954382,
      channelCreatedAt: "2025-08-14",
    },
    {
      channelName: "yasinogabuga",
      channelUrl: "https://www.youtube.com/channel/UCb0L1jbQytUliLqX7WW62-g",
      topic: "Sport, Association football",
      subscribers: 74900,
      subsGained30d: 28000,
      growthPct: 59.7,
      viewsGained30d: 14859218,
      channelCreatedAt: "2020-08-21",
    },
    {
      channelName: "Nexxo Recaps",
      channelUrl: "https://www.youtube.com/channel/UCY-2QRPXfHfcDDugOUr7A8Q",
      topic: "Sport, Entertainment",
      subscribers: 733000,
      subsGained30d: 272000,
      growthPct: 59.0,
      viewsGained30d: 511273148,
      channelCreatedAt: "2026-01-10",
    },
  ],
  methodologyNote:
    "YouTube public channel statistics (subscribers, views), collected daily by Vira's own channel-tracking pipeline. Growth % = subscribers gained in the last 30 days divided by the subscriber count 30 days ago, shown only for channels with a complete 30-day history and at least 50,000 current subscribers. Topic is YouTube's own classification for the channel, not Vira's; channels with more than 2 topic tags are excluded to keep the niche match tight.",
  highlightChannel: {
    channelName: "Artex",
    note: "an established channel (created 2019) that gained 118,700 subscribers in 30 days, more than its entire subscriber base a month earlier",
  },
};
